#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit02}}}: ejercicios

#+PROPERTY: header-args:R :session *R-ec1047-size*
#+PROPERTY: header-args:R+ :tangle yes
#+PROPERTY: header-args:R+ :exports both
#+PROPERTY: header-args:R+ :results output

#+BEGIN_SRC R :exports none :tangle no :results silent
  ## Set output width
  options(width = 70, cli.width = 70, crayon.enabled = FALSE,
          xtable.type = "latex",
          xtable.floating = TRUE,
          xtable.table.placement = "H",
          xtable.include.rownames = FALSE,
          xtable.booktabs = TRUE,
          readr.show_progress = FALSE)

  my_colnames_sanitize <- function(str) {
     paste("{", xtable::sanitize(str), "}", sep = "")
  }

  options(xtable.sanitize.colnames.function = my_colnames_sanitize)

  ## load R libraries
  library(tidyverse)
  library(xtable)
  library(zoo)
  library(broom)
#+END_SRC


Responda a las siguientes preguntas a partir de la información
estadística contenida en las publicaciones:

- [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iaavanceactuacioneconomica.aspx][Avance de la actuación económica y financiera de las
  Administraciones Públicas (2018)]], IGAE.
- [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iacogof.aspx][Informe sobre la clasificación funcional del gasto público (COFOG). Período 2015-2019]], IGAE.
- [[https://www.oecd-ilibrary.org/governance/government-at-a-glance_22214399][Government at a glance 2019]], OECD.

* Q.1

¿A cuánto asciende el gasto público en España en los últimos años?
¿Qué porcentaje con respecto al PIB representa el gasto público?  ¿Es
muy diferente esta última cifra con la media para los países de la
OECD?

** Answer

Utilicemos unas cuantas órdenes de R para conseguir un efecto nada
desdeñable, por si fuera poco:

#+name: Q1a
#+begin_src R :results output verbatim latex :exports results
  Q1a <- read_csv("./data/PR1_Q1a_db.csv", col_types = "iddddd") %>%
    mutate(G = G / 1000, PIB = PIB / 1000)

  Q1a_tab <- Q1a %>%
    select(year, G, PIB, Gpct) %>%
    filter(year > 2014)

  colnames(Q1a_tab) <-
    c("Año", "Gasto (billones €)", "PIB (billones €)", "Gasto (% sobre PIB)")
  xtable(Q1a_tab,
         caption = "Gasto público y PIB en España, 1995--2019.",
         align = c("c", "c", rep("T{5.}", 2), "T{2.1}"),
         digits = c(0, 0, 0, 0, 1))
#+end_src

#+begin_center
#+NAME: tbl:1
#+RESULTS: Q1a
#+end_center
Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta.

Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta.

Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta. Esto es una
respuesta. Esto es una respuesta. Esto es una respuesta.


#+NAME: fig1
#+header: :width 4.5 :height 2.78 :family "Times" :R-dev-args encoding = "ISOLatin9.enc"
#+begin_src R :results output graphics file :exports results :file figures/GY.pdf
  index <- Q1a %>% pull(year)
  ts_db <- zoo(Q1a %>% select(G, PIB), index)
  breaks <- c(200, 400, 600, 800, 1000)
  minor <- c(300, 500, 700, 900)
  ggplot(tidy(ts_db), aes(index, value, size = series)) +
    geom_line() +
    scale_y_log10(breaks = breaks, minor_breaks = minor) +
    scale_x_continuous(breaks = c(1995, 2000, 2005, 2010, 2015, 2020),
                       minor_breaks = c(1994, 1996, 1997, 1998, 1999,
                                        2001, 2002, 2003, 2004,
                                        2006, 2007, 2008, 2009,
                                        2011, 2012, 2013, 2014,
                                        2016, 2017, 2018, 2019,
                                        2021),
                       limits = c(1995, 2020)) +
    labs(x = NULL, y = NULL, size = NULL) +
    theme_bw() +
    scale_size_manual(values = c(0.3, 0.6)) +
    ggtitle("Miles de millones de €") +
    theme(legend.position = c(0.85, 0.13), legend.direction = "horizontal",
        panel.border = element_blank(), axis.line.x = element_line(size = 0.2),
        axis.line.y = element_line(size=0.2),
        text = element_text(size = 9),
        axis.text = element_text(size = 9),
        legend.text = element_text(size = 9),
        plot.title = element_text(size=9, face="plain", hjust = -0.075),
        plot.margin = rep(grid::unit(0.015,"npc"),4))
#+end_src

#+CAPTION: Gasto público y PIB de España, 1995--2019. Nada de esto habría sido posible sin la inestimable ayuda de todo lo que se te ocurra sin poder parar, Tampoco sabía muy bien qué era lo que iba a decir.
#+LABEL: fig:1
#+ATTR_LATEX: :placement [H]
#+RESULTS: fig1



#+NAME: fig2
#+header: :width 4.5 :height 2.78 :pointsize 8 :family "NewCenturySchoolbook"
#+begin_src R :results output graphics file :exports results :file figures/gGY.pdf
  index <- Q1a %>% pull(year)
  ts_db <- zoo(Q1a %>% select(gG, gY), index)
  breaks <- c(200, 400, 600, 800, 1000)
  minor <- c(300, 500, 700, 900)
  ggplot(tidy(ts_db), aes(index, value, size = series)) +
    geom_line() +
    geom_hline(yintercept = 0, size = 0.2, color = "gray") +
    scale_x_continuous(breaks = c(1995, 2000, 2005, 2010, 2015, 2020),
                       minor_breaks = c(1994, 1996, 1997, 1998, 1999,
                                        2001, 2002, 2003, 2004,
                                        2006, 2007, 2008, 2009,
                                        2011, 2012, 2013, 2014,
                                        2016, 2017, 2018, 2019,
                                        2021),
                       limits = c(1995, 2020)) +
    labs(x = NULL, y = NULL, size = NULL) +
    theme_bw() +
    scale_size_manual(values = c(0.3, 0.6)) +
    theme(legend.position = c(0.85, 0.13), legend.direction = "horizontal",
        panel.border = element_blank(), axis.line.x = element_line(size = 0.2),
        axis.line.y = element_line(size=0.2),
        text = element_text(size = 10))
#+end_src

#+CAPTION: Gasto público y PIB de España, 1995--2019. Nada de esto habría sido posible sin la inestimable ayuda de todo lo que se te ocurra sin poder parar, Tampoco sabía muy bien qué era lo que iba a decir.
#+LABEL: fig:2
#+ATTR_LATEX: :placement [H]
#+RESULTS: fig2



* Q.2

¿Cómo se distribuye el gasto público entre las diferentes
Administraciones Públicas?

** Answer

Esto es una respuesta.

* Q.3

Atendiendo a la clasificación funcional de los gastos, ¿qué grupos
de gasto tienen un mayor peso en España? ¿Cuáles son los grupos más
importantes para las diferentes Administraciones Públicas?

** Answer

Esto es una respuesta.

* Q.4

¿A cuanto ascienden los ingresos de las Administraciones Públicas
en España? ¿Qué porcentaje representan con respecto al PIB? ¿Es muy
diferente esta última cifra con la media para los países de la
OECD?

** Answer

Esto es una respuesta.

* Q.5

¿Cuál es el peso que tienen en España los impuestos directos, los
indirectos y las cotizaciones sociales?

** Answer

Esto es una respuesta.


* Q.6

¿Qué valor toma la presión fiscal en España? ¿Es muy diferente de
los países de nuestro entorno?

** Answer

Esto es una respuesta.

* Q.7

¿Cuál es el tamaño del déficit público en España? ¿Cómo se
distribuye este déficit en las diferentes Administraciones Públicas
que componen el Estado? ¿Es muy diferente el déficit de España del
de otros países de su entorno?
** Answer

Esto es una respuesta.



# Local Variables:
# ispell-local-dictionary: "spanish"
# End:
