# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: Ejercicios de los temas 2 a 5

* Q.1

Indique si cada una de las siguientes afirmaciones es cierta, falsa
o imprecisa y justifique su respuesta:

a) Si todo el mundo tiene la misma relación marginal de
   sustitución, entonces la asignación de recursos es eficiente en
   el sentido de Pareto.

b) Si la asignación de recursos es Pareto eficiente todo el mundo
   tiene la misma relación marginal de sustitución.

c) Cuando alguien se vacuna de sarampión está generando una
   externalidad positiva.

d) El Segundo Teorema Fundamental de la Economía del Bienestar dice
   que la asignación de recursos competitiva es socialmente deseable.

** Answer

Por hacer.

* Q.2

Considere un programa de formación dirigido a trabajadores
desempleados. El programa tiene una duración de un año y se estima
que los 200 participantes verán sus ingresos incrementarse en
\money{1000} al año durante los 10 años posteriores al programa. El
total de los salarios que perciben los formadores asciende
\money{1400000}. Los costes de materiales y suministros suponen
\money{1000} por cada participante. Determine el valor actual neto
del programa de formación para las siguientes tasas de descuento:
0%, 1%, 3%, 5% y 10%. ¿Para qué tasas de descuento sería viable el
programa de formación?

** Answer

Por hacer.
