#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit07}}}: ejercicios


* Q.1

Indique cuáles de las siguientes afirmaciones son verdaderas,
falsas o inciertas, y explique por qué.

a) Si tu consumo de tabaco produce externalidades negativas a tus
   compañeros de piso (las cuáles ignoras por completo), entonces
   estás fumando más de lo que sería eficiente.

b) Un impuesto sobre el tabaco hace que el mercado de cigarrillos
   funcione más eficientemente.

c) La prohibición del tabaco puede justificarse por razones de eficiencia.

d) La producción en un mercado competitivo con una externalidad
   negativa (sea del tipo que sea) es mayor que la producción
   socialmente óptima.


** Answer

a) /Verdadera/: si los fumadores no tienen en cuenta que cuando fuman
   reducen el bienestar de sus compañeros de piso, fumarán más de lo
   que sería eficiente.

b) /Incierta/: un impuesto reduce las ventas de cigarrillos, por lo
   que la ineficiencia asociada a los efectos externos disminuye o
   desaparece por completo. Pero un impuesto muy elevado podría
   reducir las ventas por debajo del nivel óptimo y generar una
   ineficiencia mayor.

c) /Falsa/: la presencia de externalidades negativas no implica que la
   cantidad socialmente óptima sea $0$. La prohibición reduciría la
   utilidad de los fumadores y eliminaría los beneficios de los
   productores de tabaco. Por otro lado, aumentaría la utilidad de los
   fumadores pasivos y los beneficios de los productores de
   sustitutivos del tabaco. A priori, no es posible saber si los
   beneficios de la prohibición serán mayores que sus costes.

d) /Verdadera/: cuando los agentes que generan externalidades
   negativas no las tienen en cuenta, producen o consumen una cantidad
   superior a la socialmente óptima.


* Q.2

En un pueblo pesquero las capturas mensuales totales de pescado, $Q$
(medidas en kg), dependen del número de barcas que faenan, $N$:
#+begin_export latex
\begin{equation*}
  Q = \num{1000} N^{1/2}.
\end{equation*}
#+end_export
Todas las barcas son idénticas y capturan la misma cantidad de pescado:
#+begin_export latex
\begin{equation*}
  q_i = Q / N.
\end{equation*}
#+end_export
Los costes mensuales de operar cada barca son de $c_i = \money{1000}$
al mes. El pescado se vende en un mercado competitivo a un precio de
$P = \price[kg]{6}$.  Inicialmente no hay ningún tipo de limitación al
número de barcas que operan en el pueblo.

a) Suponga que operan $16$ barcas. ¿Qué beneficios obtiene cada
   barca?

b) Si una barca más empieza a pescar, calcule el efecto externo que
   tienen que soportar los pescadores que ya estaban operando.

c) Calcule el número de barcas de equilibrio.

d) Calcule el número de barcas socialmente óptimo.

e) El ayuntamiento está considerando la posibilidad de introducir un
   sistema de licencias. ¿Qué precio debería fijar para cada licencia
   si quiere conseguir que opere el número socialmente óptimo de
   barcas?


** Answer

a) Cuando $N = 16$, cada barca produce:
   #+begin_export latex
   \[
     q_i = 1000 / 16^{1/2} = \units[kg]{250}.
   \]
   #+end_export
   Los beneficios de cada pescador son:
   #+begin_export latex
   \[
     \pi_i = P q_i - c_i = 6 \cdot 250 - 1000 = \money{500}.
   \]
   #+end_export

b) Si entra una nueva barca, la producción de cada pescador es:
   #+begin_export latex
   \[
     q_i = 1000 / 17^{1/2} \approx \units[kg]{242.54}.
   \]
   #+end_export
   En consecuencia, disminuye el beneficio de cada uno de los
   pescadores que faenaban antes de la entrada de la nueva barca:
   #+begin_export latex
   \[
     \Delta \pi_i = P \Delta q_i = 6 \cdot (242.54 - 250) = \money{-44.76}.
   \]
   #+end_export
   El efecto externo total sería: $16 \cdot (-44.76) =
   \money{-716,16}$.

c) Si no hay barreras a la entrada, los beneficios positivos atraerán
   a nuevos pescadores. En el equilibrio a largo plazo $\pi_i = 0$:
   #+begin_export latex
   \[
     \pi_i = 6 \cdot 1000 / N^{1/2} - 1000 = 0
   \]
   #+end_export
   Esta condición se satisface cuando $N = 36\,\text{barcas}$.

d) El número socialmente óptimo de barcas es el que maximiza el
   beneficio total de los pescadores:
   #+begin_export latex
   \[
     \max_{\{N\}} N \pi_i =
     N \big(6 \cdot 1000 / N^{1/2} - 1000\big) =
     6000 N^{1/2} - 1000 N.
   \]
   #+end_export
   Condición de primer orden:
   #+begin_export latex
   \[
      \frac{\diff N \pi_i}{\diff N} = 3000 N^{-1/2} - 1000 = 0.
   \]
   #+end_export
   Resolviendo la ecuación anterior, se obtiene que $9$ es el número
   eficiente de barcas.

e) Cuando $N = 9$ los beneficios individuales son:
   #+begin_export latex
   \[
     \pi_i(9) = 6 \cdot 1000 / 9^{1/2} - 1000 = \money{1000}
   \]
   #+end_export
   El ayuntamiento debería cobrar \money{1000} por cada licencia para
   desincentivar la entrada de más de 9 barcas (teniendo en cuenta que
   $N$ es un entero, bastaría con que cobrase \money{898} por
   licencia, cantidad que es ligeramente superior a $\pi_i(10)$).

* Q.3

Groucho y Harpo comparten camarote en un crucero. A Groucho le encanta
fumar sus puros durante la travesía. Harpo detesta los puros de
Groucho. La utilidad de los dos viajeros viene dada por las funciones:
#+begin_export latex
\begin{gather*}
U_G = 100 + 4 c - 0.1 c^2,
\intertext{y}
U_H = 100 - 10 c,
\end{gather*}
#+end_export
donde $c$ es el número de puros que fuma Groucho durante la travesía,
y $U_G$ y $U_H$ son las utilidades (medidas en euros) de Groucho y de
Harpo, respectivamente.

a) Si Groucho ignora las enérgicas protestas de su compañero de
   camarote y fuma todo lo que le apetece, ¿cuál será el valor de $c$?
   ¿Qué valores toman $U_G$ y $U_H$ en este caso?

b) ¿Es eficiente la solución anterior? Calcule el valor de $c$ que
   maximiza la función de bienestar $W = U_G + U_H$? ¿Qué valores
   toman $U_G$ y $U_H$ en este caso?

c) Chico, el capitán del barco, es un gran admirador de los trabajos
   de Coase y decide asignar a Groucho la capacidad de prohibir o no
   que se fume en el camarote. Si se establece una negociación entre
   Groucho y Harpo, ¿cuál sería el acuerdo que se alcanzaría?

c) Describa cómo cambiaría su respuesta al apartado anterior si Chico
   hubiese asignado a Harpo la capacidad de prohibir fumar en el
   camarote.


** Answer

a) La maximización de la utilidad de Groucho implica:
   #+begin_export latex
   \[
      \frac{\partial U_G}{\partial c} = 4 - 0.2 c = 0.
   \]
   #+end_export
   Groucho maximizaría su utilidad si fumara $20\,\text{puros}$.

b) La función de bienestar social es:
   #+begin_export latex
   \[
     W = U_G + U_H = 200 - 6 c -0.1 c^2.
   \]
   #+end_export
   Dado que $W$ es decreciente en $c$, el valor eficiente de $c$ es
   $0$. Las utilidades individuales serían: $U_G(0) = \money{100}$ y
   $U_H(0) = \money{100}$.

c) Cuando fuma, Groucho obtiene una utilidad equivalente a $U_G(20) =
   \money{140}$. Si no fuma su utilidad sería igual a $U_G(0) =
   \money{100}$. Estaría dispuesto a no fumar si se le compensara con
   al menos \money{40}.
   #+latex: \vspace*{1ex}

   Por otro lado, la utilidad de Harpo cuando Groucho fuma es $U_H(20)
   = \money{-100}$. Dado que $U_H(0) = 100$, Harpo estaría dispuesto a
   pagar hasta \money{200} para evitar que Groucho fume.
   #+latex: \vspace*{1ex}

   Como resultado de la negociación, Groucho no fumaría y Harpo le
   compensaría con un pago de entre \money{40} y \money{200}.

d) En este caso, Groucho pagaría como mucho $U_G(20) - U_G(0) =
   \money{40}$ para poder fumar. Sin embargo, Harpo exigiría una
   compensación de al menos $U_H(20) - U_H(0) = \money{200}$. Por
   tanto, Harpo no aceptaría la oferta de Groucho y éste no fumaría,
   $c = 0$.


* Q.4

Un producto se vende en un mercado competitivo. La curva de demanda es
$Q = 90 - P / 4$ y la de oferta es $Q = P / 6$. Al producir el bien se
vierten sustancias contaminantes que generan un daño a la sociedad
igual a $\DM = 2 Q$.

a) Obtenga y represente el equilibrio en este mercado en ausencia
   de cualquier tipo de intervención. Calcule la pérdida
   irrecuperable de eficiencia.

b) Para corregir la externalidad, el Gobierno quiere introducir un
   impuesto de $t$ euros por unidad producida. ¿Qué valor debe tomar
   $t$ para conseguir el nivel de producción socialmente óptimo?
   ¿Cuánto recaudaría el Gobierno?

c) El Gobierno también está barajando la posibilidad de utilizar una
   subvención para corregir la externalidad. ¿Cómo debería diseñarse?
   ¿Cuál sería el coste de esta medida?

d) ¿Cuál de las dos medidas, impuesto o subvención, preferirían las
   empresas? ¿Y los compradores del bien?


** Answer

a) La curva de beneficio marginal social, \BMS, coincide con la curva
   inversa de demanda:
   #+begin_export latex
   \[
     \BMS = 360 - 4 Q.
   \]
   #+end_export
   En un mercado competitivo, el coste marginal privado, \CMP, es la
   curva inversa de oferta:
   #+begin_export latex
   \[
     \CMP = 6 Q.
   \]
   #+end_export
   En el equilibrio de mercado $\BMS = \CMP$:
   #+begin_export latex
   \[
     360 - 4 Q_m = 6 Q_m.
   \]
   #+end_export
   De la expresión anterior se obtiene $Q_m = \units{36}$. El precio
   sería $P_m = \price{216}$.
   #+latex: \vspace*{1ex}

   El nivel de producción eficiente se obtiene igualando el beneficio
   marginal social y el coste marginal social: $\BMS = \CMS$. En el
   coste marginal social se incluye el daño marginal que soporta la
   sociedad como consecuencia de la producción del bien: $\CMS =
   \CMP + \DM$. Por tanto:
   #+begin_export latex
   \[
     360 - 4 Q_e = 6 Q_e + 2 Q_e,
   \]
   #+end_export
   y se obtiene $Q_e = \units{30}$. La producción eficiente se
   vendería al precio $P_e = \BMS(Q_e) = \price{240}$.

   #+ATTR_LATEX: :options {0.60\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex4-a-*.pdf
   #+ATTR_LATEX: :options {0.38\linewidth}
   #+xxx: col
   La producción de mercado sería superior a la eficiente y se produce
   una ineficiencia igual al área sombreada.
   #+xxx: endcol

   La ineficiencia generada por la externalidad es:
   #+begin_export latex
   \[
     (Q_m - Q_e) \DM(Q_m) / 2 =
     (36 - 30) \cdot 2 \cdot 36 / 2 =
     \money{216}.
   \]
   #+end_export

b) Para corregir los efectos de la externalidad, se debería introducir
   un impuesto igual al daño marginal correspondiente a la cantidad
   eficiente:
   #+begin_export latex
   \[
     t = \DM(Q_e) = 2 \cdot 30 = \price{60}.
   \]
   #+end_export
   #+ATTR_LATEX: :options {0.60\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex4-b-*.pdf
   #+ATTR_LATEX: :options {0.38\linewidth}
   #+xxx: col
   La introducción del impuesto reduce la producción hasta su nivel
   eficiente. Además de corregir los efectos de la externalidad, la
   recaudación del impuesto genera ingresos adicionales al sector
   público, que pueden servir financiar bienes públicos o para reducir
   otros impuestos.
   #+xxx: endcol
   La recaudación es igual al número de unidades vendidas multiplicado
   por la tasa impositiva:
   #+begin_export latex
   \[
     Q_e t = 30 \cdot 60 = \money{1800}.
   \]
   #+end_export
   El impuesto reduciría el bienestar tanto de los compradores del
   bien como de las empresas. La variación del excedente de los
   consumidores, \VEC, es negativa, ya que se consume una cantidad
   menor y se paga un mayor precio:
   #+begin_export latex
   \[
     \VEC = (P_m - P_e) (Q_e + Q_m) / 2 = \money{-792}
   \]
   #+end_export
   Después de la introducción del impuesto, las empresas venden menos
   e ingresan menos por unidad vendida. La variación del excedente de
   los productores es negativa:
   #+begin_export latex
   \[
     \VEP = (P_e - t - P_m) (Q_e + Q_m) / 2 = \money{-1188}.
   \]
   #+end_export

c) Para contrarrestar los efectos de la externalidad, el gobierno
   puede introducir una subvención a la reducción de la producción:
   por cada unidad que se produzca por debajo de $Q_m$ se pagaría a
   las empresas una cantidad fija de $s$ euros por unidad. Para
   conseguir que la producción se reduzca hasta el nivel eficiente, la
   subvención debe ser igual al daño marginal evaluado en $Q_e$:
   #+begin_export latex
   \[
     s = \DM(Q_e) = \price{60}.
   \]
   #+end_export

   #+ATTR_LATEX: :options {0.60\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex4-c-*.pdf
   #+ATTR_LATEX: :options {0.38\linewidth}
   #+xxx: col
   La subvención crea un incentivo a reducir la producción hasta el
   nivel eficiente, $Q_e$. El coste total de la subvención es igual al
   área del rectángulo resaltado en el gráfico.
   #+xxx: endcol
   El coste total de la subvención es:
   #+begin_export latex
   \[
     (Q_m - Q_e) s = \money{360}.
   \]
   #+end_export
   Además de recibir la subvención, las empresas obtienen más
   beneficios. La menor producción es compensada por un mayor precio
   de venta:
   #+begin_export latex
   \[
     \VEP = (P_e - s - P_m)(Q_m - Q_e)/2 + (P_e - P_m) Q_e =
     -108 + 720 = \money{612}.
   \]
   #+end_export
   Por su parte, los consumidores ven reducido su excedente, ya que
   pagan un precio mayor por una cantidad menor:
   #+begin_export latex
   \[
     \VEC = (P_m - P_e) (Q_e + Q_m) / 2 = \money{-792}.
   \]
   #+end_export

d) Tanto el impuesto como la subvención consiguen eliminar la
   ineficiencia de la externalidad y reducen los costes externos que
   la producción de las empresas impone al resto de la sociedad:
   #+begin_export latex
   \[
      (Q_e - Q_m) \big(\DM(Q_e) + \DM(Q_m)\big) / 2 = \money{-396}.
   \]
   #+end_export
   Sin embargo, las dos medidas tienen efectos distributivos muy
   distintos. El cuadro siguiente muestra como se altera el bienestar
   de los agentes económicos afectados por las dos medidas analizadas.

   #+ATTR_LATEX: :booktabs t :align lrr
   |                         | Con impuesto (€) | Con subvención (€) |
   |-------------------------+------------------+--------------------|
   | Reducción contaminación | $396$            | $396$              |
   | Consumidores            | $-792$           | $-792$             |
   | Empresas                | $-1188$          | $972$              |
   | Contribuyentes          | $1800$           | $-360$             |
   |-------------------------+------------------+--------------------|
   | Total                   | $216$            | $216$              |


   Los consumidores se mostrarían indiferentes entre el impuesto y la
   subvención ya que ambas medidas les suponen una pérdida de
   bienestar idéntica. La introducción del impuesto reduciría los
   beneficios empresariales y las empresas prefieren la subvención:
   sus beneficios aumentarían tanto por la propia subvención como por
   el aumento del excedente de los productores. Por último, los
   contribuyentes preferirían el impuesto a la subvención.

* Q.5

La curva de demanda inversa de un mercado donde opera un monopolista es:
#+begin_export latex
\[
  P = 100 - Q / 30.
\]
#+end_export

El coste marginal del monopolista viene dado por:
#+begin_export latex
\[
  \CMg = 20 + Q / 45.
\]
#+end_export
Como resultado del proceso productivo se vierten residuos
contaminantes a un río cercano. El daño marginal que origina la
polución se ha valorado en $\money{20}$ por unidad producida.

a) ¿Cuál sería el nivel eficiente de producción en este mercado? ¿Qué
   precio debería fijarse?

b) ¿Cuántas unidades produciría el monopolista? ¿Cuánto cobraría por
   cada una de ellas? Calcule la pérdida irrecuperable de eficiencia
   que se produciría en este mercado.

c) Si se interviene para que el mercado funcione como uno competitivo,
   ¿se obtendría una situación eficiente? En caso de que su respuesta
   sea negativa, calcule la ineficiencia en este caso.

d) Compare los resultados obtenidos en los dos apartados
   anteriores. Desde el punto de vista de la eficiencia económica,
   ¿qué tipo de mercado sería preferible en este caso? ¿El monopolista
   o el competitivo?


** Answer

a) La curva inversa de demanda de mercado representa el beneficio
   marginal social:
   #+begin_export latex
   \[
     \BMS = 100 - Q / 30.
   \]
   #+end_export
   El coste marginal social se obtiene sumando el coste marginal
   privado y el daño marginal:
   #+begin_export latex
   \[
     \CMS = 40 + Q / 45.
   \]
   #+end_export

   #+ATTR_LATEX: :options {0.5\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex5-a-*.pdf
   #+ATTR_LATEX: :options {0.49\linewidth}
   #+xxx: col
   La solución eficiente se obtiene igualando \BMS y \CMS:
   #+begin_export latex
   \[
     100 - Q_e / 30 = 40 + Q_e / 45,
   \]
   #+end_export
   lo que implica $Q_e = \units{1080}$. El precio se obtiene a partir
   de la curva de beneficio marginal social:
   #+begin_export latex
   \[
     P_e = \BMS(Q_e) = \price{64}.
   \]
   #+end_export
   #+xxx: endcol

b) El monopolista ignora la externalidad y produce la cantidad que
   iguala el ingreso marginal y el coste marginal privado. El ingreso
   marginal es:
   #+begin_export latex
   \[
     \IMg = 100 - Q / 15.
   \]
   #+end_export

   #+ATTR_LATEX: :options {0.50\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex5-b-*.pdf
   #+ATTR_LATEX: :options {0.49\linewidth}
   #+xxx: col
   La cantidad óptima del monopolio se determina resolviendo:
   #+begin_export latex
   \[
     100 - Q_m / 15 = 20 + Q_m / 45.
   \]
   #+end_export
   De donde $Q_m = \units{900}$. Sustituyendo esta cantidad en la
   curva inversa de demanda, se obtiene el precio del monopolio: $P_m
   = \price{70}$.
   #+xxx: endcol
   #+latex: \vspace*{1ex}

   La producción del monopolio es inferior a la socialmente óptima,
   por lo que se produce una ineficiencia igual al área del triángulo
   sombreado en la figura anterior:
   #+begin_export latex
   \[
      (Q_e - Q_m) \big(P_m - \CMS(Q_m)\big) / 2 = \money{900}.
   \]
   #+end_export
c) Si la empresa fijara el precio competitivo, produciría la cantidad
   que iguala el precio al coste marginal privado:
   #+begin_export latex
   \[
     100 - Q_c / 30 = 20 + Q_c / 45.
   \]
   #+end_export
   La cantidad y el precio competitivos son $Q_c = \units{1440}$ y
   $P_c = \price{52}$.

   #+ATTR_LATEX: :options {0.50\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex5-c-*.pdf
   #+ATTR_LATEX: :options {0.49\linewidth}
   #+xxx: col
   En este caso, la ineficiencia se traduce en una producción superior
   a la óptima. La pérdida de eficiencia es:
   #+begin_export latex
   \[
     (Q_c - Q_e) \DM(Q_c) / 2 = \money{3600}.
   \]
   #+end_export
   #+xxx: endcol

d) Las dos situaciones analizadas en este ejercicio son
   ineficientes. La ineficiencia asociada al monopolio es menor y
   sería preferible al comportamiento competitivo.


* Q.6

El Gobierno quiere mejorar la calidad de las aguas de un río en el que
una empresa vierte 50 toneladas de residuos. El beneficio marginal
social de reducir los vertidos en $R$ toneladas es: $\BMS = 200 - 5
R$, mientras que el coste marginal de reducir los vertidos es: $\CM = 20 +
R$.

a) ¿Cuál es el nivel de reducción óptimo desde el punto de vista
   social?

b) ¿Cuántas toneladas se verterán si se establece una multa de
   $35$ euros por tonelada de residuos? ¿A cuánto asciende la multa
   que pagará la empresa?

c) ¿Qué multa por unidad de polución debería fijarse para
   conseguir el nivel óptimo de polución?


** Answer
a) Los vertidos deberían reducirse mientras el beneficio marginal
   social sea mayor que el coste marginal. El nivel de reducción de
   vertidos óptimo es el que satisface $\BMS = \CM$:
   #+begin_export latex
   \[
     200 - 5 R^* = 20 + R^*,
   \]
   #+end_export
   de donde se obtiene $R^* = 30\,\text{Tm}$.

   #+ATTR_LATEX: :options {0.60\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex6-a-*.pdf
   #+ATTR_LATEX: :options {0.38\linewidth}
   #+xxx: col
   La empresa vertía inicialmente $50$ toneladas de residuos. La
   reducción óptima es de $30$ toneladas, por lo que los vertidos
   óptimos serían de $20$ toneladas de residuos.
   #+xxx: endcol

b) La empresa comparará el coste de reducir sus vertidos en una
   tonelada adicional con la multa que tendría que pagar si no lleva a
   cabo esa reducción. Mientras $\CM \leq f$, a la empresa le resulta
   más barato reducir que pagar la multa. La reducción que llevará a
   cabo satisface: $f = \CM(R_f)$:
   #+begin_export latex
   \[
     35 = 20 + R_{f},
   \]
   #+end_export
   Por tanto, la empresa reducirá sus vertidos en $R_f =
   15\,\text{Tm}$.

   #+ATTR_LATEX: :options {0.60\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex6-b-*.pdf
   #+ATTR_LATEX: :options {0.38\linewidth}
   #+xxx: col
   Después de reducir sus emisiones en $15$ toneladas, la empresa
   vierte $35$ toneladas de residuos y pagará en total una multa de
   #+begin_export latex
   \[
     (50 - R_f) f  = \money{1225}.
   \]
   #+end_export
   #+xxx: endcol

c) La multa que incentiva a las empresas a llevar a cabo la reducción
   óptima de vertidos es: $f^* = \CM(R^*)$. Antes se obtuvo $R^* =
   30\,\text{Tm}$, por lo que:
   #+begin_export latex
   \[
     f^* = 20 + 30 = 50\,\text{\texteuro$/$Tm}.
   \]
   #+end_export

   #+ATTR_LATEX: :options {0.60\linewidth}
   #+xxx: col
   #+latex: \vspace*{1ex}
   #+xxx: fig file:fig-07_1047-ex6-c-*.pdf
   #+ATTR_LATEX: :options {0.38\linewidth}
   #+xxx: col
   La empresa reduciría sus emisiones en $30$ toneladas de residuos y
   pagaría una multa total de \money{1000} por las 20 toneladas que
   vertería al río.
   #+xxx: endcol



* COMMENT Q.1

¿Qué externalidades genera un conductor adicional en una carretera
congestionada? ¿Cómo contribuyen los peajes a paliar esta
externalidad? ¿Qué peaje debería fijarse?


** Answer


* COMMENT Q.1

Identifique la naturaleza de las externalidades en la frase: "El humo
de la fábrica ensuciaba las casas vecinas y era veneno para los
cultivos de la zona".


** Answer

Por hacer.


* COMMENT Q.7

En una pequeña aldea habitan 100 personas que trabajan en una ciudad
situada a 30 km de distancia. Disponen de dos opciones de transporte:

- Tren: el tiempo de viaje total (ida y vuelta) es de $t_T = 40$ minutos
  al día, independientemente de cuantos viajeros opten por este medio
  de transporte.

- Coche privado: sólo hay una carretera antigua de un carril por
  sentido. El tiempo de viaje total (en minutos) con este modo de
  transporte depende del número de conductores que lo usen, $C$:
  #+begin_export latex
  \[
     t_C = 20 + C / 2.
  \]
  #+end_export

El coste monetario del viaje es el mismo en los dos modos de
transporte y los viajeros no perciben diferencias relevantes entre las
dos alternativas, salvo por la duración del viaje. Todos los
trabajadores consideran el tiempo de viaje como una inconveniencia y
cada uno de ellos estaría dispuesto a pagar hasta \money{0.10} por
cada minuto que ahorrasen.

a) ¿Cuál sería el número socialmente óptimo de conductores (para el
   que se minimizaría el tiempo que el conjunto de la sociedad dedica
   a viajar)?

b) Si cada trabajador elige el medio de transporte atendiendo
   únicamente al tiempo que dura su viaje, ¿cuántos utilizarían el
   coche? ¿Coincide su respuesta con la del apartado anterior? ¿por
   qué?

c) Si se establece un peaje para utilizar la carretera, ¿podría
   obtenerse la solución eficiente? ¿Cuál sería el peaje óptimo?


** Answer

Por hacer.


* COMMENT Q.6

El beneficio marginal privado asociado al consumo de un bien es $\BMP
= 30 - Q / 4$ y el coste marginal privado asociado a la producción del
bien es $\CMP = Q / 2$. El daño marginal causado por la producción del
bien es igual a \money{30} por unidad de producto.

a) Calcule la pérdida irrecuperable de eficiencia. Represente
   gráficamente.

b) Para corregir la externalidad el gobierno quiere establecer un
   impuesto de $t$ euros por unidad vendida. ¿Cuál debería ser la
   cuantía del impuesto para alcanzar el óptimo social?

c) Si en vez del impuesto el gobierno utilizara una subvención para
   corregir la ineficiencia, ¿cómo debería diseñarla?

d) Compare los resultados de los dos apartados anteriores. ¿Cuál de
   las dos medidas sería preferible?


** Answer

Por hacer.


* COMMENT Q.10

\DANGER Tanto la empresa $A$ como la $B$ emiten al mes 150 toneladas
de sustancias contaminantes. El Gobierno quiere intervenir para
reducir los niveles de contaminación. Los costes marginales de
reducción de una tonelada de emisiones son $\CM_A = 3 R_A$ para la
empresa $A$ y $\CM_B = 6 R_B$ para la empresa $B$, donde $R_A$ y $R_B$
son las cantidades en que reduce la contaminación cada empresa. El
beneficio marginal social debido a la reducción de la polución es
$\BMS = 600 - 3 R_T$ donde $R_T = R_A + R_B$.

a) ¿Cuál es el nivel eficiente de reducción de las emisiones? ¿Y el
   nivel socialmente óptimo de emisiones?

b) Si se establece un sistema de permisos /no/ transferibles y se
   reparte la mitad a cada empresa, ¿cuantos deben repartirse a cada
   empresa para obtener el nivel de emisiones eficiente? ¿Es posible
   encontrar repartos de los permisos que permitan alcanzar el óptimo
   social de una forma menos costosa?

c) Si se reparten a partes iguales los permisos correspondientes al
   óptimo social y se permite la compra y la venta de estos permisos,
   ¿en cuántas toneladas reduciría cada empresa sus emisiones?

d) ¿Puede alcanzarse el óptimo social mediante un impuesto a la
   polución?


** Answer

Por hacer.


* COMMENT Q.1

El gobierno del Reino Unido anunció en 1997 que, por primera vez, los
estudiantes universitarios deberían pagar una parte del coste de sus
estudios superiores. Un portavoz de los estudiantes declaró:
"Consideramos la gratuidad de la matricula como un derecho [...]
Siempre se nos ha dicho que si eliges continuar con tus estudios, el
Estado debe pagar porque devolverás mucho al Estado consiguiendo un
mejor trabajo y pagando más impuestos". Comente.


** Answer

Por hacer.

# Local Variables:
# ispell-dictionary: "spanish"
# End:

#  LocalWords:  COMMENT Answer Groucho Harpo Coase
