# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit07}}}: ejercicios


* Q.1

Identifique la naturaleza de las externalidades en la frase: "El humo
de la fábrica ensuciaba las casas vecinas y era veneno para los
cultivos de la zona".


** Answer

Por hacer.


* Q.2

Identifique cuáles de las siguientes afirmaciones son verdaderas,
falsas o inciertas, y explique por qué.

a) Si tu consumo de tabaco produce externalidades negativas a tus
   compañeros de piso (las cuáles ignoras por completo), entonces
   estás fumando más de los que sería eficiente.

b) Un impuesto sobre el tabaco hace que el mercado de cigarrillos funcione más eficientemente.

c) La prohibición del tabaco puede justificarse por razones de eficiencia.

d) La producción en un mercado competitivo con una externalidad
   negativa (sea del tipo que sea) es mayor que la producción
   socialmente óptima.


** Answer

Por hacer.


* Q.3

En un pueblo pesquero las capturas mensuales totales de pescado, $Q$
(medidas en kg), dependen del número de barcas que faenan, $N$:
#+begin_export latex
\begin{equation*}
  Q = \num{1000} N^{1/2}.
\end{equation*}
#+end_export
Todas las barcas son idénticas y capturan la misma cantidad de pescado:
#+begin_export latex
\begin{equation*}
  q_i = Q / N.
\end{equation*}
#+end_export
Los costes mensuales de operar cada barca son de $c_i = \money{1000}$
al mes. El pescado se vende en un mercado competitivo a un precio de
$P = \price[kg]{6}$.  Inicialmente no hay ningún tipo de limitación al
número de barcas que operan en el pueblo.

a) Suponga que operan $16$ barcas. ¿Qué beneficios obtiene cada
   barca?

b) Si una barca más empieza a pescar, calcule el efecto externo que
   tienen que soportar los pescadores que ya estaban operando.

c) Calcule el número de barcas de equilibrio.

d) Calcule el número de barcas socialmente óptimo.

e) El ayuntamiento está considerando la posibilidad de introducir un
   sistema de licencias. ¿Qué precio debería fijar para cada licencia
   si quiere conseguir que opere el número socialmente óptimo de
   barcas?


** Answer

Por hacer.


* Q.4

Groucho y Harpo comparten camarote en un crucero. A Groucho le encanta
fumar sus puros durante la travesía. Harpo detesta los puros de
Groucho. La utilidad de los dos viajeros viene dada por las funciones:
#+begin_export latex
\begin{gather*}
U_G = 100 - 4 c - 0.1 c^2,
\intertext{y}
U_H = 100 - 10 c,
\end{gather*}
#+end_export
donde $c$ es el número de puros que fuma Groucho durante la travesía,
y $U_G$ y $U_H$ son las utilidades (medidas en euros) de Groucho y de
Harpo, respectivamente.

a) Si Groucho ignora las enérgicas protestas de su compañero de
   camarote y fuma todo lo que le apetece, ¿cuál será el valor de $c$?
   ¿Qué valores toman $U_G$ y $U_H$ en este caso?

b) ¿Es eficiente la solución anterior? Calcule el valor de $c$ que
   maximiza la función de bienestar $W = U_G + U_H$? ¿Qué valores
   toman $U_G$ y $U_H$ en este caso?

c) Chico, el capitán del barco, es un gran admirador de los trabajos
   de Coase y decide asignar a Groucho la capacidad de prohibir o no
   que se fume en el camarote. Si se establece una negociación entre
   Groucho y Harpo, ¿cuál sería el acuerdo que se alcanzaría?

c) Describa cómo cambiaría su respuesta al apartado anterior si Chico
   hubiese asignado a Harpo la capacidad de prohibir fumar en el
   camarote.


** Answer

Por hacer.


* Q.5

La demanda de un producto es $Q = \num{1200} - 4 P$ y la oferta es $Q
= 2 P$. Al producir el bien se vierten sustancias contaminantes que
generan un daño a la sociedad valorado en \money{30} por unidad de
producto.

a) Obtenga y represente el equilibrio en este mercado en ausencia
   de cualquier tipo de intervención. Calcule la pérdida
   irrecuperable de eficiencia.

b) Para corregir la externalidad, el Gobierno quiere introducir un
   impuesto de $t$ euros por unidad producida. ¿Qué valor debe tomar
   $t$ para conseguir el nivel de producción socialmente óptimo?
   ¿Cuanto recaudaría el Gobierno?

c) El Gobierno también está barajando la posibilidad de utilizar una
   subvención para corregir la externalidad. ¿Cómo debería diseñarse?
   ¿Cuál sería el coste de esta medida?

d) ¿Cuál de las dos medidas, impuesto o subvención, preferirían las
   empresas? ¿Y los compradores del bien?


** Answer

Por hacer.


* Q.6

El beneficio marginal privado asociado al consumo de un bien es
$\BMP = 360 - 4 Q$ y el coste marginal privado asociado a la
producción del bien es $\CMP = 6 Q$. El daño marginal causado por la
producción del bien es $\DM = 2 Q$.

a) Calcule la pérdida irrecuperable de eficiencia. Represente
   gráficamente.

b) Para corregir la externalidad el gobierno quiere establecer un
   impuesto de $T$ euros por unidad vendida. ¿Cuál debería ser la
   cuantía del impuesto para alcanzar el óptimo social?

c) Si en vez del impuesto el gobierno utilizara una subvención para
   corregir la ineficiencia, ¿cómo debería diseñarla?

d) Compare los resultados de los dos apartados anteriores. ¿Cuál de
   las dos medidas sería preferible?


** Answer

Por hacer.


* Q.7

En una pequeña aldea habitan 100 personas que trabajan en una ciudad
situada a 30 km de distancia. Disponen de dos opciones de transporte:

- Tren: el tiempo de viaje total (ida y vuelta) es de $t_T = 40$ minutos
  al día, independientemente de cuantos viajeros opten por este medio
  de transporte.

- Coche privado: sólo hay una carretera antigua de un carril por
  sentido. El tiempo de viaje total (en minutos) con este modo de
  transporte depende del número de conductores que lo usen, $C$:
  #+begin_export latex
  \[
     t_C = 20 + C / 2.
  \]
  #+end_export

El coste monetario del viaje es el mismo en los dos modos de
transporte y los viajeros no perciben diferencias relevantes entre las
dos alternativas, salvo por la duración del viaje. Todos los
trabajadores consideran el tiempo de viaje como una inconveniencia y
cada uno de ellos estaría dispuesto a pagar hasta \money{0.10} por
cada minuto que ahorrasen.

a) ¿Cuál sería el número socialmente óptimo de conductores (para el
   que se minimizaría el tiempo que el conjunto de la sociedad dedica
   a viajar)?

b) Si cada trabajador elige el medio de transporte atendiendo
   únicamente al tiempo que dura su viaje, ¿cuántos utilizarían el
   coche? ¿Coincide su respuesta con la del apartado anterior? ¿por
   qué?

c) Si se establece un peaje para utilizar la carretera, ¿podría
   obtenerse la solución eficiente? ¿Cuál sería el peaje óptimo?


** Answer

Por hacer.


* Q.8

La curva de demanda inversa de un mercado donde opera un monopolista es:
#+begin_export latex
\[
  P = 100 - Q / 30.
\]
#+end_export

El coste marginal del monopolista viene dado por:
#+begin_export latex
\[
  \CMg = 20 + Q / 45.
\]
#+end_export
Como resultado del proceso productivo se vierten residuos
contaminantes a un río cercano. El daño marginal que origina la
polución se ha valorado en $\money{20}$ por unidad producida.

a) ¿Cuál sería el nivel eficiente de producción en este mercado? ¿Qué
   precio debería fijarse?

b) ¿Cuántas unidades produciría el monopolista? ¿Cuánto cobraría por
   cada una de ellas? Calcule la pérdida irrecuperable de eficiencia
   que se produciría en este mercado.

c) Si se interviene para que el mercado funcione como uno competitivo,
   ¿se obtendría una situación eficiente? En caso de que su respuesta
   sea negativa, calcule la ineficiencia en este caso.

d) Compare los resultados obtenidos en los dos apartados
   anteriores. Desde el punto de vista de la eficiencia económica,
   ¿qué tipo de mercado sería preferible en este caso? ¿El monopolista
   o el competitivo?


** Answer

Por hacer.


* Q.9

El Gobierno quiere mejorar la calidad de las aguas de un río en el que
una empresa vierte 50 toneladas de residuos. El beneficio marginal
social de reducir los vertidos en $R$ toneladas es: $\BMS = 200 - 5
R$.  El coste marginal de reducir los vertidos es: $\CM = 20 +
R$. ¿Cuál es el nivel de reducción óptimo desde el punto de vista
social? ¿Qué multa por unidad de polución debería fijarse para
conseguir el nivel óptimo de polución?


** Answer

Por hacer.


* Q.10

\DANGER Tanto la empresa $A$ como la $B$ emiten al mes 150 toneladas
de sustancias contaminantes. El Gobierno quiere intervenir para
reducir los niveles de contaminación. Los costes marginales de
reducción de una tonelada de emisiones son $\CM_A = 3 R_A$ para la
empresa $A$ y $\CM_B = 6 R_B$ para la empresa $B$, donde $R_A$ y $R_B$
son las cantidades en que reduce la contaminación cada empresa. El
beneficio marginal social debido a la reducción de la polución es
$\BMS = 600 - 3 R_T$ donde $R_T = R_A + R_B$.

a) ¿Cuál es el nivel eficiente de reducción de las emisiones? ¿Y el
   nivel socialmente óptimo de emisiones?

b) Si se establece un sistema de permisos /no/ transferibles y se
   reparte la mitad a cada empresa, ¿cuantos deben repartirse a cada
   empresa para obtener el nivel de emisiones eficiente? ¿Es posible
   encontrar repartos de los permisos que permitan alcanzar el óptimo
   social de una forma menos costosa?

c) Si se reparten a partes iguales los permisos correspondientes al
   óptimo social y se permite la compra y la venta de estos permisos,
   ¿en cuántas toneladas reduciría cada empresa sus emisiones?

d) ¿Puede alcanzarse el óptimo social mediante un impuesto a la
   polución?


** Answer

Por hacer.


* COMMENT Q.1

El gobierno del Reino Unido anunció en 1997 que, por primera vez, los
estudiantes universitarios deberían pagar una parte del coste de sus
estudios superiores. Un portavoz de los estudiantes declaró:
"Consideramos la gratuidad de la matricula como un derecho [...]
Siempre se nos ha dicho que si eliges continuar con tus estudios, el
Estado debe pagar porque devolverás mucho al Estado consiguiendo un
mejor trabajo y pagando más impuestos". Comente.


** Answer

Por hacer.
