# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Externalidades: ejercicios

1. El gobierno del Reino Unido anunció en 1997 que, por primera vez,
   los estudiantes universitarios deberían pagar una parte del coste
   de sus estudios superiores. Un portavoz de los estudiantes declaró:
   "Consideramos la gratuidad de la matricula como un derecho
   ... Siempre se nos ha dicho que si eliges continuar con tus
   estudios, el Estado debe pagar porque devolverás mucho al Estado
   consiguiendo un mejor trabajo y pagando más impuestos". Comente.

2. En un pueblo pesquero las capturas mensuales totales de pescado,
   $Q$ (medidas en kg), dependen del número de barcas que faenan, $N$:
   \begin{equation*}
     Q = \num{1000} N^{1/2}.
   \end{equation*}
   Todas las barcas son idénticas y capturan la misma cantidad de pescado:
   \begin{equation*}
     q_i = Q / N.
   \end{equation*}
   Los costes mensuales de operar cada barca son de $c_i =
   \money{1000}$ al mes. El pescado se vende en un mercado competitivo
   a un precio de $P = \price[kg]{6}$.  Inicialmente no hay ningún
   tipo de limitación al número de barcas que operan en el pueblo.

   a) Suponga que operan $16$ barcas. ¿Qué beneficios obtiene cada
      barca?

   b) Si una barca más empieza a pescar, calcule el efecto externo
      que tienen que soportar los pescadores que ya estaban operando.

   c) Calcule el número de barcas de equilibrio.

   d) Calcule el número de barcas socialmente óptimo.

   e) El ayuntamiento está considerando la posibilidad de introducir
      un sistema de licencias. ¿Qué precio debería fijar para cada
      licencia si quiere conseguir que opere el número socialmente
      óptimo de barcas?

3. El beneficio marginal privado asociado al consumo de un producto es
   $\BMP = 360 - 4 Q$ y el coste marginal privado de producción es
   $\CMP = 6 Q$. Existe un daño marginal asociado a la producción que
   expresamos como $\DM = 2Q$. No existe daño marginal asociado al
   consumo del bien.

   a) Obtenga y represente el equilibrio en este mercado. Calcule la
      pérdida irrecuperable de eficiencia.

   b) El gobierno quiere introducir un impuesto sobre la producción
      para corregir la externalidad. ¿Cuál debería ser el valor del
      impuesto por unidad producida? ¿Y la recaudación total?

   c) El gobierno también se está planteado utilizar una subvención
      para corregir la externalidad. ¿Cómo debería diseñarse? ¿Cuál
      sería el coste de esta medida?

4. El daño marginal que puede ser evitado reduciendo la polución
   generada por una empresa es $\DM = 200 - 5 Q$. El coste marginal de
   la reducción de la polución es $\CM = 10 + Q$.

   a) ¿Cuál es el nivel de reducción óptimo desde el punto de vista
      social?

   b) ¿Qué multa por unidad de polución debería fijarse para conseguir
      el nivel óptimo de polución?

   c) ¿Cómo podría alcanzarse el nivel óptimo de polución mediante una
      subvención?

5. \DANGER Las empresas $A$ y $B$ producen cada una 80 unidades de
   polución. El gobierno quiere intervenir para reducir los niveles de
   contaminación. Los costes marginales de reducción de la polución
   son $\CM_A = 50 + 3 Q_A$ para la empresa $A$ y $\CM_B = 20 + 6 Q_B$
   para la empresa $B$, donde $Q_A$ y $Q_B$ son las cantidades de
   reducción de la contaminación de cada empresa. El beneficio
   marginal social debido a la reducción de la polución es $\BMS =
   590 - 3 Q_T$ donde $Q_T$ es las reducción de la polución total.

   a) ¿Cuál es el nivel de polución total socialmente óptimo?

   b) Si se establece un sistema de permisos no transferibles y se
      reparte la mitad a cada empresa, ¿se obtiene el nivel de
      polución eficiente?

   c) ¿Qué ventajas tiene el que se pueden transferir los permisos?
      Si se reparten a partes iguales los permisos correspondientes al
      óptimo social y se establece un mercado de permisos,
      calcule cuánto reduciría la polución cada empresa.

   d) ¿Puede alcanzarse el óptimo social mediante un impuesto a la polución?
