#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit12}}}: ejercicios

* Q.1

Adam solo consume los bienes $X$ e $Y$. Elige la cesta $E_0$ cuando
los precios son $P_X = \price{5}$ y $P_Y = \price{6}$. Sin embargo, la
elección óptima de Adam es $E_1$ después de que se establezca un
impuesto sobre las compras del bien $X$ de \money{5} por unidad que se
traslada por completo a los compradores. El gráfico siguiente muestra
las elecciones de Adam, las rectas presupuestarias antes y después del
impuesto y las curvas de indiferencia de $E_0$ y $E_1$.

#+xxx: fig file:fig-12_1047-01-*.pdf

a) ¿Cuánto paga Adam por el impuesto sobre las compras de $X$?
b) Determine a cuánto ascendería un impuesto de cuantía fija
   equivalente al impuesto sobre las compras de $X$, en el sentido de
   que ambos dejarían a Adam con la misma utilidad.
c) ¿Cuál es el exceso de gravamen que soporta Adam?


** Answer


* Q.2

El gobierno trata de reducir el consumo de sal y para ello establece
un impuesto específico de $t$ euros por cada kg de sal. El impuesto se
traslada por completo a los compradores. Dulce no ha modificado en
absoluto su consumo de sal después de la introducción del
impuesto. ¿Quiere esto decir que no hay un exceso de gravamen en el
caso de Dulce? ¿Por qué? Represente gráficamente.


** Answer

Por hacer.


* Q.3

Un producto se vende en un mercado competitivo cuyas curvas de
demanda y oferta son:
#+begin_export latex
\begin{gather*}
  Q^d = 150 - 100 P / 3, \\
  Q^o = 25 + 50 P.
\end{gather*}
#+end_export
Determine el exceso de gravamen de un impuesto de \money{0.50} por
unidad vendida.


** Answer

Por hacer.


* Q.4

La demanda de mercado de un producto viene dada por $P = 20 - 0.001
Q$. La curva de oferta de mercado es perfectamente elástica: $P =
\price{10}$. Suponiendo que los efectos renta son despreciables:

a) Calcule el exceso de gravamen si se establece un impuesto de
   \money{2} por unidad producida.

b) Calcule el exceso de gravamen si el impuesto fuera de \money{3}
   por unidad producida.

c) Compare los resultados obtenidos en los apartados anterior. ¿Cómo
   cambia la ineficiencia generada por el impuesto cuando cambia la
   tasa impositiva?


** Answer

Por hacer.


* Q.5

En el mercado de un bien la curva de demanda es: $P = 10 - 0.01 Q$. El
bien es producido por un monopolista y los costes marginales son
constantes: $\CM = \price{2}$.

a) ¿Cuál sería el exceso de gravamen de un impuesto de \money{2}
   por unidad producida?

b) ¿Cómo cambiaría su respuesta al apartado anterior si el productor
   actuara como una empresa competitiva? Compare la ineficiencia
   provocada por el impuesto en un mercado competitivo y en un
   monopolio.


** Answer

Por hacer.


* Q.6

El mercado de gasoil de un pequeño país es competitivo. Las curvas de
demanda y oferta son:
#+begin_export latex
\begin{gather*}
  Q^{d} = \num{5000} - \num{3000} P, \\
  Q^{o} = \num{-1300} + \num{1500} P.
\end{gather*}
#+end_export
El gobierno piensa que los precios del gasoil son muy elevados y
establece una subvención a los compradores de \price[litre]{0.20}.

a) Calcule la ineficiencia asociada a la subvención.

b) ¿Cómo cambiaría su respuesta al apartado anterior si el consumo de
   gasoil produjera una externalidad negativa igual a
   \price[litre]{0.40}? Represente gráficamente.


** Answer


* Q.7

Las autoridades locales de una comarca están estudiando introducir un
impuesto a los arrendatarios de tierra para usos agrícolas de
\price[hectare]{4} al año.  La oferta de tierra en la comarca es fija:
$Q^o = \SI{314000}{\hectare}$. La demanda de tierra viene dada por la
ecuación:
#+begin_export latex
\[
  Q^{d} = \num{400000} - \num{1000} P.
\]
#+end_export
donde $P$ es el alquiler anual de una hectárea.

a) ¿Cuál es el alquiler de equilibrio si no se introduce el impuesto?

b) Si se introduce el impuesto, ¿cuál será el pago total por hectárea
   de los arrendatarios? ¿Cuál será el alquiler que cobran los
   arrendadores? ¿Cuál será la recaudación total del impuesto?

c) ¿Cuál es el exceso de gravamen?


** Answer

Por hacer.



# Local Variables:
# ispell-local-dictionary: "spanish"
# End:
