#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit03}}}: ejercicios



* Q.1

Indique si cada una de las siguientes afirmaciones es cierta, falsa
o imprecisa y justifique su respuesta:

a) Si todo el mundo tiene la misma relación marginal de
   sustitución, entonces la asignación de recursos es eficiente en
   el sentido de Pareto.

b) Si la asignación de recursos es Pareto eficiente todo el mundo
   tiene la misma relación marginal de sustitución.

c) Una reasignación que lleve a la economía de un punto a otro de la
   frontera de posibilidades de utilidad es una mejora de Pareto.

d) El Segundo Teorema Fundamental de la Economía del Bienestar dice
   que la asignación de recursos competitiva es socialmente deseable.

** Answer


a) *Falsa* (salvo en una economía de intercambio puro). La igualdad de
   las relaciones marginales de sustitución es condición necesaria,
   pero no suficiente para la eficiencia de Pareto. Se cumpliría la
   condición de eficiencia en el intercambio, pero no necesariamente
   se cumplirían las otras condiciones de eficiencia (en la producción
   y en la combinación de productos).

b) *Verdadera* (en ausencia de bienes públicos). Una asignación Pareto
   eficiente implica la eficiencia en el intercambio, por lo que se
   observaría la igualdad de las RMS de todos los individuos.

c) *Falsa*. Todos los puntos de la frontera son eficientes en el
   sentido de Pareto. Cualquier reasignación partiendo de un punto
   eficiente implicaría que, al menos, un individuo empeoraría.

d) *Falsa*. El teorema establece que toda asignación eficiente puede
   obtenerse como equilibrio competitivo tras una determinada
   redistribución, pero no afirma que esas asignaciones sean o no
   deseables.


* Q.2

En una economía de intercambio puro:

a) ¿Es posible que exista una asignación Pareto eficiente donde
   alguien esté peor que en otra asignación que no es
   Pareto eficiente?

b) ¿Es posible que exista una asignación Pareto eficiente donde
   todos los individuos estén peor que en otra asignación que no es
   Pareto eficiente?

c) ¿Es posible conseguir que algún individuo mejore si la economía
   se encuentra en un óptimo de Pareto?

** Answer

#+xxx: fig file:fig-03_1047-02b-*.pdf

a) *Sí*. Que una asignación sea Pareto eficiente no significa que el
   bienestar de todos los individuos sea mayor que en cualquier otra
   asignación, sea eficiente o no.

   Por ejemplo, la asignación $U$ del gráfico es eficiente ya que está
   sobre la curva de contrato. En ese punto el consumidor $A$ obtiene
   una menor utilidad que en la asignación no eficiente $Q$. En
   cambio, en la asignación eficiente $V$ es el consumidor $B$ el que
   empeora con respecto de la asignación $Q$.

b) *No*. Si fuera verdad, tendríamos una asignación eficiente desde la
   cual se podría obtener una mejora de Pareto en la que todos los
   individuos mejorasen simultáneamente. Pero eso entra en
   contradicción con que la asignación inicial sea eficiente.

   En el gráfico, se puede comparar la utilidad que obtienen los
   consumidores en la asignación $Q$ (no eficiente) y en los puntos de
   la curva de contrato (asignaciones eficientes). En el tramo $S T$
   ningún consumidor está peor que en $Q$. En las asignaciones en el
   tramo $O_A S$ el consumidor $A$ está peor que en $Q$, pero $B$ está
   mejor. Por último, en el tramo $T O_B$ solo empeora el consumidor
   $B$. En ninguna asignación eficiente los dos consumidores están
   peor que en $Q$.

c) *Sí*. Lo que no es posible es conseguir que todos los individuos
   mejoren. Si la economía está en un óptimo de Pareto, cualquier
   reasignación que mejore el bienestar de un individuo, hará que, al
   menos, otro individuo empeore.

   En el gráfico, el consumidor $A$ mejora si pasamos de la asignación
   eficiente $U$ a la asignación $S$ o a la asignación $Q$.

* Q.3

Considere una economía de intercambio puro compuesta por dos personas,
Arturo y Belén, que consumen dos bienes, pan y agua. Debido a la
pertinaz sequía, las autoridades deciden reasignar las dotaciones de
agua de manera que cada persona disponga exactamente de la mitad del
agua total disponible. Además, se prohíbe intercambiar pan por agua
con el objetivo de evitar posibles situaciones de
"explotación". ¿Puede una redistribución de ese tipo constituir una
mejora en sentido de Pareto?  ¿Es posible que la asignación resultante
sea Pareto eficiente?

** Answer


#+xxx: fig file:fig-03_1047-03a-*.pdf

- /¿Puede ser una mejora de Pareto?/ No: un individuo tendrá la misma
  cantidad de pan pero menos cantidad de agua, por lo que su utilidad
  se reducirá.

  Por ejemplo, si la asignación inicial es $Q$, después de reasignar
  el agua la economía se movería al punto $S$. Dado que el consumidor
  $B$ tendría menos agua en la nueva situación, su utilidad
  disminuiría.

- /¿Puede ser Pareto eficiente?/ No necesariamente. Sólo hay una
  asignación donde el agua se reparte al 50% y está sobre la curva de
  contrato (la asignación $T$ del gráfico). Dado que se prohíbe el
  intercambio, alcanzar esa situación solo podría ocurrir por
  casualidad.


* Q.4

En una economía de mercado que opera eficientemente se producen
\num{1000000} de unidades del bien $X$ y \num{500000} unidades del
bien $Y$. Los precios a los que se venden estos bienes son $P_X =
\price{10}$ y $P_Y = \price{2}$. Determine cuántas unidades
adicionales del bien $Y$ podrían producirse si se dejara de producir
una unidad del bien $X$.

** Answer


Si se cumplen las condiciones de eficiencia, la relación marginal de
transformación, \RMT, será igual a los precios relativos:
#+begin_export latex
\[
  \RMT = \frac{P_X}{P_Y} = \frac{10}{2} =
  5\text{\, unidades de $Y$ por unidad de $X$.}
\]
#+end_export
Si se produce $1$ unidad menos del bien $X$ se podrían producir $5$
unidades adicionales del bien $Y$.




* Q.5

Una economía está compuesta por dos consumidores, Alicia y Bruno, y
dos bienes de consumo: café y donuts. Tanto Alicia como Bruno están
dispuestos a intercambiar dos tazas de café por un donut. Por otro
lado, si se produjera una taza de café menos se liberarían suficientes
factores como para producir tres donuts. ¿Se cumplen las condiciones
de eficiencia en esta economía? Si la respuesta es negativa, ¿habría
que producir más café o más donuts?

** Answer

Las relaciones marginales de Alicia y Bruno coinciden:
#+begin_export latex
\[
  \RMS_A = \RMS_B = 2\text{\,tazas de café por donut.}
\]
#+end_export
La relación marginal de transformación es:
#+begin_export latex
\[
  \RMT = 1/3\text{\,tazas de café por donut.}
\]
#+end_export
Aunque se cumple la condición de eficiencia en el intercambio, no se
cumple la condición de eficiencia en la combinación de productos:
#+begin_export latex
\[
  \RMS_{A} = \RMS_{B} \neq \RMT.
\]
#+end_export


La \RMT es la pendiente con el signo cambiado de la frontera de
posibilidades de producción:
#+begin_export latex
\[
  \RMT \approx - \iratio{C}{D} = \frac{1}{3}.
\]
#+end_export
donde $C$ es la producción de café y $D$ la producción de donuts. Por
tanto, si nos movemos a lo largo de la frontera, se cumplirá
aproximadamente que:
#+begin_export latex
\[
  \Delta D \approx - 3 \Delta C.
\]
#+end_export

Para determinar cómo habría que alterar la producción, consideremos
que se producen 2 tazas de café menos. De acuerdo con la expresión
anterior, sería posible producir 6 donuts más. Si repartimos esas
variaciones de producción a partes iguales entre los dos consumidores,
cada uno de ellos consumiría 3 donuts más y 1 taza de café menos. De
acuerdo con las \RMS, a cambio de 3 donuts adicionales los
consumidores estarían dispuestos a renunciar hasta a 6 tazas de
café. Dado que sólo han perdido 1 taza de café, el bienestar de los
dos consumidores aumentaría. En conclusión, debería producirse menos
café y más donuts.



* COMMENT Q.6

El gobierno de un país quiere fomentar la producción de aceite de
oliva. Para ello establece un impuesto adicional a los consumidores
sobre la compra de aceites de semillas. ¿Es esta medida compatible
con una asignación de recursos eficiente en el sentido de Pareto?

** Answer

Por hacer


* COMMENT Q.10

En un mercado con curva inversa de demanda $P = 14 - 0.04 Q$ opera
un monopolista cuyos costes marginales son $\CM = 2 + 0.02 Q$. Las
autoridades económicas están considerando regular las actividades
del monopolio.

a) Calcule la ineficiencia del monopolio.

b) Si se obliga al monopolista a fijar el precio competitivo, ¿cuál
   sería el aumento del bienestar de los consumidores?

** Answer

Por hacer


* COMMENT Q.15

\DDANGER Considere una economía pura de intercambio con dos
consumidores $A$ y $B$ y dos bienes $X$ e $Y$. Las preferencias vienen
dadas por:
#+begin_export latex
\begin{gather*}
  U_{A}(X_{A}, Y_{A}) = X_{A}^{1/4} Y_{A}^{1/4} \\
  U_{B}(X_{B}, Y_{B}) = X_{B}^{1/4} Y_{B}^{1/4}
\end{gather*}
#+end_export
Las dotaciones iniciales de los consumidores son:
#+begin_export latex
\begin{gather*}
  \Xbar_{A} = 20; \quad \Ybar_{A} = 60. \\
  \Xbar_{B} = 80; \quad \Ybar_{B} = 40.
\end{gather*}
#+end_export

a) ¿Es la dotación inicial Pareto eficiente?

b) Calcule la curva de contrato.

c) Considere ahora que se instituyen mercados competitivos para
   asignar los bienes de consumo. ¿Se alcanza el equilibrio
   competitivo si los precios son $P_X = 2$ y $P_Y = 1$? Si su
   respuesta es negativa, calcule los precios del equilibrio
   competitivo. ¿Es eficiente la asignación de mercado?


* COMMENT Q.7

Imagine una economía donde sólo habitan dos consumidores, Aurora y Bernardo.

a) Si la función de bienestar social es:
   #+begin_export latex
   \[ W_1 = U_A + U_B \]
   #+end_export
   donde $U_A$ y $U_B$ son las utilidades de Aurora y Bernardo,
   respectivamente. Dibuje las curvas de indiferencia social. ¿Cómo
   describiría la importancia relativa que se asigna a cada
   utilidad?

b) ¿Cómo cambiaría su respuesta al apartado anterior si la función
   de bienestar social fuera $W_2 = U_A + 2 U_B$?

c) ¿Y si fuera $W_3 = \min\{U_A, U_B\}$?

d) Suponga que la función de posibilidades de utilidad es:
   #+xxx: fig file:fig-Efficiency-Equity_1047-01-*.pdf
   Muestre gráficamente como difieren las soluciones óptimas para
   las funciones de bienestar social de los apartados anteriores.

** Answer

Por hacer


* COMMENT Q.8

Un programa público elevaría ligeramente el bienestar de los
ciudadanos más pobres pero disminuye considerablemente el bienestar
de los demás individuos. ¿Debería llevarse a cabo este programa si
se adopta el criterio utilitarista? ¿Y si se utiliza el criterio
/rawlsiano/?

** Answer

Por hacer


* COMMENT Q.9

En un país sólo viven dos ciudadanos: Blanca y Teo. Blanca es
abogada y gana \money{50} por hora. Cuando la tasa impositiva sobre
la renta es $t = \SI{0}{\percent}$, Blanca trabaja 20 horas a la
semana; si $t = \SI{25}{\percent}$, trabajaría 16 horas; y si $t =
\SI{40}{\percent}$ sólo trabajaría 8 horas. Teo trabaja en un
pequeño taller de reparaciones y gana \money{6} por hora. Teo
siempre trabaja 20 horas por semana sea cual sea la tasa
impositiva. El gobierno está pensando en gravar la renta de Blanca
y transferir la recaudación a Teo.

a) Blanca y Teo tienen la misma función de utilidad: $U(Y) =
   Y^{1/2}$ donde $Y$ es la renta después de impuestos y
   transferencias. ¿Cuál de las tres tasas impositivas sería óptima
   desde un punto de vista utilitarista? ¿Y si se utiliza una
   función de bienestar social /rawlsiana/?

b) ¿Cambiarían las conclusiones del apartado anterior si la función
   de utilidad fuera $U(Y) = Y^{1/5}$?.

c) Suponga ahora que Blanca y Teo tienen funciones de utilidad
   diferentes. La utilidad de Blanca es $U_B(Y) = 0.25 Y^{1/2}$ y
   la de Teo es $U_T(Y) = Y^{1/2}$. Esto se debe a que Blanca sufre
   una discapacidad por lo que necesita más renta para alcanzar el
   mismo nivel de utilidad. ¿Cómo ordenarían ahora las diferentes
   alternativas los criterios utilitarista y /rawlsiano/?

** Answer

Por hacer


* COMMENT Q.11

¿Es posible encontrar una situación en la que que el óptimo social de
acuerdo a una función de bienestar /rawlsiana/ coincida con el que se
obtendría con una función de bienestar utilitarista?  Represente
gráficamente.


* COMMENT Q.12

Considere una economía con dos individuos $A$ y $B$. La tabla
siguiente muestra algunas combinaciones de utilidad que se
encuentran sobre la frontera de posibilidades de utilidad:

#+begin_export latex
\begin{center}
  \begin{tabular}{>{$}l<{$}*{2}{>{$}r<{$}}}
    \toprule
    \text{Opción} & U_A & U_B \\
    \midrule
    M & 100 &  0 \\
    N &  90 & 20 \\
    O &  60 & 30 \\
    P &  30 & 30 \\
    Q &  40 & 60 \\
    R &  10 & 70 \\
  \bottomrule
\end{tabular}
\end{center}
#+end_export

Indique cuál será la opción elegida de acuerdo con:

a) el criterio utilitarista.

b) el criterio igualitarista.

c) el criterio /rawlsiano/.


* COMMENT Q.13

6. Analice la veracidad o falsedad de las siguientes afirmaciones:

   a) La aplicación del criterio /rawlsiano/ conduce necesariamente a
      una distribución igualitaria de la renta.

   b) Dada una curva de posibilidades de utilidad para dos individuos,
      la aplicación del criterio utilitarista llevará siempre a una
      distribución menos igualitaria que la del criterio /rawlsiano/.


* COMMENT Q.14

\DANGER Una economía está compuesta por dos individuos: $A$ y
$B$. $A$ dispone de un factor de producción que puede usar para
producir un bien de consumo $X$. $B$ no posee ninguna unidad del
factor de producción y, por tanto, no puede producir nada. Para
paliar esta situación el gobierno puede transferir a $B$ una
fracción $t$ de la producción de $A$. La producción de $A$ depende
de $t$ mediante la siguiente función:
#+begin_export latex
\[
  X(t) = 167 (1 - t) (t + 0.6)
\]
#+end_export
Suponiendo que la utilidad de ambos individuos es igual a la
cantidad que consumen del bien $X$, determinar qué fracción debería
$t$ debería establecerse de acuerdo a un criterio:

a) utilitarista.

b) /rawlsiano/.

c) igualitarista.


# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  donuts donut
