# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit02}}} (I)



* Q.1

Responda a las siguientes preguntas utilizando los datos del /Resumen
del Informe COFOG 2018-2022/, el cual se encuentra disponible en [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iacogof.aspx][la
web del IGAE]]:

a) ¿Qué porcentaje sobre el PIB representa el total del gasto público?
b) ¿Cuáles son los principales grupos de gasto público en España?
c) ¿Cómo se reparte el gasto entre los diferentes administraciones
   públicas?
d) ¿Qué grupos de gastos conforman el gasto social de las
   administraciones públicas? ¿Qué porcentaje representan con respecto
   al gasto público total? ¿Y con respecto al PIB?


** Answer

Esto es una respuesta.



* Q.2

Acceda a la sección /Public finance/ del [[https://data-explorer.oecd.org][OECD Data Explorer]], y utilice
las herramientas que proporciona para que, con la información
contenida en /Public finance main indicators - Government at a Glance,
2023 edition/, comparar la evolución de las siguientes variables en
España con la OCDE y con los países de la Unión Europea miembros de la
OCDE:

a) Gasto público (/Government expenditure/).
b) Saldo fiscal (/Government fiscal balance/).
c) Déficit primario (/Government primary balance/).
d) Deuda pública (/Government gross debt/).

Obtenga gráficos de esas variables expresadas como porcentaje del PIB
y comente brevemente su evolución a lo largo del tiempo y la posición
de España con respecto a los países de su entorno.

** Answer

Esto es una respuesta.


* COMMENT Q.2

En este ejercicio se analiza el comportamiento de los gastos e
ingresos del Sector Público en España utilizando datos elaborados por
la [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Paginas/inicio.aspx][Intervención General de la Administración del Estado, IGAE]]. En el
Aula Virtual puede encontrar los archivos:

- ~A_AAPP.xlsx~: Operaciones no financieras del conjunto de las
  Administraciones Públicas.

- ~A_AAPP_Imp.xlsx~: Impuestos y cotizaciones sociales del conjunto de
  las Administraciones Públicas.

- ~COFOG.xlsx~: Clasificación funcional de los gastos de las diferentes administraciones que componen el Sector Público.

A partir de la información estadística contenida en esos archivos,
responda a las siguientes preguntas:


a) Examine la evolución del gasto público en España. ¿A cuánto
   asciende en los últimos años?  ¿Qué porcentaje con respecto al PIB
   representa el gasto público?

b) ¿Cómo se distribuye el gasto público entre las diferentes
   Administraciones Públicas?

c) Atendiendo a la /clasificación funcional de los gastos/, ¿qué
   grupos de gasto tienen un mayor peso en España? ¿Cuáles son los
   grupos más importantes para las diferentes Administraciones
   Públicas?

d) Examine la evolución de los ingresos del Sector Público en España
   ¿A cuánto ascienden durante los últimos años? ¿Qué porcentaje
   representan /los impuestos y las cotizaciones sociales/ con respecto
   a los ingresos totales de las Administraciones Públicas? ¿Cómo ha
   evolucionado la /presión fiscal/ en España?

e) ¿Cuál es el peso que tienen en España los /impuestos directos/, los
   /impuestos indirectos/ y las /cotizaciones sociales/? ¿Cómo ha
   evolucionado la importancia de cada una de esas categorías?

f) ¿Cuál es el tamaño del déficit público en España? Compare la
   evolución del /saldo fiscal/ (/capacidad/necesidad de
   financiación/) y del /saldo primario/. ¿Por qué son diferentes?

** Answer

Esto es una respuesta.



* COMMENT Q.2

Utilizando los datos que publica la OECD en
[[https://data.oecd.org/government.htm][https://data.oecd.org/government.htm]] describa y compare la magnitud y
la evolución reciente en España y en los países de su entorno de las
siguientes variables del Sector Público (en todos los casos se miden
como porcentaje con respecto al PIB):

a) Gastos (/General government spending/).
b) Ingresos (/General government revenues/).
c) Saldo fiscal (/General government deficit/).
d) Deuda pública (/General government debt/).
e) Presión fiscal (/Tax revenue/).

** Answer

Esto es una respuesta.
