#+SETUPFILE: ./probl-es.org

#+TITLE: Tercera entrega: ejercicios


* Q.4


En un país solo viven dos ciudadanos: Blanca y Teo. Blanca es abogada
y gana $50$ euros por hora. Teo trabaja en un pequeño taller de
reparaciones y gana $10$ euros por hora.

El gobierno está considerando gravar la renta de Blanca y transferir
íntegramente la recaudación a Teo. Se consideran seis tipos
impositivos sobre la renta de Blanca: \pct{0}, \pct{10}, \pct{30},
\pct{40}, \pct{60} y \pct{80}. Cualquiera que sea el tipo impositivo,
Teo trabaja siempre 40 horas semanales. La oferta semanal de trabajo
de Blanca depende del tipo impositivo y es la siguiente:
#+ATTR_LATEX: :booktabs t :align cc
| Tipo impositivo | Horas trabajadas por Blanca |
|-----------------+-----------------------------|
| \pct{ 0}        | \num{40}                    |
| \pct{10}        | \num{38}                    |
| \pct{30}        | \num{34}                    |
| \pct{40}        | \num{29}                    |
| \pct{60}        | \num{24}                    |
| \pct{80}        | \num{20}                    |

a) Suponga que Blanca y Teo tienen la misma función de utilidad: $U(Y)
   = Y^{1/2}$, donde $Y$ representa la renta disponible semanal,
   después de impuestos y transferencias. ¿Cuál de los seis tipos
   impositivos sería socialmente óptimo según un criterio
   utilitarista? ¿Y según un criterio rawlsiano?

b) Suponga ahora que Blanca y Teo siguen teniendo la misma función de
   utilidad, pero esta pasa a ser: $U(Y) = Y^{1/4}$. Determine los
   tipos impositivos socialmente óptimos según el criterio
   utilitarista y según el criterio rawlsiano.

c) Suponga ahora que Blanca y Teo tienen funciones de utilidad
   distintas. La utilidad de Teo es $U_T(Y) = Y^{1/2}$, mientras que
   la de Blanca es $U_B(Y) = Y^{2/5}$.  La diferencia refleja que
   Blanca sufre una discapacidad, por lo que necesita más renta para
   alcanzar el mismo nivel de utilidad. Calcule los tipos óptimos
   desde los puntos de vista utilitarista y rawlsiano.

** Answer

a) Blanca trabaja $H_B$ horas. Su renta disponible es:
   #+begin_export latex
   \[
     Y_B = (1 - t) 50 H_B
   \]
   #+end_export
   La renta disponible de Teo es la suma de su renta salarial y la
   transferencia recibida, que coincide con la recaudación del
   impuesto:
   #+begin_export latex
   \[
     Y_T = 400 + t 50 H_B
   \]
   #+end_export

   Las rentas disponibles de ambos dependen del tipo impositivo:
   #+ATTR_LATEX: :booktabs t :align *{4}{w{r}{1.5cm}}
   | $t$      | $H_B$    | $Y_B$      | $Y_T$      |
   |----------+----------+------------+------------|
   | \pct{ 0} | \num{40} | \num{2000} | \num{ 400} |
   | \pct{10} | \num{38} | \num{1710} | \num{ 590} |
   | \pct{30} | \num{34} | \num{1190} | \num{ 910} |
   | \pct{40} | \num{29} | \num{ 870} | \num{ 980} |
   | \pct{60} | \num{24} | \num{ 480} | \num{1120} |
   | \pct{80} | \num{20} | \num{ 200} | \num{1200} |

   La siguiente tabla muestra las utilidades de Blanca, $U_B$, y de
   Teo, $U_T$, y las funciones de bienestar social utilitarista,
   $W_U$, y rawlsiana, $W_R$:
   #+ATTR_LATEX: :booktabs t :align *{6}{w{r}{1.2cm}}
   | $t$      | $U_B$       | $U_T$       | $W_U$       | $W_R$       |
   |----------+-------------+-------------+-------------+-------------|
   | \pct{ 0} | \num{44.72} | \num{20.00} | \num{64.72} | \num{20.00} |
   | \pct{10} | \num{41.35} | \num{24.29} | \num{65.64} | \num{24.29} |
   | \pct{30} | \num{34.50} | \num{30.17} | \num{64.66} | \num{30.17} |
   | \pct{40} | \num{29.50} | \num{31.30} | \num{60.80} | \num{29.50} |
   | \pct{60} | \num{21.91} | \num{33.47} | \num{55.38} | \num{21.91} |
   | \pct{80} | \num{14.14} | \num{34.64} | \num{48.78} | \num{14.14} |
   El máximo de $W_U$ se alcanza con $t=\pct{10}$, mientras que el
   máximo de $W_R$ se produce cuando $t=\pct{30}$.

b) Cálculo de las funciones de bienestar social:
   #+ATTR_LATEX: :booktabs t :align *{6}{w{r}{1.2cm}}
   | $t$      | $U_B$      | $U_T$      | $W_U$       | $W_R$      |
   |----------+------------+------------+-------------+------------|
   | \pct{ 0} | \num{6.69} | \num{4.47} | \num{11.16} | \num{4.47} |
   | \pct{10} | \num{6.43} | \num{4.93} | \num{11.36} | \num{4.93} |
   | \pct{30} | \num{5.87} | \num{5.49} | \num{11.37} | \num{5.49} |
   | \pct{40} | \num{5.43} | \num{5.60} | \num{11.03} | \num{5.43} |
   | \pct{60} | \num{4.68} | \num{5.79} | \num{10.47} | \num{4.68} |
   | \pct{80} | \num{3.76} | \num{5.89} | \num{ 9.65} | \num{3.76} |
   En este caso, las dos funciones de bienestar social alcanzan su valor
   máximo con $t=\pct{30}$.

c) Cálculo de las funciones de bienestar social:
   #+ATTR_LATEX: :booktabs t :align *{6}{w{r}{1.2cm}}
   | $t$      | $U_B$       | $U_T$       | $W_U$       | $W_R$       |
   |----------+-------------+-------------+-------------+-------------|
   | \pct{ 0} | \num{20.91} | \num{20.00} | \num{40.91} | \num{20.00} |
   | \pct{10} | \num{19.64} | \num{24.29} | \num{43.93} | \num{19.64} |
   | \pct{30} | \num{16.99} | \num{30.17} | \num{47.16} | \num{16.99} |
   | \pct{40} | \num{14.99} | \num{31.30} | \num{46.30} | \num{14.99} |
   | \pct{60} | \num{11.82} | \num{33.47} | \num{45.28} | \num{11.82} |
   | \pct{80} | \num{ 8.33} | \num{34.64} | \num{42.97} | \num{ 8.33} |
   La aplicación del criterio utilitarista llevaría a fijar
   $t=\pct{30}$. El criterio rawlsiano seleccionaría $t=\pct{0}$ en
   este caso.


* Q.2

En una pequeña ciudad sólo viven dos personas: Ana y Belén. El
servicio de limpieza municipal, que es un bien público, se financia
exclusivamente con sus aportaciones voluntarias. Tanto Ana como Belén
tienen las mismas preferencias sobre su consumo de un bien privado,
$Y$, y sobre el número total de horas semanales de servicio de
limpieza municipal, $N$. Estas preferencias se pueden representar
mediante las funciones de utilidad:
#+begin_export latex
\begin{gather*}
  \text{Ana: } U_{A} = 4 \log Y_A + 2 \log N, \\
  \text{Belén: } U_{B} = 4 \log Y_{B} + 2 \log N,
\end{gather*}
#+end_export
donde $Y_A$ y $Y_B$ son las unidades del bien privado consumidas por
Ana y por Belén, respectivamente. El número total de horas de limpieza
prestadas a la semana es la suma de las horas financiadas por Ana,
$N_A$, y por Belén, $N_B$: $N = N_A + N_B$. Tanto Ana como Belén
disponen de una renta semanal de \money{600}. El precio de una unidad
del bien privado $Y$ es \money{10} y el coste de una hora de servicio
de limpieza es \money{8}.

a) ¿Cuántas horas semanales de limpieza municipal se contratarán en
   estas condiciones?

b) ¿Cuál es el número socialmente óptimo de horas de limpieza? Si su
   respuesta difiere de la del apartado anterior, explique por qué.

c) El ayuntamiento decide proveer $20$ horas adicionales de limpieza a
   la semana, que financia mediante un impuesto de \money{80} a cada
   habitante. ¿Cuál es ahora el número total de horas de limpieza
   prestadas? ¿Se ha alcanzado el óptimo social? ¿Por qué?

d) Suponga ahora que un misterioso benefactor se hace cargo del coste
   de las $20$ horas adicionales, de forma que se elimina el
   impuesto. ¿Se obtienen en este caso los mismos resultados que en el
   apartado anterior?


** Answer

a) <<item:2a>>Cada persona decide cuánto aportar voluntariamente a la
   financiación del servicio de limpieza municipal.

   Ana decide los valores óptimos de $Y_A$ y $N_A$ maximizando su
   función de utilidad:
   #+begin_export latex
   \[
     U_A = 4 \log Y_A + 2 \log (N_A + N_B),
   \]
   #+end_export
   sujeto a su restricción presupuestaria
   #+begin_export latex
   \[
     10Y_A + 8N_A = 600.
   \]
   #+end_export
   Despejando $Y_A$ en la restricción presupuestaria y sustituyendo en
   la función de utilidad:
   #+begin_export latex
   \[
     U_A = 4 \log \left(\frac{600 - 8N_A}{10}\right) + 2 \log (N_A + N_B).
   \]
   #+end_export
   La condición de primer orden es:
   #+begin_export latex
   \[
     \frac{\diff U_A}{\diff N_A} =
     -\frac{32}{600 - 8N_A} + \frac{2}{N_A + N_B} = 0.
   \]
   #+end_export
   Reordenando, se obtiene:
   #+begin_export latex
   \[
     N_A = 25 - 2 N_B / 3.
   \]
   #+end_export

   La función de utilidad de Belén es idéntica a la de Ana y ambas
   disponen de la misma renta y se enfrentan a los mismos precios. Por
   tanto, la función de reacción de Belén es simétrica a la de Ana:
   #+begin_export latex
   \[
     N_B = 25 - 2 N_A / 3.
   \]
   #+end_export
   En equilibrio, $N_A = N_B$. Sustituyendo en cualquiera de las
   funciones de reacción se obtiene $N_A = N_B = 15$ horas. Por tanto
   se contratarán $N_A + N_B = 30$ horas semanales.

b) El óptimo social se obtiene maximizando la suma de utilidades de
   Ana y Belén:
   #+begin_export latex
   \[
     W = 4 \log Y_A + 2 \log N + 4 \log Y_B + 2 \log N.
   \]
   #+end_export
   sujeto a la restricción presupuestaria conjunta:
   #+begin_export latex
   \[
      10Y_A + 10Y_B + 8N = 1200.
   \]
   #+end_export
   Como ambas personas son idénticas, en el óptimo se cumple $Y_A =
   Y_B = Y$. Teniendo esto en cuenta, la restricción se puede
   escribir como:
   #+begin_export latex
   \begin{equation}\label{eq:1}
     Y = (600 - 4 N) / 5.
   \end{equation}
   #+end_export
   Por otro lado, la función de bienestar social se puede escribir:
   #+begin_export latex
   \begin{equation}\label{eq:2}
     W = 8 \log Y + 4 \log N.
   \end{equation}
   #+end_export
   Sustituyendo \eqref{eq:1} en \eqref{eq:2}:
   #+begin_export latex
   \[
     W = 8 \log \left(\frac{600 - 4N}{5}\right) + 4 \log N.
   \]
   #+end_export
   Derivando con respecto de $N$ e igualando a $0$, se obtiene la
   condición de primer orden:
   #+begin_export latex
   \[
     \frac{\diff W}{\diff N} = -\frac{32}{600 - 4N} + \frac{4}{N} = 0.
   \]
   #+end_export
   Resolviendo la ecuación anterior se obtiene que el número óptimo de
   horas de limpieza a la semana es $N = 50$.
   #+latex: \smallskip

   Este resultado difiere del apartado anterior porque, con
   aportaciones voluntarias, cada persona tiene en cuenta sólo el
   beneficio privado de su contribución y no el beneficio que también
   obtiene la otra. En consecuencia, la provisión privada es
   inferior a la socialmente óptima.

c) <<item:2c>>El ayuntamiento provee $20$ horas adicionales de
   limpieza y las financia mediante un impuesto de \money{80} a cada
   habitante. El número de horas total de limpieza es:
   #+begin_export latex
   \[
     N = N_A + N_B + 20.
   \]
   #+end_export
   La utilidad de Ana es:
   #+begin_export latex
   \[
     U_A = 4 \log Y_A + 2 \log (N_A + N_B + 20).
   \]
   #+end_export
   La restricción presupuestaria de Ana se ve modificada con la
   introducción del impuesto:
   #+begin_export latex
   \[
     10Y_A + 8N_A = 520.
   \]
   #+end_export
   Despejando $Y_A$ y sustituyendo en la función de utilidad:
   #+begin_export latex
   \[
     U_A = 4 \log \left(\frac{520 - 8N_A}{10}\right) + 2 \log (N_A + N_B + 20).
   \]
   #+end_export
   La condición de primer orden es:
   #+begin_export latex
   \[
     \frac{\diff U_A}{\diff N_A} =
     -\frac{32}{520 - 8N_A} + \frac{2}{N_A + N_B + 20} = 0.
   \]
   #+end_export
   Reordenando, se obtiene:
   #+begin_export latex
   \[
     N_A = (25 - 2 N_B) / 3.
   \]
   #+end_export
   Dado que el problema es simétrico para Ana y Belén, el número de
   horas que contrata cada una de ellas es el mismo. Por tanto, $N_A =
   N_B = 5$ horas. El número total de horas de limpieza sigue siendo
   $N_A + N_B + 20 = 30$.
   #+latex: \smallskip

   A pesar de la intervención del ayuntamiento, no se ha alcanzado el
   óptimo social, que corresponde a $50$ horas semanales. Las $20$
   horas adicionales financiadas públicamente desplazan exactamente
   $20$ horas de aportaciones privadas: antes cada persona aportaba
   $15$ horas y ahora aporta solamente $5$.

d) Ahora un benefactor financia el coste de las 20 horas adicionales,
   por lo que desaparece el impuesto. Cada persona vuelve a disponer
   de su renta completa de \money{600}.

   La función de utilidad de Ana es:
   #+begin_export latex
   \[
     U_A = 4 \log Y_A + 2 \log (N_A + N_B + 20),
   \]
   #+end_export
   y su restricción presupuestaria es:
   #+begin_export latex
   \[
     10Y_A + 8N_A = 600.
   \]
   #+end_export
   La condición de primer orden para la maximización de la utilidad es:
   #+begin_export latex
   \[
     \frac{\diff U_A}{\diff N_A} =
     -\frac{32}{600 - 8N_A} + \frac{2}{N_A + N_B + 20} = 0.
   \]
   #+end_export
   Reordenando:
   #+begin_export latex
   \[
     N_A = (35 - 2 N_B) / 3.
   \]
   #+end_export
   Por simetría, en equilibrio $N_A = N_B = 7$ horas a la semana. El
   número total de horas de limpieza es $N_A + N_B + 20 = 34$.
   #+latex: \smallskip

   No se obtienen los mismos resultados que en el apartado anterior,
   ya que ahora las 20 horas adicionales no reducen la renta
   disponible de Ana y Belén.  En comparación con el apartado [[item:2a]],
   sus aportaciones privadas disminuyen, pero menos que en el apartado
   [[item:2c]].

* Q.3

En un pequeño municipio se está debatiendo si el ayuntamiento debe
instalar un sistema de vigilancia y alerta temprana frente a incendios
forestales. La provisión de este servicio público tendría un coste
total de $90$ euros al mes.

En el municipio sólo viven tres personas: Alicia, Beatriz y Carlos. Sus
disposiciones máximas a pagar por la instalación de este sistema son,
respectivamente, $16$, $20$ y $60$ euros al mes. Las rentas mensuales
de Alicia, Beatriz y Carlos son, respectivamente, $1500$, $1500$ y $6000$
euros. La decisión sobre si proveer o no este bien público se adopta
mediante votación.

a) ¿Es eficiente proveer este bien público? Razone su respuesta.

b) Suponga que, si se aprueba la provisión del bien público, su coste
   se financia mediante una capitación, es decir, mediante una
   contribución igual para cada persona. ¿Cuál sería el resultado de
   la votación? ¿Sería eficiente ese resultado?

c) Suponga ahora que, si se aprueba la provisión del bien público, su
   coste se financia mediante un impuesto proporcional sobre la
   renta. ¿Cuál sería el resultado de la votación? ¿Sería eficiente
   ese resultado?


** COMMENT Sugerencia

Cambiar los números para que en el apartado c) Alicia vote en
contra. Bastaría con cambiar la disposición a pagar a 12, ¿no?. Por
otro lado, Carlos pagaría exactamente su disposición máxima. Se podría
aumentar.


** Answer

a) La provisión del bien público es eficiente si la suma de las
   disposiciones a pagar de los tres individuos es mayor que el coste
   total. En este caso, la disposición a pagar colectiva es: $16 +
   20 + 60 = \money{96}$ al mes. Dado que el coste mensual del
   sistema es de \money{90}, sería eficiente proveer el bien público.

b) Si el coste se financia mediante una capitación, cada persona debe
   pagar la misma cantidad. Como el coste total es $90$ euros y hay tres
   personas, la contribución de cada una sería de $30$ euros.
   Cada persona votará a favor si su disposición a pagar es al menos
   igual a la cantidad que debe pagar.
   #+latex: \smallskip

   Tanto Alicia como Beatriz votarían en contra, ya que su disposición
   a pagar ($16$ y $20$ euros, respectivamente) es inferior al
   impuesto de $30$ euros. Tan solo Carlos votaría a favor.
   #+latex: \smallskip

   El resultado de la votación sería, por tanto, dos votos en contra y
   uno a favor, de modo que se llega a una situación ineficiente donde
   el bien público no se provee.

c) Se establece un impuesto proporcional a la renta para financiar el
   sistema de vigilancia. El tipo impositivo, $t$, se determina
   igualando la recaudación del impuesto al coste del bien público:
   #+begin_export latex
   \[
     1500 t + 1500 t + 6000 t = 90,
   \]
   #+end_export
   por lo que $t = \pct{1}$.
   #+latex: \smallskip
   La tabla siguiente muestra para cada persona su disposición a
   pagar, el impuesto correspondiente y el beneficio neto:

   #+ATTR_LATEX: :booktabs t :align lrrr
   |         | Disp. a pagar | Impuesto | Beneficio neto |
   |---------+---------------+----------+----------------|
   | Alicia  | \num{16}      | \num{15} | \num{1}        |
   | Beatriz | \num{20}      | \num{15} | \num{5}        |
   | Carlos  | \num{60}      | \num{60} | \num{0}        |
   En este caso, ninguna de las disposiciones a pagar es inferior al
   impuesto correspondiente y todos votarían a favor. En conclusión,
   se aprobaría la propuesta y se alcanzaría la solución eficiente
   consistente en la instalación del sistema de vigilancia y alerta
   temprana.



* COMMENT Q.1

Imagine una economía donde sólo habitan dos consumidores, Aurora y Bernardo.

a) Si la función de bienestar social es:
   #+begin_export latex
   \[ W_1 = U_A + U_B \]
   #+end_export
   donde $U_A$ y $U_B$ son las utilidades de Aurora y Bernardo,
   respectivamente. Dibuje las curvas de indiferencia social. ¿Cómo
   describiría la importancia relativa que se asigna a cada
   utilidad?

b) ¿Cómo cambiaría su respuesta al apartado anterior si la función
   de bienestar social fuera $W_2 = U_A + 2 U_B$?

c) ¿Y si fuera $W_3 = \min\{U_A, U_B\}$?

d) Suponga que la función de posibilidades de utilidad es:
   #+xxx: fig file:fig-04_1047-01-*.pdf
   Muestre gráficamente como difieren las soluciones óptimas para
   las funciones de bienestar social de los apartados anteriores.

** Answer

Por hacer


* COMMENT Q.6

En una economía hay dos consumidores y la función de utilidad de cada
uno de ellos es $U_i = \log(Y_i)$, $i = 1, 2$, donde $Y_i$ es la renta
del consumidor $i$. Se quiere distribuir entre los dos consumidores la
renta total de la economía $\overline{Y} = \money{1000}$. Si se usa una
función de bienestar social utilitarista, $W = U_1 + U_2$:

a) ¿Sería óptima la distribución $Y_1 = \money{200}$ e $Y_2 =
   \money{800}$? ¿Por qué?

b) Obtenga la distribución óptima de la renta.



* COMMENT Q.11

¿Es posible encontrar una situación en la que que el óptimo social de
acuerdo a una función de bienestar /rawlsiana/ coincida con el que se
obtendría con una función de bienestar utilitarista?  Represente
gráficamente.


* COMMENT Q.12

Considere una economía con dos individuos $A$ y $B$. La tabla
siguiente muestra algunas combinaciones de utilidad que se
encuentran sobre la frontera de posibilidades de utilidad:

#+begin_export latex
\begin{center}
  \begin{tabular}{>{$}l<{$}*{2}{>{$}r<{$}}}
    \toprule
    \text{Opción} & U_A & U_B \\
    \midrule
    M & 100 &  0 \\
    N &  90 & 20 \\
    O &  60 & 30 \\
    P &  30 & 30 \\
    Q &  40 & 60 \\
    R &  10 & 70 \\
  \bottomrule
\end{tabular}
\end{center}
#+end_export

Indique cuál será la opción elegida de acuerdo con:

a) el criterio utilitarista.

b) el criterio igualitarista.

c) el criterio /rawlsiano/.


* COMMENT Q.14

\DANGER Una economía está compuesta por dos individuos: $A$ y
$B$. $A$ dispone de un factor de producción que puede usar para
producir un bien de consumo $X$. $B$ no posee ninguna unidad del
factor de producción y, por tanto, no puede producir nada. Para
paliar esta situación el gobierno puede transferir a $B$ una
fracción $t$ de la producción de $A$. La producción de $A$ depende
de $t$ mediante la siguiente función:
#+begin_export latex
\[
  X(t) = 167 (1 - t) (t + 0.6)
\]
#+end_export
Suponiendo que la utilidad de ambos individuos es igual a la
cantidad que consumen del bien $X$, determinar qué fracción debería
$t$ debería establecerse de acuerdo a un criterio:

a) utilitarista.

b) /rawlsiano/.

c) igualitarista.



# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  Teo rawlsiano Answer
