#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit06}}}: ejercicios


* Q.1

¿Son las autopistas un bien público? ¿Es eficiente la provisión
privada de autopistas?


** Answer

Características de un bien público:

- /No rivalidad/. Se cumple, salvo que la autopista esté congestionada.

- /No exclusión/. No se cumple: es posible establecer peajes.
#+latex: \vspace*{1ex}

Sin congestión, la provisión privada no es eficiente:

- Para poder obtener beneficios, la empresa privada ha de establecer
  peajes e incurrir en costes de transacción.

- Los peajes impiden que algunos conductores usen la autopista. No es
  socialmente óptimo excluir a nadie del consumo de bienes no rivales.


* Q.2

Considere una economía con dos habitantes $A$ y $B$ que consumen dos
bienes: el bien público puro $X$ y el bien privado $Y$. Actualmente se
producen 50 unidades del bien $X$ y 200 unidades del bien $Y$. Toda la
producción del bien $Y$ se reparte a partes iguales entre los dos
consumidores. Las relaciones marginales de sustitución son: $\RMS_A =
\RMS_B = 8$ unidades de $Y$ por unidad de $X$. La relación marginal de
transformación es $\RMT = 20$ unidades de $Y$ por unidad de $X$. ¿Es
eficiente la situación descrita? ¿Debería aumentar la producción del
bien público?


** Answer

Obtenemos la valoración social de 1 unidad adicional del bien público
sumando las valoraciones de cada uno de los dos habitantes:
#+begin_export latex
\[
  \RMS_A + \RMS_B = 16\;\text{unidades de $Y$ por unidad de $X$}.
\]
#+end_export
La condición de eficiencia requiere que se igualen la valoración
social y la relación marginal de transformación. Esta condición no se
cumple en el caso que estamos considerando:
#+begin_export latex
\[
  \RMS_A + \RMS_B = 16 < \RMT = 20.
\]
#+end_export
Se debería reducir su producción del bien público ya que que la
valoración social de la última unidad de $X$ es inferior a su coste de
oportunidad.


* Q.3

Rocío y Pablo comparten un piso. La siguiente tabla muestra, para un
conjunto de temperaturas, el beneficio marginal de Rocío, el beneficio
marginal de Pablo y el coste marginal de mantener el piso a esa
temperatura durante una semana.
#+begin_center
#+latex: \small\normalfont%
#+attr_latex: :booktabs :center :align @{}*{4}{c}@{}
|-------------+--------------------+--------------------+----------------|
| Temperatura | Beneficio marginal | Beneficio marginal | Coste marginal |
|        (ºC) |       Rocío (€/ºC) |       Pablo (€/ºC) |         (€/ºC) |
|-------------+--------------------+--------------------+----------------|
|          18 |                  8 |                 12 |             14 |
|          19 |                  7 |                 10 |             17 |
|          20 |                  5 |                  8 |             21 |
|          21 |                  2 |                  6 |             26 |
|          22 |                  1 |                  3 |             32 |
|-------------+--------------------+--------------------+----------------|
#+end_center
¿Es la temperatura del piso un bien público? ¿Cuál sería la
temperatura eficiente?


** Answer


La temperatura del piso puede considerarse un bien público ya que su
consumo es no rival y no excluible. Para determinar la temperatura
óptima, calculamos el beneficio marginal social, \BMS, sumando los
beneficios marginales de Rocío y Pablo, y comparamos con el coste
marginal:

#+begin_center
#+latex: \newcommand*{\thin}[1]{\textcolor{gray!70}{#1}}
#+latex: \small\normalfont%
#+attr_latex: :booktabs :center :align crr
|-----------+--------------------------+-----------|
| ºC        | $\BMS = \BMg_R + \BMg_P$ | $\CMg$    |
|-----------+--------------------------+-----------|
| \thin{18} | \thin{20}                | \thin{14} |
| 19        | 17                       | 17        |
| \thin{20} | \thin{13}                | \thin{21} |
| \thin{21} | \thin{ 8}                | \thin{26} |
| \thin{22} | \thin{ 4}                | \thin{32} |
|-----------+--------------------------+-----------|
#+end_center

La temperatura eficiente es de 19ºC, ya que entonces se igualan el
beneficio marginal social del bien público y su coste marginal.


* Q.4

Suponga que sólo dos pescadores, Acab e Ismael, faenan en una
misma zona. Ambos se beneficiarían de la instalación de faros en
esa zona. El coste de construir cada faro es de
\money{100}. Para Acab, el beneficio marginal de un faro adicional es
$\BMg_{A} = 90 - 5 Q$, mientras que para Ismael es $\BMg_{I} = 40 - 5
Q$, donde $Q$ es el número total de faros construidos.

a) ¿Cuál es el número eficiente de faros? ¿Cuáles serían los
   beneficios marginales de Acab y de Ismael si se construyera el
   número eficiente de faros?

b) Si los faros se construyeran de forma independiente por Acab e
   Ismael, ¿cuántos instalaría cada uno? ¿Se alcanzaría el número
   socialmente óptimo de faros?


** Answer

a) Dado que los faros son un bien público puro, la condición de
   eficiencia es:
   #+begin_export latex
   \[
     \BMg_A + \BMg_I = \CMg.
   \]
   #+end_export
   La cantidad eficiente de faros, $Q_e$, se obtiene resolviendo:
   #+begin_export latex
   \[
     (90 - 5Q_e) + (40 - 5Q_e) = 100,
   \]
   #+end_export
   por lo que $Q_e = 3\;\text{faros}$.
   #+latex: \vspace*{1ex}

   Los beneficios marginales cuando se construye el número eficiente
   de faros son:
   #+begin_export latex
   \begin{gather*}
     \BMg_A(3) = 90 - 5\cdot 3 = 75\;\text{\texteuro/faro}, \\
     \BMg_I(3) = 40 - 5\cdot 3 = 25\;\text{\texteuro/faro}.
   \end{gather*}
   #+end_export

b) Si cada pescador decide de forma privada, construirá faros mientras
   que: $\BMg_i(Q) > \CMg$. Sin embargo, el beneficio que obtendría
   cada pescador por la construcción del primer faro sería inferior al
   coste de producción:
   #+begin_export latex
   \begin{gather*}
     \BMg_A(1) = 85 < \CMg = 100, \\
     \BMg_I(1) = 35 < \CMg = 100.
   \end{gather*}
   #+end_export
   En estas condiciones, no se construiría ningún faro. La producción
   de mercado, $Q_m = 0\;\text{faros}$, sería inferior a la producción
   socialmente óptima, $Q_e = 3\;\text{faros}$. La provisión privada
   del bien público conduciría a una situación de subproducción.


* Q.5

El coste marginal de producir Q unidades de un bien público puro es:
$\CM = 5 Q$. Existen dos grupos de consumidores. El primero está
compuesto por 75 demandantes, cada uno de ellos con demanda igual a $Q
= 50 - 5 P$. El segundo grupo lo forman 5 consumidores cuyas demandas
individuales son $Q = 50 - P$. ¿Cuál sería la provisión eficiente del
bien público? Represente gráficamente.


** Answer

Para obtener la demanda colectiva del bien público sumamos las curvas
de demanda inversa de todos los consumidores. La curva de demanda
inversa representa la disposición a pagar de un consumidor por cada
unidad adicional del bien público. Al sumar las demandas inversas
individuales obtenemos el beneficio marginal social, que coincide con
la valoración social de cada unidad del bien público.
#+latex: \vspace*{1ex}

Curvas inversas de demanda individuales:

- Primer grupo: $P = 10 - 0.2Q$.

- Segundo grupo: $P = 50 - Q$.

Demanda colectiva:
#+begin_export latex
\[
  \BMS = 75 \cdot (10 - 0.2 Q) + 5 \cdot (50 - Q) = 1000 - 20 Q.
\]
#+end_export

La provisión eficiente requiere que se igualen el beneficio marginal
social y el coste marginal:
#+begin_export latex
\[
  1000 - 20 Q = 5 Q,
\]
#+end_export
por lo que deberían producirse $Q = 40$ unidades del bien público.

#+xxx: fig file:fig-06_1047-ex5-1-*.pdf


* Q.6

La curva de demanda de un bien privado viene dada por $P = 50 - Q$. El
coste de producir una unidad adicional del bien es de \price{15} y no
depende de la cantidad producida. Cuando el bien lo proveen empresas
competitivas, estas tienen que afrontar unos costes de transacción de
\price{10}. El gobierno está planteándose la posibilidad de proveer el
bien gratuitamente, en cuyo caso no existirían costes de
transacción. ¿Es eficiente la provisión privada?  ¿Y la pública? ¿Cuál
de las dos opciones es más conveniente desde el punto de vista social?


** Answer

En la solución eficiente se igualaría el precio al coste marginal $P^E
= \CMg = \price{15}$ y se producirían las unidades que se demandan a
ese precio: $Q^E = 35$ unidades.
#+latex: \vspace*{1ex}

Cuando el bien es provisto por empresas privadas, éstas tienen en
cuenta tanto los costes de producción, $\CMg = \price{15}$, como los
costes de transacción, $c_T = \price{10}$. En este caso, la condición
de equilibrio competitivo es:
#+begin_export latex
\[
  P^C = \CMg + c_T = \price{25}
\]
#+end_export
y se producirían $Q^C = 25$ unidades. La provisión privada conduciría
a una situación de subproducción ya que el número de unidades
producidas sería inferior al óptimo.
#+latex: \vspace*{1ex}

Si el gobierno provee gratuitamente el bien, se llegaría a una
situación de sobreproducción, ya que se producirían $Q^P = 50$
unidades.
# #+latex: \vspace*{1ex}

#+xxx: fig file:fig-06_1047-ex6-1-*.pdf

Ni la provisión privada ni la pública serían eficientes en este
caso. Para determinar que opción sería preferible, se calcula el
cambio en el bienestar social cuando la provisión pasa a ser pública:

- Al ser gratuita la provisión pública, la sociedad se ahorra los
  costes de transacción y el bienestar social aumenta en $Q^C c_T = 25
  \cdot 10 = \money{250}$.

- La producción privada es $10$ unidades inferior a la óptima. Cuando
  la provisión es pública, estas $10$ unidades se producen y generan
  un aumento de bienestar de $(Q^E - Q^C) (P^C - P^E) / 2 = 10 \cdot
  10 / 2 = \money{50}$.

- La provisión pública es superior a la eficiente en $15$ unidades. La
  valoración de estas unidades es inferior a su coste de producción y,
  al producirlas, el bienestar social disminuye en $(Q^P - Q^E) P^E /
  2 = 15 \cdot 15 / 2 = \money{112.5}$.

En conclusión, si la provisión del bien pasara a ser pública, el
bienestar social se incrementaría en $250 + 50 - 112.5 =
\money{187.5}$. Por tanto, sería más conveniente la provisión pública
gratuita.


* Q.7

La curva de costes de un monopolio natural es: $\CT(Q) = \num{10000} +
Q$. La curva de demanda de mercado es $Q = \num{5150} - 50 P$.

a) ¿Cuál sería el precio que maximiza el beneficio de la empresa?
   Calcule la pérdida de eficiencia en esta situación.

b) Si el Gobierno obliga al monopolista a fijar el precio competitivo,
   ¿cuál sería el beneficio del monopolista?

c) Determine qué precio debería fijar el regulador para que el
   monopolio obtenga beneficios nulos.


** Answer

a) La curva inversa de demanda es:
   #+begin_export latex
   \[
     P = 103 - Q / 50.
   \]
   #+end_export
   El ingreso marginal es:
   #+begin_export latex
   \[
     \IMg  = 103 - Q/25.
   \]
   #+end_export
   El monopolio obtiene beneficios máximos cuando se igualan el
   ingreso marginal y el coste marginal:
   #+begin_export latex
   \[
     103 - Q_M/25 = 1.
   \]
   #+end_export
   Por tanto, el monopolio producirá $Q_M = 2550$ unidades. La curva
   de demanda determina a qué precio se venderán estas unidades:
   #+begin_export latex
   \[
     P_M = P(2550) = 103 - 2550 / 25 = \price{52}.
   \]
   #+end_export

   #+xxx: fig file:fig-06_1047-ex7-1-*.pdf

   Para calcular la ineficiencia del monopolio, se comparará con el
   equilibrio competitivo. El precio competitivo sería igual al coste
   marginal, $P_C = \price{1}$. A ese precio se demandarían $Q_C =
   5100$ unidades. La pérdida de eficiencia del monopolio es:
   #+begin_export latex
   \[
     \big[P_M - \CMg(Q_M)\big] \big(Q_C - Q_M\big) / 2 =
     (52 - 1) (5100 - 2550) / 2 = \money{65025}.
   \]
   #+end_export

b) Los beneficios de la empresa pueden calcularse como:
   #+begin_export latex
   \[
     \pi(Q) = \big(P(Q) - \CMe(Q)\big) Q,
   \]
   #+end_export
   donde $\CMe(Q)$ es la curva de costes medios:
   #+begin_export latex
   \[
     \CMe(Q) = \num{10000} / Q + 1
   \]
   #+end_export
   Si se introduce una regulación que obligue al monopolio a fijar el
   precio competitivo, $P = \price{1}$, se venderán $Q = 5100$
   unidades y el beneficio de la empresa será:
   #+begin_export latex
   \[
     \pi = (1 - \num{10000} / 5100 + 1) \cdot 5100 = -\money{10000}.
   \]
   #+end_export
   El precio sería inferior al coste medio, $\CMe \approx
   \price{2.96}$, y el monopolio incurriría en pérdidas.

   #+xxx: fig file:fig-06_1047-ex7-2-*.pdf


c) Si el beneficio es nulo, el precio debe ser igual al coste medio:
   #+begin_export latex
   \[
     103 - Q_N / 50 = \num{10000} / Q_N + 1.
   \]
   #+end_export
   Operando en la expresión anterior, se obtiene una ecuación
   cuadrática:
   #+begin_export latex
   \[
      Q_N^2 - 5100 Q_N + \num{500000} = 0.
   \]
   #+end_export
   Las raíces de la expresión anterior satisfacen:
   #+begin_export latex
   \[
     Q_N =
     \frac{5100 \pm \sqrt{5100^2 - 4 \cdot \num{500000}}}{2} =
     2550 \pm 2450.
   \]
   #+end_export
   La empresa obtiene beneficios nulos cuando produce \units{100} o
   \units{5000}. Dado que el objetivo de la regulación es maximizar el
   beneficio social se selecciona la cantidad mayor. Por tanto, la
   producción sería $Q_N = 5000$ unidades que se venderían a un precio
   $P_N = \CMe(Q_N) = \price{3}$.


* COMMENT Q.4

Tarzán y Jane viven en la jungla y han adiestrado a Chita para que
patrulle los límites de su asentamiento y para que recolecte
fruta. Chita puede recoger 3 kg de fruta por hora y dedica 6 horas al
día a patrullar y 8 horas a recolectar fruta.

a) Identifique si los bienes de este ejemplo son públicos o privados.

b) Si Tarzán y Jane están dispuestos cada uno a sacrificar una hora de
   patrulla por 2 kg de fruta, ¿es la actual asignación de horas
   patrullando y recolectando un óptimo de Pareto? ¿Debería Chita
   patrullar más horas o menos?


** Answer

Por hacer.


* COMMENT Q.8

En una ciudad hay tres tipos de personas que se distinguen únicamente
por sus preferencias con respecto a los parques municipales. Cada una
de las personas del primer tipo está dispuesta a pagar $D_I =
\money{100}$ por la mera existencia de algún parque y esta disposición
es independiente del número de parques que haya. Por otro lado, la
disposición a pagar de los individuos de los otros dos tipos es:
#+begin_export latex
\begin{gather*}
D_{II} = 200 + 30 N - 1.5N^2 \\
D_{III} = 150 + 90 N - 4.5N^2
\end{gather*}
#+end_export
donde $N$ es el número de parques de la ciudad. Si hay 500 individuos
de cada tipo, cada parque cuesta $\money{40000}$ y solo se puede
construir un número entero de parques, ¿cuántos deben de construirse?


** Answer

Por hacer.



* COMMENT Q.11

En la segunda década del siglo XXI, el Presidente de México intentó
privatizar Pemex, la empresa estatal productora, refinadora y
comercializadora de petróleo. Muchos de los opositores al proyecto
argumentaron que la privatización de la compañía de teléfonos mejicana
Telmex sólo consiguió crear un monopolio que fijaba precios
exorbitantes. ¿Cree que hubiera ocurrido lo mismo si Pemex se hubiese
privatizado? Relacione su respuesta con el papel que juegan las
condiciones del mercado sobre las consecuencias de las
privatizaciones.


* COMMENT Q.12

Se ha estimado que el coste por interno en las prisiones privadas es
entre un 5% y un 15% menor que en los establecimientos penitenciarios
públicos. De acuerdo con esto, ¿recomendaría que se privaticen las
prisiones? ¿Qué otra información necesitaría para evaluar la
conveniencia de la privatización de las cárceles?


* COMMENT Q.13

\DANGER En una pequeña ciudad sólo viven dos personas: Alba y
Blanca. El servicio de bomberos de la ciudad se financia
exclusivamente con su aportaciones voluntarias. Tanto Alba como Blanca
tienen las mismas preferencias sobre su consumo de bienes privados,
$Y_i$, y sobre el número total de bomberos contratado por el
ayuntamiento, $N$. Estas preferencias se pueden representar por las
funciones de utilidad:
#+begin_export latex
\begin{gather*}
  \text{Alba: } U_{A} = 4 \log Y_A + 2 \log N \\
  \text{Blanca: } U_{B} = 4 \log Y_{B} + 2 \log N
\end{gather*}
#+end_export
El número total de bomberos es la suma de los contratados por las
aportaciones de Ana, $N_A$, y de Blanca, $N_B$: $N = N_A + N_B$. Tanto
Ana como Blanca disponen de una renta de \money{150} y los precios por
unidad de $Y$ y de $N$ son iguales a \money{1}.

a) ¿Cuántos bomberos se contratarán en estas condiciones?

b) ¿Cuál es el número socialmente óptimo de bomberos? Si su respuesta
   difiere de la del apartado anterior, explique por qué.

c) El ayuntamiento decide contratar 40 bomberos más que financia
   mediante un impuesto de \money{20} a cada habitante. ¿Cuál es ahora
   número total de bomberos contratados? ¿Se ha alcanzado el óptimo
   social? ¿Por qué?

d) Suponga ahora que en vez de tener que financiar con impuestos los
   40 bomberos que contrata el ayuntamiento, un misterioso benefactor
   se hace cargo de los gastos adicionales. ¿Se obtienen en este caso
   los mismos resultados que en el apartado anterior?


** Answer

Por hacer.


* COMMENT Q.14

Empresas privadas de seguridad proporcionaron parte del apoyo
logístico de las fuerzas armadas de Estados Unidos en Afganistán e
Irak. Las críticas a las fuerzas mercenarias se han centrado en que
cargan precios excesivos, actúan de forma irresponsable y no
proporcionan soluciones de largo plazo. Como expresó un [[https://www.nytimes.com/2006/12/11/opinion/11krugman.html][comentarista]]:
"No hay ninguna razón para suponer que una empresa privada contratada
para realizar un servicio público lo lleve a cabo mejor que personas
contratadas directamente por el Estado." Relacione esta discusión con el papel

# Local Variables:
# ispell-dictionary: "spanish"
# End:

#  LocalWords:  Tarzán Answer Telmex Acab Chita Jane
