# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Bienes públicos: ejercicios

1. ¿Son las autopistas un bien público? ¿Es una idea razonable la
   provisión privada de autopistas?

   #+begin_answer

   #+end_answer

2. Tarzán y Jane viven en la jungla y han adiestrado a Chita para que
   patrulle los límites de su asentamiento y para que recolecte
   fruta. Chita puede recoger 3 kg de fruta por hora y
   dedica 6 horas al día a patrullar y 8 horas a recolectar fruta.

   a) Identifique si los bienes de este ejemplo son públicos o privados.

      #+begin_answer

      #+end_answer

   b) Si Tarzán y Jane están dispuestos cada uno a sacrificar una hora
      de patrulla por 2 kg de fruta, ¿es la actual asignación de horas
      patrullando y recolectando un óptimo de Pareto? ¿Debería Chita
      patrullar más horas o menos?

      #+begin_answer

      #+end_answer

3. El coste marginal de producir Q unidades de un bien público puro
   es: $\CM = 5 Q$. Existen 100 demandantes: 75 cuya demanda viene
   dada por $Q = 50 - 5 P$; y 25 con demanda es $Q = 100 - 5 P$. ¿Cuál
   sería la provisión eficiente del bien público? Represente
   gráficamente.

   #+begin_answer

   #+end_answer

4. En una ciudad hay tres tipos de personas que se distinguen
   únicamente por sus preferencias con respecto a los parques
   municipales. Cada una de las personas del primer tipo están
   dispuestas a pagar $D_{I} = \money{100}$ por la mera existencia de
   algún parque y esta disposición es independiente del número de
   parques que haya. Por otro lado, la disposición a pagar de los
   individuos de los otros dos tipos es:
   #+begin_export latex
   \begin{gather*}
     D_{II} = 200 + 30 N - 1.5 N^{2} \\
     D_{III} = 150 + 90 N - 4.5 N^{2}
   \end{gather*}
   #+end_export
   donde $N$ es el número de parques de la ciudad. Si hay 500
   individuos de cada tipo, cada parque cuesta \money{40000} y sólo se
   puede construir un número entero de parques, ¿cuántos deben de
   construirse?

   #+begin_answer

   #+end_answer

5. La curva de demanda de un bien privado viene dada por $P = 50 -
   Q$. El coste de producir una unidad adicional del bien es de
   \price{15} y no depende de la cantidad producida. Cuando el bien es
   provisto por empresas competitivas, estas tienen que afrontar unos
   costes de transacción de \price{10}. El gobierno está planteándose
   la posibilidad de proveer el bien gratuitamente, en cuyo caso no
   existirían costes de transacción. ¿Es eficiente la provisión
   privada? ¿Y la pública? ¿Cuál de las dos opciones es más
   conveniente desde el punto de vista social?

   #+begin_answer

   #+end_answer

6. La curva de costes de un monopolio natural es: $\CT(Q) =
   \num{10000} + Q$. La curva de demanda de mercado es $Q = 5150 - 50
   P$.

   a) ¿Cuál sería el precio que maximiza el beneficio de la empresa?
      Calcule la pérdida de eficiencia en esta situación.

      #+begin_answer

      #+end_answer

   b) Si el Gobierno obliga al monopolista a fijar el precio
      competitivo, ¿cuál sería el beneficio del monopolista?

      #+begin_answer

      #+end_answer

   c) Calcule el precio que debería fijar el monopolio para obtener
      beneficios nulos.

      #+begin_answer

      #+end_answer
