# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Bienes públicos: ejercicios

1. \DANGER En una pequeña ciudad sólo viven dos personas: Alba y
   Blanca. El servicio de bomberos de la ciudad se financia
   exclusivamente con su aportaciones voluntarias. Tanto Alba como
   Blanca tienen las mismas preferencias sobre su consumo de bienes
   privados, $Y_i$, y sobre el número total de bomberos contratado por
   el ayuntamiento, $N$. Estas preferencias se pueden representar por
   las funciones de utilidad:
   #+begin_export latex
   \begin{gather*}
     \text{Alba: } U_{A} = 4 \log Y_A + 2 \log N \\
     \text{Blanca: } U_{B} = 4 \log Y_{B} + 2 \log N
   \end{gather*}
   #+end_export
   El número total de bomberos es la suma de los contratados por las
   aportaciones de Ana, $N_A$, y de Blanca, $N_B$: $N = N_A +
   N_B$. Tanto Ana como Blanca disponen de una renta de \money{150} y
   los precios por unidad de $Y$ y de $N$ son iguales a \money{1}.

   a) ¿Cuántos bomberos se contratarán en estas condiciones?

      #+begin_answer

      #+end_answer

   b) ¿Cuál es el número socialmente óptimo de bomberos? Si su
      respuesta difiere de la del apartado anterior, explique por qué.

      #+begin_answer

      #+end_answer

   c) El ayuntamiento decide contratar 40 bomberos más que financia
      mediante un impuesto de \money{20} a cada habitante. ¿Cuál es
      ahora número total de bomberos contratados? ¿Se ha alcanzado el
      óptimo social? ¿Por qué?

      #+begin_answer

      #+end_answer

   d) Suponga ahora que en vez de tener que financiar con impuestos
      los 40 bomberos que contrata el ayuntamiento, un misterioso
      benefactor se hace cargo de los gastos adicionales. ¿Se obtienen
      en este caso los mismos resultados que en el apartado anterior?

      #+begin_answer

      #+end_answer
