#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit05}}}: ejercicios


* Q.1

Un avión se estrella en el Océano Pacífico. Los dos únicos
supervivientes consiguen ponerse a salvo en una isla desierta donde
no hay nada que comer. En la playa encuentran, entre los restos del
accidente, una caja que contiene \num{1000} bolsitas de
cacahuetes.

a) Encuentre las posibles asignaciones de las bolsas de cacahuetes
   entre los dos supervivientes que sean óptimas en el sentido de
   Pareto. ¿Cuáles de estas asignaciones son justas?

b) Suponga que la función de utilidad de cada superviviente es $U(N_i)
   = N_i$, donde $N_i$ es el número de bolsitas de cacahuetes que
   obtiene el superviviente $i$, $i = 1, 2$.  ¿Cuál sería el reparto
   óptimo si se usa una función de bienestar utilitarista? ¿Y si se
   usa una función de bienestar rawlsiana?

c) ¿Cómo cambiarían sus respuestas al apartado anterior si la función
   de utilidad de cada superviviente fuera $U(N_i) = \log N_i$? ¿Por
   qué se obtienen repartos diferentes con esta función de utilidad?

** Answer

a) Si la utilidad de cada superviviente es creciente en el número de
   bolsitas que recibe, sería un óptimo de Pareto cualquier reparto
   que asigne las $1000$ bolsitas sin que se pierda ninguna. Si, por
   ejemplo, un superviviente obtiene $100$ bolsitas y el otro recibe
   $900$, no es posible mejorar la situación de uno sin empeorar la
   del otro.

   En cuanto a la justicia del reparto, el criterio de Pareto no
   permite evaluar qué asignaciones son justas o no, pues ello
   requiere introducir juicios de valor adicionales.

b) La función de bienestar social utilitarista es:
   #+begin_export latex
   \[
     W_U = U_A(N_A) + U_B(N_B) = N_A + N_B.
   \]
   #+end_export
   Sólo consideramos asignaciones eficientes, por lo que:
   #+begin_export latex
   \[
     N_A + N_B = 1000.
   \]
   #+end_export
   Las dos expresiones anteriores implican que, sea cual sea la
   asignación eficiente que se escoja, el valor de la función de
   bienestar social va a ser el mismo: $W_U = N_A + N_B = 1000$. En
   este caso, el criterio utilitarista implica que todas las
   asignaciones eficientes son igualmente preferibles.
   #+latex: \vspace*{1ex}

   La función de bienestar rawlsiana es:
   #+begin_export latex
   \[
     W_R = \min\{N_A, N_B\}.
   \]
   #+end_export
   Con esta función no puede ser óptima ninguna asignación donde los
   individuos reciban un número diferente de bolsitas, ya que se
   podría incrementar el bienestar social transfiriendo bolsitas del
   superviviente que tiene más al que tiene menos. Por tanto, la
   asignación socialmente óptima se caracteriza por $N_A = N_B$. Esta
   condición junto con la condición de eficiencia, $N_A + N_B = 1000$,
   permite obtener el reparto óptimo: $N_A = N_B = 500$.

c) En este caso, la función de bienestar utilitarista es:
   #+begin_export latex
   \[
     W_U = \log N_A + \log N_B.
   \]
   #+end_export
   El óptimo social se obtiene maximizando esta función sujeta a la
   restricción que define la condición de eficiencia:
   #+begin_export latex
   \[
     N_A + N_B = 1000.
   \]
   #+end_export
   Sustituyendo la condición de eficiencia en la función de bienestar
   social, se obtiene:
   #+begin_export latex
   \[
     W_U = \log N_A + \log (1000 - N_A).
   \]
   #+end_export
   La condición de primer orden requiere que la derivada de la
   expresión anterior sea igual a $0$:
   #+begin_export latex
   \[
     \frac{\diff W_u}{\diff N_A} =
     \frac{1}{N_A} - \frac{1}{1000 - N_A} = 0.
   \]
   #+end_export
   Resolviendo la ecuación anterior, se obtiene $N_A = 500$. Por
   tanto, la asignación óptima es $N_A = N_B = 500$.
   #+latex: \vspace*{1ex}

   La función de bienestar rawlsiana es:
   #+begin_export latex
   \[
     W_R = \min\{\log N_A, \log N_B\}.
   \]
   #+end_export
   En el óptimo social se debe cumplir $\log N_A = \log N_B$, por lo
   que $N_A = N_B$. Esta condición y la de eficiencia implican que el
   reparto óptimo es $N_A = N_B = 500$.
   #+latex: \vspace*{1ex}

   En el caso de la función de bienestar utilitarista, el reparto
   óptimo es diferente al del apartado anterior porque la utilidad
   marginal es decreciente. Esto hace que se otorgue más peso relativo
   a los individuos con menos recursos y se favorezca un reparto más
   igualitario.
   #+latex: \vspace*{1ex}

   Por otro lado, los resultados no cambian con el criterio rawlsiano:
   cualquier función de utilidad que sea creciente en el número de
   bolsitas producirá el mismo reparto óptimo.


* Q.2

Se está considerando la implantación de un programa público que
elevaría ligeramente el bienestar de los ciudadanos más pobres pero
disminuiría considerablemente el bienestar del resto de
ciudadanos. ¿Sería aconsejable este programa desde el punto de vista
del criterio utilitarista?  ¿Y si se utilizara el criterio
/rawlsiano/?

** Answer

Desde el punto de vista utilitarista, el programa sólo se debería
llevar a cabo si la mejora agregada del bienestar de los más pobres
supera la pérdida total del resto de la población.
#+latex: \vspace*{1ex}

El criterio rawlsiano favorecería la implantación del programa siempre
que aumente el bienestar del individuo en peor situación,
independientemente de las pérdidas o ganancias de bienestar del resto
de ciudadanos.


* Q.3

Suponga que sólo hay dos consumidores, Aurelio y Beatriz, los cuales
deben repartirse una renta fija de \money{100}. En el caso de
Aurelio, la utilidad marginal de la renta es $\UMgY_A = 400 - 2 Y_A$, y
en el caso de Beatriz es $\UMgY_B = 400 - 6 Y_B$, siendo $Y_A$ e $Y_B$
la renta que obtiene Aurelio y Beatriz respectivamente.

a) ¿Cuál es la distribución óptima de la renta si la función de
   bienestar social es la utilitarista?

b) ¿Cuál es la distribución óptima si la sociedad sólo valora la
   utilidad de Beatriz? ¿Y si sólo valorase la utilidad de Aurelio?

c) Responda a los apartados anteriores suponiendo ahora que la
   utilidad marginal de la renta de ambos consumidores es igual a una
   constante: $\UMgY_A = \UMgY_B = 400$.

** Answer

a) La maximización de la suma de las utilidades de los consumidores,
   implica que se igualan sus utilidades marginales:
   #+begin_export latex
   \[
     400 - 2Y_A = 400 - 6Y_B.
   \]
   #+end_export
   De esta expresión se obtiene:
   #+begin_export latex
   \[
     Y_A = 3Y_B
   \]
   #+end_export
   Dado que $Y_A + Y_B = 100$, el reparto óptimo es:
   #+begin_export latex
   \[
   Y_A = \money{75},\quad Y_B = \money{25}.
   \]
   #+end_export

b) Si solo se valora la utilidad de Beatriz y se le asignan los
   \money{100} su utilidad marginal sería negativa:
   #+begin_export latex
   \[
     \UMgY_B(100) = 400 - 6 \cdot 100 = -200.
   \]
   #+end_export
   La utilidad de Beatriz aumentaría si recibiera menos dinero. En
   concreto, su utilidad se maximizaría cuando $\UMgY_B = 0$:
   #+begin_export latex
   \[
      400 - 6 Y_B = 0,
   \]
   #+end_export
   por lo que la asignación óptima sería $Y_A = \money{33.33}$ e $Y_B
   = \money{66.67}$.
   #+latex: \vspace*{1ex}

   En cambio, si solo se valora la utilidad de Aurelio, éste debería
   recibir los \money{100}. En este caso: $\UMgY_A(100) > 0$, por lo
   que el reparto óptimo sería $Y_A = \money{100}$ e $Y_B =
   \money{0}$.

c) Cuando las utilidades marginales de la renta son constantes, todas
   las asignaciones son igualmente preferibles desde el punto de vista
   utilitarista.
   #+latex: \vspace*{1ex}

   Si la sociedad solo valorase la utilidad de uno de los
   consumidores, ese consumidor debería recibir la totalidad de los
   \money{100}.

* Q.4

Considere un programa por el que se transfiera renta de ciudadanos
pertenecientes a la clase media a ciudadanos tanto pobres como
ricos. ¿Apoyaría un /rawlsiano/ esa redistribución? ¿Y un
utilitarista?

** Answer

Si la función de utilidad es la misma para todos los individuos y es
creciente en la renta, un rawlsiano apoyaría la medida siempre que
mejore el individuo más pobre, sin tener en consideración las pérdidas
o ganancias de utilidad del resto de ciudadanos.
#+latex: \vspace*{1ex}

Un utilitarista solo apoyaría el programa si la suma de las ganancias
totales de pobres y ricos superase la pérdida agregada de los
ciudadanos de clase media.


* Q.5

Discuta la veracidad de las siguientes afirmaciones sobre una economía
con dos consumidores:

a) Si la función de bienestar social es utilitarista, $W = U_1 + U_2$,
   la sociedad se muestra indiferente entre dar \money{1} a un
   consumidor o al otro.

b) Una función de bienestar social como $W = U_1 + 8 U_2$ valora más
   la felicidad del consumidor 2 que la del consumidor 1.

c) Si la función de bienestar social es $W = \min\{U_1, U_2\}$, la
   distribución de la renta óptima es completamente igualitaria.

** Answer

a) La afirmación sólo sería cierta si la utilidad marginal de la renta
   fuera igual para ambos consumidores. En general, el criterio
   utilitarista favorecería asignar \money{1} al individuo con mayor
   utilidad marginal.

b) La afirmación es cierta ya que la utilidad del consumidor 2 tiene
   un peso mayor en la función de bienestar social.

c) Falso en general. El criterio rawlsiano iguala utilidades, no
   rentas. Solo si las funciones de utilidad son idénticas se obtiene
   una distribución igualitaria de la renta.


* Q.6

Analice la veracidad o falsedad de las siguientes afirmaciones:

a) La aplicación del criterio /rawlsiano/ conduce necesariamente a una
   distribución igualitaria de la renta.

b) Dada una curva de posibilidades de utilidad para dos individuos, la
   aplicación del criterio utilitarista llevará siempre a una
   distribución menos igualitaria que la del criterio /rawlsiano/.

** Answer

a) /Falso/. La aplicación del criterio rawlsiano lleva a la igualación
   de las utilidades, no de las rentas. Si las funciones de utilidad
   difieren, la distribución óptima de la renta no será igualitaria.

b) /Falso/. Bajo ciertas condiciones el utilitarismo genera
   distribuciones tan igualitarias como las obtenidas bajo el punto de
   vista rawlsiano. Si los consumidores tienen funciones de utilidad
   idénticas y la utilidad marginal de la renta es decreciente, el
   criterio utilitarista y el rawlsiano producen los mismos
   resultados.





* COMMENT Q.7

En un país sólo viven dos ciudadanos: Blanca y Teo. Blanca es
abogada y gana \money{50} por hora. Cuando la tasa impositiva sobre
la renta es $t = \SI{0}{\percent}$, Blanca trabaja 20 horas a la
semana; si $t = \SI{25}{\percent}$, trabajaría 16 horas; y si $t =
\SI{40}{\percent}$ sólo trabajaría 8 horas. Teo trabaja en un
pequeño taller de reparaciones y gana \money{6} por hora. Teo
siempre trabaja 20 horas por semana sea cual sea la tasa
impositiva. El gobierno está pensando en gravar la renta de Blanca
y transferir la recaudación a Teo.

a) Blanca y Teo tienen la misma función de utilidad: $U_B(Y) = U_T(Y)
   = Y^{1/2}$ donde $Y$ es la renta semanal después de impuestos y
   transferencias. ¿Cuál de las tres tasas impositivas sería óptima
   desde un punto de vista utilitarista? ¿Y si se utiliza una función
   de bienestar social /rawlsiana/?

b) ¿Cambiarían las conclusiones del apartado anterior si las funciones
   de utilidad fueran $U_B(Y) = U_T(Y) = Y^{1/5}$?.

c) Suponga ahora que Blanca y Teo tienen funciones de utilidad
   diferentes. La utilidad de Blanca es $U_B(Y) = 0.25 Y^{1/2}$ y la
   de Teo es $U_T(Y) = Y^{1/2}$. La diferencia es debida a que Blanca
   sufre una discapacidad por lo que necesita más renta para alcanzar
   el mismo nivel de utilidad. ¿Cómo ordenarían ahora las diferentes
   alternativas los criterios utilitarista y /rawlsiano/?

** Answer

Por hacer


* COMMENT Q.7

El gobierno de un país quiere fomentar la producción de aceite de
oliva. Para ello establece un impuesto adicional a los consumidores
sobre la compra de aceites de semillas. ¿Es esta medida compatible
con una asignación de recursos eficiente en el sentido de Pareto?

** Answer

Por hacer


* COMMENT Q.15

\DDANGER Considere una economía pura de intercambio con dos
consumidores $A$ y $B$ y dos bienes $X$ e $Y$. Las preferencias vienen
dadas por:
#+begin_export latex
\begin{gather*}
  U_{A}(X_{A}, Y_{A}) = X_{A}^{1/4} Y_{A}^{1/4} \\
  U_{B}(X_{B}, Y_{B}) = X_{B}^{1/4} Y_{B}^{1/4}
\end{gather*}
#+end_export
Las dotaciones iniciales de los consumidores son:
#+begin_export latex
\begin{gather*}
  \Xbar_{A} = 20; \quad \Ybar_{A} = 60. \\
  \Xbar_{B} = 80; \quad \Ybar_{B} = 40.
\end{gather*}
#+end_export

a) ¿Es la dotación inicial Pareto eficiente?

b) Calcule la curva de contrato.

c) Considere ahora que se instituyen mercados competitivos para
   asignar los bienes de consumo. ¿Se alcanza el equilibrio
   competitivo si los precios son $P_X = 2$ y $P_Y = 1$? Si su
   respuesta es negativa, calcule los precios del equilibrio
   competitivo. ¿Es eficiente la asignación de mercado?


* COMMENT Q.14

\DANGER Una economía está compuesta por dos individuos: $A$ y
$B$. $A$ dispone de un factor de producción que puede usar para
producir un bien de consumo $X$. $B$ no posee ninguna unidad del
factor de producción y, por tanto, no puede producir nada. Para
paliar esta situación el gobierno puede transferir a $B$ una
fracción $t$ de la producción de $A$. La producción de $A$ depende
de $t$ mediante la siguiente función:
#+begin_export latex
\[
  X(t) = 167 (1 - t) (t + 0.6)
\]
#+end_export
Suponiendo que la utilidad de ambos individuos es igual a la
cantidad que consumen del bien $X$, determinar qué fracción debería
$t$ debería establecerse de acuerdo a un criterio:

a) utilitarista.

b) /rawlsiano/.

c) igualitarista.


* COMMENT Q.1

Imagine una economía donde sólo habitan dos consumidores, Aurora y Bernardo.

a) Si la función de bienestar social es:
   #+begin_export latex
   \[ W_1 = U_A + U_B \]
   #+end_export
   donde $U_A$ y $U_B$ son las utilidades de Aurora y Bernardo,
   respectivamente. Dibuje las curvas de indiferencia social. ¿Cómo
   describiría la importancia relativa que se asigna a cada
   utilidad?

b) ¿Cómo cambiaría su respuesta al apartado anterior si la función
   de bienestar social fuera $W_2 = U_A + 2 U_B$?

c) ¿Y si fuera $W_3 = \min\{U_A, U_B\}$?

d) Suponga que la función de posibilidades de utilidad es:
   #+xxx: fig file:fig-04_1047-01-*.pdf
   Muestre gráficamente como difieren las soluciones óptimas para
   las funciones de bienestar social de los apartados anteriores.

** Answer

Por hacer


* COMMENT Q.11

¿Es posible encontrar una situación en la que que el óptimo social de
acuerdo a una función de bienestar /rawlsiana/ coincida con el que se
obtendría con una función de bienestar utilitarista?  Represente
gráficamente.


* COMMENT Q.12

Considere una economía con dos individuos $A$ y $B$. La tabla
siguiente muestra algunas combinaciones de utilidad que se
encuentran sobre la frontera de posibilidades de utilidad:

#+begin_export latex
\begin{center}
  \begin{tabular}{>{$}l<{$}*{2}{>{$}r<{$}}}
    \toprule
    \text{Opción} & U_A & U_B \\
    \midrule
    M & 100 &  0 \\
    N &  90 & 20 \\
    O &  60 & 30 \\
    P &  30 & 30 \\
    Q &  40 & 60 \\
    R &  10 & 70 \\
  \bottomrule
\end{tabular}
\end{center}
#+end_export

Indique cuál será la opción elegida de acuerdo con:

a) el criterio utilitarista.

b) el criterio igualitarista.

c) el criterio /rawlsiano/.



# Local Variables:
# ispell-local-dictionary: "spanish"
# End:

#  LocalWords:  rawlsiano Answer Pareto Teo rawlsiana
