# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Análisis coste-beneficio: ejercicios

1. Considere un proyecto que cueste \money{100000} este año y produzca
   unos ingresos de \money{30000} durante los 5 años siguientes. Al
   final del último año habría que soportar un coste de limpieza por
   valor de \money{20000}. ¿Debería llevarse a cabo el proyecto si la
   tasa de descuento es 0? ¿Y si fuera del 10%? ¿15%?

   #+begin_answer

   #+end_answer

2. El doctor Jones está decidiendo dónde ir en sus próximas
   vacaciones. Si se decide a visitar el país $A$, el riesgo de morir
   es de 1 entre \num{10000} y estaría dispuesto a pagar hasta
   \money{6000}. Si se decide por el país $B$ el riesgo de muerte es
   de 1 entre \num{20000} y su disposición a pagar sería de
   \money{9000}. Si el doctor Jones se muestra indiferente entre los
   dos destinos salvo por el diferencial de riesgo de muerte, ¿qué se
   puede inferir acerca de cómo valora su propia vida?

   #+begin_answer

   #+end_answer

3. Una consultora elaboró por encargo de un gobierno un análisis
   coste-beneficio de una serie de limitaciones legales a fumar en
   público. El informe señalaba que fumar tiene un beneficio neto
   positivo porque el tabaco causa muertes prematuras con el
   consiguiente ahorro para el sistema sanitario, por un lado, y el
   sistema de pensiones, por otro. Discuta.

   #+begin_answer

   #+end_answer

4. Un artículo periodístico sobre los costes y los beneficios de
   reciclar en Nueva York, señalaba como beneficio principal la
   creación de 1000 puestos de trabajo en el sector privado
   relacionados directa o indirectamente con el reciclaje. Discuta.

   #+begin_answer

   #+end_answer

5. Un gobierno está planteando la posibilidad de gastar ahora
   \num{10000} millones de euros para reducir los daños que el cambio
   climático causaría dentro de 100 años.  Se estima que el proyecto
   conseguiría evitar daños por valor de \num{80000} millones de
   euros. Un miembro del parlamento, muy crítico con el gobierno,
   propone invertir los \num{10000} millones de euros en el mercado de
   valores para obtener una tasa de rendimiento media de un 6% y usar
   los resultados de esa inversión para reparar dentro de 100 años los
   daños causados por el cambio climático. Discuta.

   #+begin_answer

   #+end_answer
