#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit08}}}: ejercicios

* Q.1

Considere un programa de formación dirigido a trabajadores
desempleados. El programa tiene una duración de un año y se estima que
los 200 participantes verán incrementados sus ingresos en \money{1000}
al año durante los 10 años posteriores. El total de los
salarios que perciben los formadores asciende a \money{1400000}. Los
costes de materiales y suministros suponen \money{1000} por cada
participante. Calcule el valor actual neto del programa de formación
para las siguientes tasas de descuento: 0%, 1%, 3%, 5% y 10%. ¿Para
qué tasas de descuento sería viable el programa?

** Answer

Cada uno de los $200$ participantes gana \money{1000} más al año
durante $10$ años, así que el beneficio anual total es: $B = 200\cdot
1000= \money{200000}$. Los costes del programa se corresponden a los
salarios de los formadores, \money{1400000}, y al valor de los
materiales: $200 \cdot 1000 = \money{200000}$. Por tanto, el coste
total inicial es: $C_0 = \money{1600000}$. El valor actual neto es:
#+begin_export latex
\[
  VAN = -C_0 + \sum_{t=1}^{10}\frac{B}{(1+r)^t} =
  \num{-1600000} + \num{200000} \sum_{t=1}^{10}\frac{1}{(1+r)^t}.
\]
#+end_export
Cuando $r = 0$, la expresión anterior se simplifica a $VAN =
\money{400000}$. Cuando $r > 0$, la expresión anterior puede
reescribirse como:
#+begin_export latex
\[
  VAN = \num{-1600000} + \num{200000} \frac{1 - (1 + r)^{-10}}{r}
\]
#+end_export
La tabla siguiente muestra el valor actual neto para las diferentes
tasas de descuento:
#+ATTR_LATEX: :booktabs t :align rr
| $r$      | $VAN$           |
|----------+-----------------|
| \pct{0}  | \money{400000}  |
| \pct{1}  | \money{294261}  |
| \pct{3}  | \money{106041}  |
| \pct{5}  | \money{-55653}  |
| \pct{10} | \money{-371087} |
El programa sería admisible para $r = \pct{3}$ y tasas de descuento
inferiores. Para tasas de descuento iguales o superiores al \pct{5} el
valor actual neto es negativo y el proyecto no es viable.



* Q.2

Considere un proyecto que cuesta \money{100000} este año y genera
unos ingresos de \money{30000} durante los 5 años siguientes. Al
final del último año habría que incurrir en un coste de limpieza por
valor de \money{20000}.

a) ¿Debería llevarse a cabo el proyecto si la tasa de descuento es
   10%?

b) Considere que existe incertidumbre con respecto al coste de
   limpieza que puede ascender a \money{15000} o a \money{35000},
   ambas cifras con un 50% de probabilidad. Suponiendo neutralidad
   frente al riesgo, ¿debería llevarse a cabo el proyecto?


** Answer

a) Con una tasa de descuento del \pct{10} y un coste de limpieza de
   \money{20000}, el valor actual neto es:
   #+begin_export latex
   \begin{align*}
     VAN &=
           -\num{100000} +
           \num{30000} \sum_{t=1}^{5} \frac{1}{1.1^t} -
           \frac{\num{20000}}{1.1^5}\\
         &= -\num{100000}
           + \num{113723.60}
           - \num{12418.42} \\
       &= \money{1305.18}
   \end{align*}
   #+end_export
   Como el VAN es positivo, el proyecto debería llevarse a cabo.

b) El coste de limpieza es incierto: \money{15000} con probabilidad
   $0.5$ o \money{35000} con probabilidad $0.5$. El valor esperado del
   coste de limpieza es de \money{25000}.
   #+latex: \smallskip

   Al calcular el valor actual neto, se utiliza el valor esperado del
   coste de limpieza:
   #+begin_export latex
   \begin{align*}
     VAN &=
           -\num{100000} +
           \num{30000} \sum_{t=1}^{5} \frac{1}{1.1^t} -
           \frac{\num{25000}}{1.1^5}\\
         &= -\num{100000}
           + \num{113723.60}
           - \num{15523.04}\\
         &= -\money{1799.43}
   \end{align*}
   #+end_export
   Como el VAN esperado es negativo, el proyecto no debería llevarse a
   cabo.



* Q.3

Diana trata de decidir el destino de sus próximas vacaciones. Estaría
dispuesta a pagar hasta \money{6000} por viajar al país $A$ donde el
riesgo de muerte es de 1 entre \num{10000}. Por otro lado, estaría
dispuesta a pagar como mucho \money{6500} por viajar al país $B$,
donde el riesgo de muerte es de 1 entre \num{22500}. Diana es
indiferente entre ambos destinos salvo por el diferencial de riesgo de
muerte. A partir de la información proporcionada, ¿qué se puede inferir
acerca de la valoración por parte de Diana de su propia vida?


** Answer

Podemos expresar la disposición a pagar de Diana por viajar al país A,
$D_A$, como:
#+begin_export latex
\[
  D_A = T_A + (1 - p_A) V,
\]
#+end_export
donde $T_A$ es la valoración subjetiva del viaje, $p_A$ la
probabilidad de morir en el país A y $V$ es la valoración que Diana
hace de su propia vida si sobrevive al viaje. De forma similar,
expresamos la disposición a pagar por viajar al país B:
#+begin_export latex
\[
  D_B = T_B + (1 - p_B) V.
\]
#+end_export
Restando estas dos ecuaciones:
#+begin_export latex
\[
  D_B - D_A = T_B  - T_A + (1 - p_B) V - (1 - p_A) V.
\]
#+end_export
Dado que la única diferencia en la valoración de los viajes se debe a
la probabilidad de morir, se sigue que $T_B = T_A$. Por tanto:
#+begin_export latex
\[
  D_B - D_A = (p_A - p_B) V.
\]
#+end_export
Despejando $V$ en la expresión anterior, se obtiene:
#+begin_export latex
\[
  V = (D_B - D_A) / (p_A - p_B).
\]
#+end_export
Finalmente:
#+begin_export latex
\[
  V = (\num{6500} - \num{6000}) / (1/\num{10000} - 1/\num{22500}) =
  \money{9000000}.
\]
#+end_export
Se puede concluir que Diana valora implícitamente su vida en 9
millones de euros.




* Q.4

Las autoridades de Tierra Media están considerando la posibilidad
de construir un puente que mejore la conexión por carretera de dos
ciudades separadas por un río.

Actualmente, solo se puede cruzar el río con un ferry que transporta
\num{25000} vehículos por año. La empresa que opera el ferry es un
monopolio que cobra un peaje de \money{2} por vehículo y trayecto y
soporta unos costes de \money{1.5} por vehículo y trayecto. El número
de vehículos que cruzarían el río cada año viene dado por la curva de
demanda: $q = \num{125000} - \num{50000} p$ donde $p$ es el peaje por
cruzar el río.

Se tardaría un año en construir el puente y los costes ascenderían a
1 millón de euros. Una vez en funcionamiento, los costes de
mantenimiento del puente serían de \money{50000} por año. Se estima
que el tiempo de viaje entre las dos ciudades sería aproximadamente el
mismo que con el ferry. Si se construye el puente, no se cobraría
ningún peaje por cruzar el puente. En consecuencia, el servicio de
ferry desaparecería.

a) Determine si se debería construir el puente suponiendo una tasa
   de descuento del 10% y que el puente tiene una duración
   infinita.

b) ¿Cambiaría su respuesta al apartado anterior si se cobrara un
   peaje de \money{0.40} por trayecto?


** Answer

a) El precio máximo que algún consumidor estaría dispuesto a pagar por
   cruzar el río es \money{2.5}, que se obtiene de la curva de demanda
   cuando $q=0$.
   #+latex: \smallskip

   Si no se construye el puente, el bienestar social anual está compuesto por el excedente de los conductores y el beneficio del monopolio. El excedente de los consumidores es el área entre la curva de demanda y el precio del ferry:
   #+begin_export latex
   \[
     EC_0 = (2.5 - 2)\cdot \num{25000} / 2 = \money{6250}.
   \]
   #+end_export
   Por otro lado, los beneficios del monopolio son:
   #+begin_export latex
   \[
     \Pi_0 = (2 - 1.5)\cdot \num{25000} = \money{12500}.
   \]
   #+end_export
   Por tanto, el bienestar social anual inicial es:
   #+begin_export latex
   \[
     W_0 = \num{6250} + \num{12500} = \money{18750}.
   \]
   #+end_export
   #+latex: \smallskip

   Si se construye el puente y no se cobra peaje, entonces $p=0$ y $q
   = \num{125000}$ trayectos. El excedente de los conductores pasa a
   ser:
   #+begin_export latex
   \[
     EC_1 = 2.5 \cdot \num{125000} / 2 = \money{156250}.
   \]
   #+end_export
   El monopolio deja de operar y el mantenimiento anual del puente
   cuesta \money{50000}, así que el bienestar social anual con puente es:
   #+begin_export latex
   \[
     W_1 = \num{156250} - \num{50000} = \money{106250}.
   \]
   #+end_export
   La ganancia anual neta respecto a la situación inicial es:
   #+begin_export latex
   \[
     W_1 - W_0 = \num{106250} - \num{18750} = \money{87500}.
   \]
   #+end_export
   El valor actual neto del puente con una tasa de descuento del
   \pct{10} y duración infinita es:
   #+begin_export latex
   \[
     VAN =
     -\num{1000000} + \frac{1}{1.1}\frac{\num{87500}}{0.1} =
     -\money{204545.45},
   \]
   #+end_export
   donde se ha tenido en cuenta que los costes de construcción se
   pagan en el año inicial y los rendimientos netos anuales no se
   obtienen hasta que se haya construido el puente, un año más tarde.
   Como el VAN es negativo, no debería construirse el puente.

b) Cuando se cobra un peaje de \money{0.40} por trayecto, la cantidad
   demandada será:
   #+begin_export latex
   \[
     q = \num{125000} - \num{50000} \cdot 0.4 = \text{\num{105000} trayectos},
   \]
   #+end_export
   y los ingresos obtenidos con los peajes ascienden a $0.4 \cdot
   \num{105000} = \num{42000}$ euros.

   El excedente de los conductores es:
   #+begin_export latex
   \[
     EC_2 = (2.5 - 0.4) \num{105000} / 2 = \money{110250}.
   \]
   #+end_export
   El bienestar social anual es la suma del excedente de los
   conductores y los ingresos por peajes menos los costes de
   mantenimiento:
   #+begin_export latex
   \[
     W_2 = \num{110250} + \num{42000} - \num{50000} = \money{102250}.
   \]
   #+end_export
   La ganancia anual neta con respecto a la situación inicial es:
   #+begin_export latex
   \[
     W_2 - W_0 = \num{102250} - \num{18750} = \money{83500}.
   \]
   #+end_export
   El valor actual neto del puente cuando se cobra peaje es:
   #+begin_export latex
   \[
     VAN =
     -\num{1000000} + \frac{1}{1.1} \frac{\num{83500}}{0.1} =
     -\money{240909.09}.
   \]
   #+end_export

   El VAN es incluso más negativo cuando se cobra un peaje. Tampoco
   debería construirse el puente en este caso.


** COMMENT Answer

La demanda anual de cruces viene dada por:

\[
q = 125000 - 50000p
\]

donde $p$ es el peaje por trayecto.

Actualmente, el ferry cobra un peaje de 2 € y transporta:

\[
q = 125000 - 50000 \times 2 = 25000
\]

vehículos al año.

El coste marginal del ferry es 1.5 € por vehículo.

*** Situación actual: ferry

El precio máximo que algún consumidor estaría dispuesto a pagar es
2.5 €, obtenido al imponer $q=0$.

El excedente del consumidor es:

\[
EC_0 =
\frac{1}{2}(2.5 - 2)\times 25000
= 6250
\]

Los beneficios del monopolio son:

\[
\Pi_0 =
(2 - 1.5)\times 25000
= 12500
\]

Por tanto, el bienestar social anual inicial es:

\[
W_0 = 6250 + 12500 = 18750
\]

*** Apartado a

Si se construye el puente y no se cobra peaje, entonces $p=0$ y:

\[
q = 125000
\]

El excedente del consumidor pasa a ser:

\[
EC_1 =
\frac{1}{2}(2.5 - 0)\times 125000
= 156250
\]

El mantenimiento anual del puente cuesta 50000 €, así que el
bienestar social anual con puente es:

\[
W_1 = 156250 - 50000 = 106250
\]

La ganancia anual neta respecto a la situación inicial es:

\[
\Delta W =
106250 - 18750
= 87500
\]

Con una tasa de descuento del \pct{10} y duración infinita, el valor
actual de esta ganancia es:

\[
VA =
\frac{87500}{0.1}
= 875000
\]

El coste de construcción del puente es 1 millón de euros, por lo que:

\[
VAN =
-1000000 + 875000
= -125000
\]

Como el VAN es negativo, no debería construirse el puente.

*** Apartado b

Ahora se cobra un peaje de 0.40 € por trayecto.

La cantidad demandada será:

\[
q =
125000 - 50000 \times 0.4
= 105000
\]

El excedente del consumidor es:

\[
EC_2 =
\frac{1}{2}(2.5 - 0.4)\times 105000
= 110250
\]

Los ingresos anuales por peaje son:

\[
I = 0.4 \times 105000 = 42000
\]

El bienestar social anual pasa a ser:

\[
W_2 =
110250 + 42000 - 50000
= 102250
\]

La ganancia anual respecto a la situación inicial es:

\[
\Delta W =
102250 - 18750
= 83500
\]

El valor actual de esta ganancia es:

\[
VA =
\frac{83500}{0.1}
= 835000
\]

Entonces:

\[
VAN =
-1000000 + 835000
= -165000
\]

Como el VAN sigue siendo negativo, tampoco debería construirse el
puente en este caso.


* COMMENT Q.3

Un artículo periodístico enumeraba los costes y los beneficios de
un nuevo programa de fomento del reciclaje en la ciudad de
Springfield. El reportero destacaba como principal beneficio la
creación de 100 puestos de trabajo relacionados directa o
indirectamente con el reciclaje. Discuta.


** Answer

Por hacer.



* COMMENT Q.1

Un ayuntamiento debe de elegir entre dos proyectos cuya duración es
menor de un año. Un consultor financiero ha calculado a cuanto
ascenderían los costes y beneficios de ambos proyectos:

#+begin_center
#+attr_latex: :booktabs :center :align lp{0.5cm}rp{0.5cm}r
|------------+---+--------------+---+--------------|
|            |   |   Beneficios |   |       Costes |
|            |   | (miles de €) |   | (miles de €) |
|------------+---+--------------+---+--------------|
| Proyecto 1 |   |          100 |   |           60 |
| Proyecto 2 |   |           21 |   |           10 |
|------------+---+--------------+---+--------------|
#+end_center

El consultor recomienda que se seleccione el proyecto con un mayor
ratio beneficio-coste. De acuerdo con ese criterio, ¿qué proyecto
sería preferible? ¿Está de acuerdo con esa recomendación?


** Answer

Por hacer.

# Local Variables:
# ispell-dictionary: "spanish"
# End:

#  LocalWords:  Answer
