#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit07}}}: ejercicios


* Q.1

Indique cuáles de las siguientes afirmaciones son verdaderas,
falsas o inciertas, y explique por qué.

a) Si tu consumo de tabaco produce externalidades negativas a tus
   compañeros de piso (las cuáles ignoras por completo), entonces
   estás fumando más de los que sería eficiente.

b) Un impuesto sobre el tabaco hace que el mercado de cigarrillos
   funcione más eficientemente.

c) La prohibición del tabaco puede justificarse por razones de eficiencia.

d) La producción en un mercado competitivo con una externalidad
   negativa (sea del tipo que sea) es mayor que la producción
   socialmente óptima.


** Answer

a) /Verdadera/: una externalidad negativa de consumo implica que se
   consume más de lo socialmente óptimo.

b) /Incierta/: un impuesto reduce las ventas de cigarrillos, por lo
   que la ineficiencia asociada a los efectos externos disminuye o
   desaparece por completo. Pero un impuesto muy elevado podría
   reducir las ventas por debajo del nivel óptimo y generar una
   ineficiencia mayor.

c) /Falsa/: la presencia de externalidades negativas no implica que la
   cantidad socialmente óptima sea $0$. La prohibición reduciría la
   utilidad de los fumadores y eliminaría los beneficios de los
   productores de tabaco. Por otro lado, aumentaría la utilidad de los
   fumadores pasivos y los beneficios de los productores de
   sustitutivos del tabaco. A priori, no es posible saber si los
   beneficios de la prohibición serán mayores que sus costes.

d) /Verdadera/: los agentes que generan las externalidades negativas
   no las tienen en cuenta y producen o consumen una cantidad superior
   a la socialmente óptima.


* Q.2

En un pueblo pesquero las capturas mensuales totales de pescado, $Q$
(medidas en kg), dependen del número de barcas que faenan, $N$:
#+begin_export latex
\begin{equation*}
  Q = \num{1000} N^{1/2}.
\end{equation*}
#+end_export
Todas las barcas son idénticas y capturan la misma cantidad de pescado:
#+begin_export latex
\begin{equation*}
  q_i = Q / N.
\end{equation*}
#+end_export
Los costes mensuales de operar cada barca son de $c_i = \money{1000}$
al mes. El pescado se vende en un mercado competitivo a un precio de
$P = \price[kg]{6}$.  Inicialmente no hay ningún tipo de limitación al
número de barcas que operan en el pueblo.

a) Suponga que operan $16$ barcas. ¿Qué beneficios obtiene cada
   barca?

b) Si una barca más empieza a pescar, calcule el efecto externo que
   tienen que soportar los pescadores que ya estaban operando.

c) Calcule el número de barcas de equilibrio.

d) Calcule el número de barcas socialmente óptimo.

e) El ayuntamiento está considerando la posibilidad de introducir un
   sistema de licencias. ¿Qué precio debería fijar para cada licencia
   si quiere conseguir que opere el número socialmente óptimo de
   barcas?


** Answer

a) Cuando $N = 16$, cada barca produce:
   #+begin_export latex
   \[
     q_i = 1000 / 16^{1/2} = \units[kg]{250}.
   \]
   #+end_export
   Los beneficios de cada pescador son:
   #+begin_export latex
   \[
     \pi_i = P q_i - c_i = 6 \cdot 250 - 1000 = \money{500}.
   \]
   #+end_export

b) Si entra una nueva barca, la producción de cada barca es:
   #+begin_export latex
   \[
     q_i = 1000 / 17^{1/2} \approx \units[kg]{242.54}.
   \]
   #+end_export
   La producción de las 16 barcas que operaban antes se reduce:
   #+begin_export latex
   \[
     \Delta q_i = 242.54 - 250 = \units[kg]{-7.46}.
   \]
   #+end_export
   En consecuencia, disminuye el beneficio de cada uno de los
   pescadores que faenaban antes de la entrada:
   #+begin_export latex
   \[
     \Delta \pi_i = P \Delta q_i = \money{-44.76}.
   \]
   #+end_export
   El efecto externo total sería la suma de la pérdida de beneficios:
   $16 \cdot (-44.76) = \money{-716,16}$.

c) Si no hay restricciones a la entrada, entrarán nuevos pescadores
   mientras consigan beneficios positivos. En el equilibrio a largo
   plazo $\pi_i = 0$ y el número de barcas sería:
   #+begin_export latex
   \[
     6 \cdot 1000 / N^{1/2} - 1000 = 0
   \]
   #+end_export
   La ecuación anterior se satisface cuando $N = 36\,\text{barcas}$.

d) El número socialmente óptimo de barcas es el que maximiza el
   beneficio total de los pescadores:
   #+begin_export latex
   \[
     \max_{\{N\}} N \pi_i =
     N \big(6 \cdot 1000 / N^{1/2} - 1000\big) =
     6000 N^{1/2} - 1000 N.
   \]
   #+end_export
   Condición de primer orden:
   #+begin_export latex
   \[
      \frac{\diff N \pi_i}{\diff N} = 3000 N^{-1/2} - 1000 = 0.
   \]
   #+end_export
   Resolviendo la ecuación anterior, se obtiene que el número
   eficiente de barcas es $N = 9\,\text{barcas}$.

e) La licencia debería desincentivar la entrada de más de 9
   barcas. Cuando $N = 9$ los beneficios individuales son:
   #+begin_export latex
   \[
     6 \cdot 1000 / 9^{1/2} - 1000 = \money{1000}
   \]
   #+end_export
   El ayuntamiento debería cobrar \money{1000} por cada licencia
   (teniendo en cuenta que $N$ es un entero, bastaría con que cobrase
   \money{898} por licencia).

* Q.3

Groucho y Harpo comparten camarote en un crucero. A Groucho le encanta
fumar sus puros durante la travesía. Harpo detesta los puros de
Groucho. La utilidad de los dos viajeros viene dada por las funciones:
#+begin_export latex
\begin{gather*}
U_G = 100 + 4 c - 0.1 c^2,
\intertext{y}
U_H = 100 - 10 c,
\end{gather*}
#+end_export
donde $c$ es el número de puros que fuma Groucho durante la travesía,
y $U_G$ y $U_H$ son las utilidades (medidas en euros) de Groucho y de
Harpo, respectivamente.

a) Si Groucho ignora las enérgicas protestas de su compañero de
   camarote y fuma todo lo que le apetece, ¿cuál será el valor de $c$?
   ¿Qué valores toman $U_G$ y $U_H$ en este caso?

b) ¿Es eficiente la solución anterior? Calcule el valor de $c$ que
   maximiza la función de bienestar $W = U_G + U_H$? ¿Qué valores
   toman $U_G$ y $U_H$ en este caso?

c) Chico, el capitán del barco, es un gran admirador de los trabajos
   de Coase y decide asignar a Groucho la capacidad de prohibir o no
   que se fume en el camarote. Si se establece una negociación entre
   Groucho y Harpo, ¿cuál sería el acuerdo que se alcanzaría?

c) Describa cómo cambiaría su respuesta al apartado anterior si Chico
   hubiese asignado a Harpo la capacidad de prohibir fumar en el
   camarote.


** Answer

a) La maximización de la utilidad de Groucho implica:
   #+begin_export latex
   \[
      \frac{\partial U_G}{\partial c} = 4 - 0.2 c = 0.
   \]
   #+end_export
   Groucho maximizaría su utilidad si fumara $20\,\text{puros}$.

b) La función de bienestar social es:
   #+begin_export latex
   \[
     W = U_G + U_H = 200 - 6 c -0.1 c^2.
   \]
   #+end_export
   Dado que $W$ es decreciente en $c$, el valor eficiente de $c$ es
   $0$. Las utilidades individuales serían: $U_G(0) = \money{100}$ y
   $U_H(0) = \money{100}$.

c) Cuando fuma, Groucho obtiene una utilidad equivalente a $U_G(20) =
   \money{140}$. Si no fuma su utilidad sería igual a $U_G(0) =
   \money{100}$. Estaría dispuesto a no fumar si se le compensara con
   al menos \money{40}.
   #+latex: \vspace*{1ex}

   Por otro lado, la utilidad de Harpo cuando Groucho fuma es $U_H(20)
   = \money{-100}$. Dado que $U_H(0) = 100$, Harpo estaría dispuesto a
   pagar hasta \money{200} para evitar que Groucho fume.
   #+latex: \vspace*{1ex}

   Como resultado de la negociación, Groucho no fumaría y Harpo le
   compensaría con un pago de entre \money{40} y \money{200}.

d) En este caso, Groucho pagaría como mucho $U_G(20) - U_G(0) =
   \money{40}$ para poder fumar. Sin embargo, Harpo exigiría una
   compensación de al menos $U_H(20) - U_H(0) = \money{200}$. Por
   tanto, Harpo no aceptaría la oferta de Groucho y éste no fumaría,
   $c = 0$.


* Q.4

La demanda de un producto es $Q = 90 - P / 4$ y la oferta es $Q
= P / 6$. Al producir el bien se vierten sustancias contaminantes que
generan un daño a la sociedad igual a $\DM = 2 Q$.

a) Obtenga y represente el equilibrio en este mercado en ausencia
   de cualquier tipo de intervención. Calcule la pérdida
   irrecuperable de eficiencia.

b) Para corregir la externalidad, el Gobierno quiere introducir un
   impuesto de $t$ euros por unidad producida. ¿Qué valor debe tomar
   $t$ para conseguir el nivel de producción socialmente óptimo?
   ¿Cuanto recaudaría el Gobierno?

c) El Gobierno también está barajando la posibilidad de utilizar una
   subvención para corregir la externalidad. ¿Cómo debería diseñarse?
   ¿Cuál sería el coste de esta medida?

d) ¿Cuál de las dos medidas, impuesto o subvención, preferirían las
   empresas? ¿Y los compradores del bien?


** Answer

a) Equilibrio.

   #+xxx: fig file:fig-07_1047-ex4-a-*.pdf

b) Impuesto.

   #+xxx: fig file:fig-07_1047-ex4-b-*.pdf


b) Subvención.

   #+xxx: fig file:fig-07_1047-ex4-c-*.pdf

* Q.5

La curva de demanda inversa de un mercado donde opera un monopolista es:
#+begin_export latex
\[
  P = 100 - Q / 30.
\]
#+end_export

El coste marginal del monopolista viene dado por:
#+begin_export latex
\[
  \CMg = 20 + Q / 45.
\]
#+end_export
Como resultado del proceso productivo se vierten residuos
contaminantes a un río cercano. El daño marginal que origina la
polución se ha valorado en $\money{20}$ por unidad producida.

a) ¿Cuál sería el nivel eficiente de producción en este mercado? ¿Qué
   precio debería fijarse?

b) ¿Cuántas unidades produciría el monopolista? ¿Cuánto cobraría por
   cada una de ellas? Calcule la pérdida irrecuperable de eficiencia
   que se produciría en este mercado.

c) Si se interviene para que el mercado funcione como uno competitivo,
   ¿se obtendría una situación eficiente? En caso de que su respuesta
   sea negativa, calcule la ineficiencia en este caso.

d) Compare los resultados obtenidos en los dos apartados
   anteriores. Desde el punto de vista de la eficiencia económica,
   ¿qué tipo de mercado sería preferible en este caso? ¿El monopolista
   o el competitivo?


** Answer

Por hacer.


* Q.6

El Gobierno quiere mejorar la calidad de las aguas de un río en el que
una empresa vierte 50 toneladas de residuos. El beneficio marginal
social de reducir los vertidos en $R$ toneladas es: $\BMS = 200 - 5
R$.  El coste marginal de reducir los vertidos es: $\CM = 20 +
R$. ¿Cuál es el nivel de reducción óptimo desde el punto de vista
social? ¿Qué multa por unidad de polución debería fijarse para
conseguir el nivel óptimo de polución?


** Answer

Por hacer.


* COMMENT Q.1

¿Qué externalidades genera un conductor adicional en una carretera
congestionada? ¿Cómo contribuyen los peajes a paliar esta
externalidad? ¿Qué peaje debería fijarse?


** Answer


* COMMENT Q.1

Identifique la naturaleza de las externalidades en la frase: "El humo
de la fábrica ensuciaba las casas vecinas y era veneno para los
cultivos de la zona".


** Answer

Por hacer.


* COMMENT Q.7

En una pequeña aldea habitan 100 personas que trabajan en una ciudad
situada a 30 km de distancia. Disponen de dos opciones de transporte:

- Tren: el tiempo de viaje total (ida y vuelta) es de $t_T = 40$ minutos
  al día, independientemente de cuantos viajeros opten por este medio
  de transporte.

- Coche privado: sólo hay una carretera antigua de un carril por
  sentido. El tiempo de viaje total (en minutos) con este modo de
  transporte depende del número de conductores que lo usen, $C$:
  #+begin_export latex
  \[
     t_C = 20 + C / 2.
  \]
  #+end_export

El coste monetario del viaje es el mismo en los dos modos de
transporte y los viajeros no perciben diferencias relevantes entre las
dos alternativas, salvo por la duración del viaje. Todos los
trabajadores consideran el tiempo de viaje como una inconveniencia y
cada uno de ellos estaría dispuesto a pagar hasta \money{0.10} por
cada minuto que ahorrasen.

a) ¿Cuál sería el número socialmente óptimo de conductores (para el
   que se minimizaría el tiempo que el conjunto de la sociedad dedica
   a viajar)?

b) Si cada trabajador elige el medio de transporte atendiendo
   únicamente al tiempo que dura su viaje, ¿cuántos utilizarían el
   coche? ¿Coincide su respuesta con la del apartado anterior? ¿por
   qué?

c) Si se establece un peaje para utilizar la carretera, ¿podría
   obtenerse la solución eficiente? ¿Cuál sería el peaje óptimo?


** Answer

Por hacer.


* COMMENT Q.6

El beneficio marginal privado asociado al consumo de un bien es $\BMP
= 30 - Q / 4$ y el coste marginal privado asociado a la producción del
bien es $\CMP = Q / 2$. El daño marginal causado por la producción del
bien es igual a \money{30} por unidad de producto.

a) Calcule la pérdida irrecuperable de eficiencia. Represente
   gráficamente.

b) Para corregir la externalidad el gobierno quiere establecer un
   impuesto de $t$ euros por unidad vendida. ¿Cuál debería ser la
   cuantía del impuesto para alcanzar el óptimo social?

c) Si en vez del impuesto el gobierno utilizara una subvención para
   corregir la ineficiencia, ¿cómo debería diseñarla?

d) Compare los resultados de los dos apartados anteriores. ¿Cuál de
   las dos medidas sería preferible?


** Answer

Por hacer.


* COMMENT Q.10

\DANGER Tanto la empresa $A$ como la $B$ emiten al mes 150 toneladas
de sustancias contaminantes. El Gobierno quiere intervenir para
reducir los niveles de contaminación. Los costes marginales de
reducción de una tonelada de emisiones son $\CM_A = 3 R_A$ para la
empresa $A$ y $\CM_B = 6 R_B$ para la empresa $B$, donde $R_A$ y $R_B$
son las cantidades en que reduce la contaminación cada empresa. El
beneficio marginal social debido a la reducción de la polución es
$\BMS = 600 - 3 R_T$ donde $R_T = R_A + R_B$.

a) ¿Cuál es el nivel eficiente de reducción de las emisiones? ¿Y el
   nivel socialmente óptimo de emisiones?

b) Si se establece un sistema de permisos /no/ transferibles y se
   reparte la mitad a cada empresa, ¿cuantos deben repartirse a cada
   empresa para obtener el nivel de emisiones eficiente? ¿Es posible
   encontrar repartos de los permisos que permitan alcanzar el óptimo
   social de una forma menos costosa?

c) Si se reparten a partes iguales los permisos correspondientes al
   óptimo social y se permite la compra y la venta de estos permisos,
   ¿en cuántas toneladas reduciría cada empresa sus emisiones?

d) ¿Puede alcanzarse el óptimo social mediante un impuesto a la
   polución?


** Answer

Por hacer.


* COMMENT Q.1

El gobierno del Reino Unido anunció en 1997 que, por primera vez, los
estudiantes universitarios deberían pagar una parte del coste de sus
estudios superiores. Un portavoz de los estudiantes declaró:
"Consideramos la gratuidad de la matricula como un derecho [...]
Siempre se nos ha dicho que si eliges continuar con tus estudios, el
Estado debe pagar porque devolverás mucho al Estado consiguiendo un
mejor trabajo y pagando más impuestos". Comente.


** Answer

Por hacer.

# Local Variables:
# ispell-dictionary: "spanish"
# End:

#  LocalWords:  COMMENT Answer Groucho Harpo Coase
