# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Eficiencia y equidad: ejercicios

1. Considere una economía con dos personas: Ana y Berto, que consumen
   dos bienes: pan y agua. Debido a la pertinaz sequía, las
   autoridades deciden reasignar las dotaciones de agua de forma que
   cada persona disponga exactamente de la mitad del agua
   disponible. Se estipula, además, la prohibición de intercambiar pan
   por agua con el objetivo de que nadie pueda "explotar" a
   nadie. ¿Puede ser una redistribución de ese tipo una mejora en
   sentido de Pareto? ¿Es posible que la asignación resultante sea
   Pareto eficiente?

   #+begin_answer

   #+end_answer

2. Una economía está compuesta por dos consumidores: Alicia y Bruno; y
   dos bienes de consumo: café y donuts. Tanto Alicia como Bruno están
   dispuestos a intercambiar dos tazas de café por un donut. Por otro
   lado, si se produjera una taza de café menos se liberarían
   suficientes factores para producir tres donuts. ¿Se cumplen las
   condiciones de eficiencia en esta economía? Si la respuesta es
   negativa, ¿habría que producir más tazas de café o más donuts?

   #+begin_answer

   #+end_answer

3. Considere una economía con dos individuos $A$ y $B$. La tabla
   siguiente muestra algunas combinaciones de utilidad que se
   encuentran sobre la frontera de posibilidades de utilidad:

   #+begin_export latex
   \begin{center}
     \begin{tabular}{>{$}l<{$}*{2}{>{$}r<{$}}}
       \toprule
       \text{Opción} & U_A & U_B \\
       \midrule
       M & 100 &  0 \\
       N &  90 & 20 \\
       O &  60 & 30 \\
       P &  30 & 30 \\
       Q &  40 & 60 \\
       R &  10 & 70 \\
     \bottomrule
   \end{tabular}
   \end{center}
   #+end_export

   Indique cuál será la opción elegida de acuerdo con:

   a) el criterio utilitarista.

      #+begin_answer

      #+end_answer

   b) el criterio igualitarista.

      #+begin_answer

      #+end_answer

   c) el criterio /rawlsiano/.

      #+begin_answer

      #+end_answer

4. Analice la veracidad o falsedad de las siguientes afirmaciones:

   a) La aplicación del criterio /rawlsiano/ conduce necesariamente a
      una distribución igualitaria de la renta.

      #+begin_answer

      #+end_answer

   b) Dada una curva de posibilidades de utilidad para dos individuos,
      la aplicación del criterio utilitarista llevará siempre a una
      distribución menos igualitaria que la del criterio /rawlsiano/.

      #+begin_answer

      #+end_answer

5. \DANGER Una economía está compuesta por dos individuos: $A$ y
   $B$. $A$ dispone de un factor de producción que puede usar para
   producir un bien de consumo $X$. $B$ no posee ninguna unidad del
   factor de producción y, por tanto, no puede producir nada. Para
   paliar esta situación el gobierno puede transferir a $B$ una
   fracción $t$ de la producción de $A$. La producción de $A$ depende
   de $t$ mediante la siguiente función:
   #+begin_export latex
   \[
     X(t) = 167 (1 - t) (t + 0.6)
   \]
   #+end_export
   Suponiendo que la utilidad de ambos individuos es igual a la
   cantidad que consumen del bien $X$, determinar qué fracción debería
   $t$ debería establecerse de acuerdo a un criterio:

   a) utilitarista.

      #+begin_answer

      #+end_answer

   b) /rawlsiano/.

      #+begin_answer

      #+end_answer

   c) igualitarista.

      #+begin_answer

      #+end_answer

6. \DDANGER Considere una economía pura de intercambio con dos
   consumidores $A$ y $B$ y dos bienes $X$ e $Y$. Las preferencias
   vienen dadas por:
   #+begin_export latex
   \begin{gather*}
     U_{A}(X_{A}, Y_{A}) = X_{A}^{1/4} Y_{A}^{1/4} \\
     U_{B}(X_{B}, Y_{B}) = X_{B}^{1/4} Y_{B}^{1/4}
   \end{gather*}
   #+end_export
   Las dotaciones iniciales de los consumidores son:
   #+begin_export latex
   \begin{gather*}
     \Xbar_{A} = 20; \quad \Ybar_{A} = 60. \\
     \Xbar_{B} = 80; \quad \Ybar_{B} = 40.
   \end{gather*}
   #+end_export

   a) ¿Es la dotación inicial Pareto eficiente?

      #+begin_answer

      #+end_answer

   b) Calcule la curva de contrato.

      #+begin_answer

      #+end_answer

   c) Considere ahora que se instituyen mercados competitivos para
      asignar los bienes de consumo. ¿Se alcanza el equilibrio
      competitivo si los precios son $P_X = 2$ y $P_Y = 1$? Si su
      respuesta es negativa, calcule los precios del equilibrio
      competitivo. ¿Es eficiente la asignación de mercado?

      #+begin_answer

      #+end_answer
