# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Externalidades: ejercicios

1. El gobierno del Reino Unido anunció en 1997 que, por primera vez,
   los estudiantes universitarios deberían pagar una parte del coste
   de sus estudios superiores. Un portavoz de los estudiantes declaró:
   "Consideramos la gratuidad de la matricula como un derecho
   [...] Siempre se nos ha dicho que si eliges continuar con tus
   estudios, el Estado debe pagar porque devolverás mucho al Estado
   consiguiendo un mejor trabajo y pagando más impuestos". Comente.

   #+begin_answer

   #+end_answer

2. En un pueblo pesquero las capturas mensuales totales de pescado,
   $Q$ (medidas en kg), dependen del número de barcas que faenan, $N$:
   \begin{equation*}
     Q = \num{1000} N^{1/2}.
   \end{equation*}
   Todas las barcas son idénticas y capturan la misma cantidad de pescado:
   \begin{equation*}
     q_i = Q / N.
   \end{equation*}
   Los costes mensuales de operar cada barca son de $c_i =
   \money{1000}$ al mes. El pescado se vende en un mercado competitivo
   a un precio de $P = \price[kg]{6}$.  Inicialmente no hay ningún
   tipo de limitación al número de barcas que operan en el pueblo.

   a) Suponga que operan $16$ barcas. ¿Qué beneficios obtiene cada
      barca?

      #+begin_answer

      #+end_answer

   b) Si una barca más empieza a pescar, calcule el efecto externo
      que tienen que soportar los pescadores que ya estaban operando.

      #+begin_answer

      #+end_answer

   c) Calcule el número de barcas de equilibrio.

      #+begin_answer

      #+end_answer

   d) Calcule el número de barcas socialmente óptimo.

      #+begin_answer

      #+end_answer

   e) El ayuntamiento está considerando la posibilidad de introducir
      un sistema de licencias. ¿Qué precio debería fijar para cada
      licencia si quiere conseguir que opere el número socialmente
      óptimo de barcas?

      #+begin_answer

      #+end_answer

3. La demanda de un producto es $Q = 1200 - 4 P$ y la oferta es $Q = 2
   P$. Al producir el bien se vierten sustancias contaminantes que
   generan un daño a la sociedad valorado en \money{30} por unidad de
   producto.

   a) Obtenga y represente el equilibrio en este mercado en ausencia
      de cualquier tipo de intervención. Calcule la pérdida
      irrecuperable de eficiencia.

      #+begin_answer

      #+end_answer

   b) Para corregir la externalidad, el Gobierno quiere introducir un
      impuesto de $t$ euros por unidad producida. ¿Qué valor debe
      tomar $t$ para conseguir el nivel de producción socialmente
      óptimo? ¿Cuanto recaudaría el Gobierno?

      #+begin_answer

      #+end_answer

   c) El Gobierno también está barajando la posibilidad de utilizar
      una subvención para corregir la externalidad. ¿Cómo debería
      diseñarse? ¿Cuál sería el coste de esta medida?

      #+begin_answer

      #+end_answer

   d) ¿Cuál de las dos medidas, impuesto o subvención, preferirían las
      empresas? ¿Y los compradores del bien?

      #+begin_answer

      #+end_answer

4. El Gobierno quiere mejorar la calidad de las aguas de un río en el
   que una empresa vierte residuos. El beneficio marginal social de
   reducir los vertidos en $R$ toneladas es: $\BMS = 200 - 5 R$.  El
   coste marginal de reducir los vertidos es: $\CM = 20 + R$. ¿Cuál es
   el nivel de reducción óptimo desde el punto de vista social? ¿Qué
   multa por unidad de polución debería fijarse para conseguir el
   nivel óptimo de polución?

   #+begin_answer

   #+end_answer

5. \DANGER Tanto la empresa $A$ como la $B$ emiten al mes 150
   toneladas de sustancias contaminantes. El Gobierno quiere
   intervenir para reducir los niveles de contaminación. Los costes
   marginales de reducción de una tonelada de emisiones son $\CM_A = 3
   R_A$ para la empresa $A$ y $\CM_B = 6 R_B$ para la empresa $B$,
   donde $R_A$ y $R_B$ son las cantidades en que reduce la
   contaminación cada empresa. El beneficio marginal social debido a
   la reducción de la polución es $\BMS = 600 - 3 R_T$ donde $R_T =
   R_A + R_B$.

   a) ¿Cuál es el nivel eficiente de reducción de las emisiones? ¿Y el
      nivel socialmente óptimo de emisiones?

      #+begin_answer

      #+end_answer

   b) Si se establece un sistema de permisos *no* transferibles y se
      reparte la mitad a cada empresa, ¿cuantos deben repartirse a
      cada empresa para obtener el nivel de emisiones eficiente? ¿Es
      posible encontrar repartos de los permisos que permitan alcanzar
      el óptimo social de una forma menos costosa?

      #+begin_answer

      #+end_answer

   c) Si se reparten a partes iguales los permisos correspondientes al
      óptimo social y se permite la compra y la venta de estos
      permisos, ¿en cuántas toneladas reduciría cada empresa sus
      emisiones?

      #+begin_answer

      #+end_answer

   d) ¿Puede alcanzarse el óptimo social mediante un impuesto a la polución?

      #+begin_answer

      #+end_answer
