# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Elección pública: ejercicios

1. ¿Coincide el votante mediano con el votante con renta mediana? Use
   ejemplos.

   #+begin_answer

   #+end_answer

2. Andrea, Blas y Carla valoran la protección policial de forma
   diferente. Las demandas del bien público son:

   - Andrea: $Q = 55 - 5 P$.

   - Blas: $Q = 80 - 4 P$.

   - Carla: $Q = 100 - 10 P$.

   Si el coste marginal de proporcionar una hora adicional de
   protección policial es \wage{13.5}, ¿cuál es el nivel
   socialmente óptimo de protección policial? Si se utiliza la
   propuesta de Lindahl, ¿qué parte de la carga impositiva soportaría
   cada ciudadano?

   #+begin_answer

   #+end_answer

3. Suponga que hay 5 personas (1, 2, ... 5) que ordenan cuatro
   posibles proyectos ($A$, $B$, $C$ y $D$) como se muestra en la
   siguiente tabla:
   #+BEGIN_EXPORT latex
   \begin{center}
   \begin{tabular}{@{}>{$}l<{$}*{4}{p{1cm}>{$}l<{$}}@{}}
     \toprule
     1 && 2 && 3 && 4 && 5 \\
     \midrule
     A && A && D && C && B \\
     D && C && B && B && C \\
     C && B && C && D && D \\
     B && D && A && A && A \\
     \bottomrule
   \end{tabular}
   \end{center}
   #+END_EXPORT
   a) Represente gráficamente las preferencias.

      #+begin_answer

      #+end_answer

   b) Si se usa la regla de la mayoría, ¿se elegirá algún proyecto?
      ¿Cuál? Si no se elige ninguno explique por qué.

      #+begin_answer

      #+end_answer

4. Para determinar el ganador de un premio a los méritos deportivos
   una asociación utiliza el siguiente sistema: cada votante asigna 5
   puntos a su atleta preferido, 3 puntos al segundo y 1 punto al
   tercero. Los puntos recibidos por todos los votantes se suman y el
   premio se otorga a quien consiga más votos. En la edición de este
   año hay 3 votantes (1, 2 y 3) y 5 candidatos ($A$, $B$, $C$, $D$, y
   $E$). La siguiente tabla muestra como ordena cada votante a los 5
   candidatos:
   #+BEGIN_EXPORT latex
   \begin{center}
   \begin{tabular}{@{}>{$}l<{$}*{2}{p{1cm}>{$}l<{$}}@{}}
     \toprule
     1 && 2 && 3 \\
     \midrule
     D && D && C \\
     A && A && A \\
     C && C && B \\
     B && B && E \\
     E && E && D \\
     \bottomrule
   \end{tabular}
   \end{center}
   #+END_EXPORT
   El candidato $C$ se ha visto implicado en una trama de dopaje y el
   día anterior a la votación se anunciará el veredicto del tribunal
   que le ha juzgado. Si fuera declarado culpable, los estatutos de la
   asociación deportiva impedirían que optase al premio.

   a) ¿Quién ganará el premio si $C$ es declarado inocente?

      #+begin_answer

      #+end_answer

   b) ¿Y si $C$ es declarado culpable?

      #+begin_answer

      #+end_answer

   c) ¿Que tipo de problema presenta este sistema de votación?

      #+begin_answer

      #+end_answer
