#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit09}}}: ejercicios

* Q.1

Algunos autores piensan que las preferencias sobre el nivel de gasto
público en sanidad presentan con frecuencia un patrón bimodal. ¿En qué
circunstancias podría aparecer este patrón? ¿Por qué?

** Answer

Un patrón bimodal de preferencias sobre el gasto público sanitario
puede aparecer cuando existe una alternativa privada a la provisión
pública de sanidad.
#+latex: \smallskip

En ese contexto, algunos individuos prefieren un nivel elevado de
gasto público porque permitiría disponer de un sistema público amplio
y de buena calidad. Sin embargo, si ese nivel de gasto no es
políticamente viable, pueden preferir que el gasto sea lo más reducido
posible.
#+latex: \smallskip

La razón es que un nivel intermedio de gasto podría no ofrecer una
sanidad pública suficientemente buena y, en ese caso, estos individuos
preferirían pagar menos impuestos y recurrir a la sanidad
privada. Así, las preferencias pueden concentrarse en dos opciones:
mucho gasto público o muy poco, con escaso apoyo a soluciones
intermedias.



* Q.2

Suponga que en una ciudad hay tres grupos de personas (pobres, renta
media y ricos) de igual tamaño y que votan en bloque. Para decidir el
tipo del impuesto sobre la renta aplicable a cada grupo se someten a
votación tres alternativas (A, B y C) que generan la misma recaudación
total:
#+ATTR_LATEX: :booktabs t :center t :align w{l}{2.5cm}*{3}{>{$}w{c}{2cm}<{$}}
|             | \text{A} | \text{B} | \text{C} |
|-------------+----------+----------+----------|
| Pobres      | \pct{20} | \pct{18} | \pct{17} |
| Renta media | \pct{20} | \pct{18} | \pct{21} |
| Ricos       | \pct{20} | \pct{23} | \pct{22} |
Las preferencias de cada grupo dependen exclusivamente del tipo
impositivo que les correspondería en cada una de las alternativas.

a) Muestre que la regla de la mayoría generaría una pauta cíclica de
   votaciones.

b) Suponga que, para evitar pautas cíclicas, se eliminan las
   alternativas que no resulten elegidas en cada votación. Si un
   representante del grupo de renta media decide qué par de
   alternativas se votará primero, ¿cuáles elegirá?

c) Suponga que el representante del grupo de renta media elige el
   orden de las votaciones. Tanto el grupo de pobres como el de renta
   media votan sinceramente, mientras que el grupo de ricos es el
   único que vota estratégicamente, sin que los demás lo prevean. ¿Qué
   opción resultaría elegida?

** Answer
#+latex: \newcommand*{\altA}{\text{A}}
#+latex: \newcommand*{\altB}{\text{B}}
#+latex: \newcommand*{\altC}{\text{C}}

a) Cada grupo prefiere el tipo impositivo más bajo para sí mismo, por
   lo que las preferencias de cada grupo son:
   #+ATTR_LATEX: :booktabs t :center t :align *{2}{w{l}{2.5cm}}
   | Grupo       | Preferencias        |
   |-------------+---------------------|
   | Pobres      | $\altC \succ \altB \succ \altA$ |
   | Renta media | $\altB \succ \altA \succ \altC$ |
   | Ricos       | $\altA \succ \altC \succ \altB$ |

   Votaciones por mayoría:

   - A frente a B: Pobres y renta media prefieren B, por lo que  gana B

   - B frente a C: Pobres y ricos prefieren C, por lo que se elige C.

   - A frente a C: Renta media y ricos prefieren A y gana esta
     alternativa.

   Por tanto: $\altC \succ \altB$, $\altB \succ \altA$ y $\altA \succ
   \altC$ y se genera un ciclo de mayorías.

b) El representante del grupo de renta media quiere que el resultado
   final sea B. Si se vota primero A contra C, se
   elige A. Posteriormente B es elegida en la votación de A frente
   a B. El resultado final sería la alternativa B. Por tanto, el
   representante del grupo de renta media elegirá que la primera
   votación sea entre A y C.

c) El grupo de renta media elige el orden esperando que todos voten
   sinceramente, por lo que se confrontan en primer lugar las
   alternativas A y C. Si todos votan de acuerdo a sus preferencias,
   la alternativa seleccionada es B, la opción menos preferida por los
   ricos. Si este grupo vota estratégicamente, optará por la opción C
   en la primera votación. En la segunda votación de C frente a B, se
   elige la opción C si todos votan de acuerdo a sus preferencias.


* Q.3

En una liga deportiva se usa un sistema de votación para elegir el
jugador más valioso de cada temporada. Cada votante asigna 5 puntos al
que considera mejor jugador, 3 puntos al segundo mejor y 1 punto al
tercero. Los puntos que otorgan los votantes se suman y gana el premio
el jugador que obtiene más puntos. Suponga que hay tres votantes (1, 2
y 3) y 5 jugadores (A, B, C, D y E) y que las ordenaciones de
preferencia de los votantes son:
#+ATTR_LATEX: :booktabs t :center t
| Valoración    | 1 | 2 | 3 |
|---------------+---+---+---|
| Mejor         | A | A | B |
| Segundo mejor | C | C | C |
| Tercero mejor | B | B | D |
| Cuarto mejor  | D | E | E |
| Quinto mejor  | E | D | A |
El jugador B está envuelto en un escándalo de uso de sustancias
prohibidas. El veredicto acerca de la inocencia o culpabilidad de B
llegará el día antes de las votaciones y si B es declarado culpable
quedaría excluido de la votación.

a) ¿Quién ganaría el premio si B es declarado inocente?

b) ¿Y si es declarado culpable?

c) ¿Qué problema de la agregación de las preferencias individuales se
   manifiesta en este ejemplo?

** Answer

a) Si B es declarado inocente, las puntuaciones totales son:
   #+ATTR_LATEX: :booktabs t :center t :align cr
   | Jugador | Puntos |
   |---------+--------|
   | A       | 10     |
   | B       | 7      |
   | C       | 9      |
   | D       | 1      |
   | E       | 0      |

   El ganador sería A.

b) Si B es declarado culpable, las puntuaciones son:
   #+ATTR_LATEX: :booktabs t :center t :align cr
   | Jugador | Puntos |
   |---------+--------|
   | C       | 11     |
   | A       | 10     |
   | D       | 4      |
   | E       | 2      |

   El ganador sería C.

c) El ganador cambia cuando se elimina B, aunque B no ganaba
   inicialmente. Esto muestra que el sistema viola la propiedad de la
   independencia de alternativas irrelevantes: la comparación entre A
   y C depende de la presencia o ausencia de B.


* Q.4

Alicia, Bruno, Celia, David y Elena son los cinco filántropos más
acaudalados de una ciudad y quieren donar parte de sus riquezas a una
causa benéfica. Para evitar comparaciones entre las aportaciones
individuales, han decidido que todos donarán la misma cantidad de
dinero. Las propuestas de cada uno de los filántropos se presentan en
la siguiente tabla:
#+ATTR_LATEX: :booktabs t :center t :align *{5}{w{c}{2cm}}
| Alicia         | Bruno          | Celia         | David          | Elena          |
|----------------+----------------+---------------+----------------+----------------|
| \money{500000} | \money{100000} | \money{50000} | \money{250000} | \money{200000} |
La cantidad que aportará cada uno se seleccionará mediante votaciones
por mayoría entre pares de propuestas.

Sabiendo que las preferencias de cada uno de los potentados alcanzan
un máximo en su propuesta y disminuyen cuanto más se alejan de su
donación preferida, responda a las siguientes preguntas:

a) ¿Es posible determinar sin ambigüedad cuál será la propuesta
   elegida mediante votaciones por mayoría?

b) ¿Es posible encontrar una ordenación colectiva consistente con las
   preferencias individuales? Si su respuesta es afirmativa, ¿cuál es
   esa ordenación?

** Answer

a) Con preferencias unimodales, la regla de la mayoría selecciona la
   propuesta del votante mediano. Se elegiría, por tanto, la propuesta
   mediana de \money{200000}, correspondiente a Elena.

b) Con preferencias unimodales las preferencias colectivas son transitivas ya que serían idénticas a las preferencias de Elena, la votante mediana. La ordenación social es:
   #+begin_export latex
   \[
     \money{200000} \succ
     \money{250000} \succ
     \money{100000} \succ
     \money{50000} \succ
     \money{500000}
   \]
   #+end_export



* Q.5

Andrea, Blas y Carla son los únicos habitantes de una pequeña
ciudad. Cada uno de ellos tiene una demanda diferente de protección
policial:

- Andrea: $Q = 55 - 5 P_A$

- Blas: $Q = 80 - 4 P_B$

- Carla: $Q = 100 - 10 P_C$

donde $Q$ es el número de horas de protección policial en la ciudad y
$P_i$ es el precio que debe pagar el habitante $i$ por cada hora que
se contrate.  Si el coste marginal de proporcionar una hora adicional
de protección policial es \wage{13.5}, ¿cuál es el nivel socialmente
óptimo de $Q$? Si se utiliza la propuesta de Lindahl, ¿qué parte de la
carga impositiva soportaría cada ciudadano?

** Answer

Se obtiene la curva de demanda colectiva sumando las curvas de demanda
inversa. El beneficio marginal social, \BMS, es:
#+begin_export latex
\[
  \BMS = (11 - Q / 5) + (20 - Q / 4) + (10 - Q / 10)= 41 - 11 Q / 20.
\]
#+end_export

El óptimo social satisface:
#+begin_export latex
\[
  41 - 11 Q^* / 20 = 13.5,
\]
#+end_export
de donde: $Q^* = 50$ horas.

Los precios de Lindahl se obtienen de las curvas de demanda inversa,
ya que representan las disposiciones marginales a pagar de cada
individuo:
#+begin_export latex
\begin{gather*}
P_A = 11 - 50 / 5 = \wage{1}, \\
P_B = 20 - 50 / 4 = \wage{7.5}, \\
P_C = 10 - 50 / 10 = \wage{5}.
\end{gather*}
#+end_export

Pagos totales:
#+ATTR_LATEX: :booktabs nil :center t :align lr
| Andrea: | 1  \cdot  50 = \money{50}    |
| Blas:  | 7.5  \cdot  50 = \money{375} |
| Carla: | 5  \cdot  50 = \money{250}   |
La suma de pagos es \money{675}, igual al coste total de las $50$
horas.



* COMMENT Q.1

Suponga que 5 votantes (1, 2, 3, 4 y 5) ordenan de más a menos
preferido los proyectos A, B, C y D como muestra la siguiente tabla:

#+ATTR_LATEX: :booktabs t :center t
| 1 | 2 | 3 | 4 | 5 |
|---+---+---+---+---|
| A | A | D | C | B |
| D | C | B | B | C |
| C | B | C | D | D |
| B | D | A | A | A |

a) Represente gráficamente las preferencias de los 5 votantes.

b) ¿Es posible agregar de forma consistente las preferencias
   individuales con la regla de la mayoría? Si su respuesta es
   afirmativa, ¿qué proyecto sería preferido por la sociedad? Si su
   respuesta es negativa, explique por qué.

** Answer

Por hacer

# Local Variables:
# ispell-dictionary: "spanish"
# End:

#  LocalWords:  bimodal Andrea Lindahl Answer Elena Bruno succ
