# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Bienes públicos: ejercicios

* Q.1

¿Son las autopistas un bien público? ¿Es una idea razonable la
provisión privada de autopistas?

** Answer

Por hacer.

* Q.2

Considere una economía con dos habitantes $A$ y $B$. Sólo se producen
dos bienes: el bien público puro $X$ y el bien privado $Y$. Las
relaciones marginales de sustitución son: $\RMS_A = 5$ y $\RMS_B = 10$
unidades de $Y$ por unidad de $X$. La relación marginal de
transformación es $\RMT = 20$ unidades de $Y$ por unidad de $X$. ¿Es
eficiente la situación descrita?

** Answer

Por hacer.

* Q.3

Tarzán y Jane viven en la jungla y han adiestrado a Chita para que
patrulle los límites de su asentamiento y para que recolecte
fruta. Chita puede recoger 3 kg de fruta por hora y dedica 6 horas al
día a patrullar y 8 horas a recolectar fruta.

a) Identifique si los bienes de este ejemplo son públicos o privados.

b) Si Tarzán y Jane están dispuestos cada uno a sacrificar una hora de
   patrulla por 2 kg de fruta, ¿es la actual asignación de horas
   patrullando y recolectando un óptimo de Pareto? ¿Debería Chita
   patrullar más horas o menos?

** Answer

Por hacer.

* Q.4

El coste marginal de producir Q unidades de un bien público puro es:
$\CM = 5 Q$. Existen 100 demandantes: 75 cuya demanda viene dada por
$Q = 50 - 5 P$; y 25 con demanda es $Q = 100 - 5 P$. ¿Cuál sería la
provisión eficiente del bien público? Represente gráficamente.

** Answer

Por hacer.

* Q.5

Rocío y Pablo comparten un piso. La siguiente tabla muestra, para un
conjunto de temperaturas, el beneficio marginal de Rocío, el beneficio
marginal de Pablo y el coste marginal de mantener el piso a esa
temperatura durante una semana:
#+begin_center
#+latex: \small\normalfont%
#+attr_latex: :booktabs :center :align @{}*{4}{c}@{}
|-------------+--------------------+--------------------+----------------|
| Temperatura | Beneficio marginal | Beneficio marginal | Coste marginal |
|        (ºC) |       Rocío (€/ºC) |       Pablo (€/ºC) |         (€/ºC) |
|-------------+--------------------+--------------------+----------------|
|          18 |                  8 |                 12 |             14 |
|          19 |                  7 |                 10 |             17 |
|          20 |                  5 |                  8 |             21 |
|          21 |                  2 |                  6 |             26 |
|          22 |                  1 |                  3 |             32 |
|-------------+--------------------+--------------------+----------------|
#+end_center

¿Es la temperatura del piso un bien público? ¿Cuál sería la
temperatura eficiente?

** Answer

Por hacer.

* Q.6

En una ciudad hay tres tipos de personas que se distinguen únicamente
por sus preferencias con respecto a los parques municipales. Cada una
de las personas del primer tipo están dispuestas a pagar $D_{I} =
\money{100}$ por la mera existencia de algún parque y esta disposición
es independiente del número de parques que haya. Por otro lado, la
disposición a pagar de los individuos de los otros dos tipos es:
#+begin_export latex
\begin{gather*}
  D_{II} = 200 + 30 N - 1.5 N^{2} \\
  D_{III} = 150 + 90 N - 4.5 N^{2}
\end{gather*}
#+end_export
donde $N$ es el número de parques de la ciudad. Si hay 500 individuos
de cada tipo, cada parque cuesta \money{40000} y sólo se puede
construir un número entero de parques, ¿cuántos deben de construirse?

** Answer

Por hacer.

* Q.7

La curva de demanda de un bien privado viene dada por $P = 50 - Q$. El
coste de producir una unidad adicional del bien es de \price{15} y no
depende de la cantidad producida. Cuando el bien es provisto por
empresas competitivas, estas tienen que afrontar unos costes de
transacción de \price{10}. El gobierno está planteándose la
posibilidad de proveer el bien gratuitamente, en cuyo caso no
existirían costes de transacción. ¿Es eficiente la provisión privada?
¿Y la pública? ¿Cuál de las dos opciones es más conveniente desde el
punto de vista social?

** Answer

Por hacer.

* Q.8

La curva de costes de un monopolio natural es: $\CT(Q) = \num{10000} +
Q$. La curva de demanda de mercado es $Q = \num{5150} - 50 P$.

a) ¿Cuál sería el precio que maximiza el beneficio de la empresa?
   Calcule la pérdida de eficiencia en esta situación.

b) Si el Gobierno obliga al monopolista a fijar el precio competitivo,
   ¿cuál sería el beneficio del monopolista?

c) Calcule el precio que debería fijar el monopolio para obtener
   beneficios nulos.

** Answer

Por hacer.

* Q.9

\DANGER En una pequeña ciudad sólo viven dos personas: Alba y
Blanca. El servicio de bomberos de la ciudad se financia
exclusivamente con su aportaciones voluntarias. Tanto Alba como Blanca
tienen las mismas preferencias sobre su consumo de bienes privados,
$Y_i$, y sobre el número total de bomberos contratado por el
ayuntamiento, $N$. Estas preferencias se pueden representar por las
funciones de utilidad:
#+begin_export latex
\begin{gather*}
  \text{Alba: } U_{A} = 4 \log Y_A + 2 \log N \\
  \text{Blanca: } U_{B} = 4 \log Y_{B} + 2 \log N
\end{gather*}
#+end_export
El número total de bomberos es la suma de los contratados por las
aportaciones de Ana, $N_A$, y de Blanca, $N_B$: $N = N_A + N_B$. Tanto
Ana como Blanca disponen de una renta de \money{150} y los precios por
unidad de $Y$ y de $N$ son iguales a \money{1}.

a) ¿Cuántos bomberos se contratarán en estas condiciones?

b) ¿Cuál es el número socialmente óptimo de bomberos? Si su respuesta
   difiere de la del apartado anterior, explique por qué.

c) El ayuntamiento decide contratar 40 bomberos más que financia
   mediante un impuesto de \money{20} a cada habitante. ¿Cuál es ahora
   número total de bomberos contratados? ¿Se ha alcanzado el óptimo
   social? ¿Por qué?

d) Suponga ahora que en vez de tener que financiar con impuestos los
   40 bomberos que contrata el ayuntamiento, un misterioso benefactor
   se hace cargo de los gastos adicionales. ¿Se obtienen en este caso
   los mismos resultados que en el apartado anterior?

** Answer

Por hacer.
