# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: La dimensión del Sector Público: ejercicios

#+PROPERTY: header-args:R :session *R-ec1047-size*
#+PROPERTY: header-args:R+ :tangle yes
#+PROPERTY: header-args:R+ :exports both
#+PROPERTY: header-args:R+ :results output

#+BEGIN_SRC R :exports none :tangle no
  ## Set output width
  options(width=65)
#+END_SRC


Responda a las siguientes preguntas a partir de la información
estadística contenida en las publicaciones:

- [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iaavanceactuacioneconomica.aspx][Avance de la actuación económica y financiera de las
  Administraciones Públicas (2018)]], IGAE.
- [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iacogof.aspx][Informe sobre la clasificación funcional del gasto público (COFOG). Período 2015-2019]], IGAE.
- [[https://www.oecd-ilibrary.org/governance/government-at-a-glance_22214399][Government at a glance 2019]], OECD.

* Q.1

¿A cuánto asciende el gasto público en España en los últimos años?
¿Qué porcentaje con respecto al PIB representa el gasto público?  ¿Es
muy diferente esta última cifra con la media para los países de la
OECD?

** Answer

Utilicemos unas cuantas órdenes de R para conseguir un efecto nada
desdeñable, por si fuera poco:
#+begin_src R
  ## Cálculo de los cinco primeros cuadrados
  x_1 <- (1:5)^2
  x_1

  ## Media
  mean(rnorm(100), na.rm = TRUE)
#+end_src

Esto es una respuesta.

* Q.2

¿Cómo se distribuye el gasto público entre las diferentes
Administraciones Públicas?

** Answer

Esto es una respuesta.

* Q.3

Atendiendo a la clasificación funcional de los gastos, ¿qué grupos
de gasto tienen un mayor peso en España? ¿Cuáles son los grupos más
importantes para las diferentes Administraciones Públicas?

** Answer

Esto es una respuesta.

* Q.4

¿A cuanto ascienden los ingresos de las Administraciones Públicas
en España? ¿Qué porcentaje representan con respecto al PIB? ¿Es muy
diferente esta última cifra con la media para los países de la
OECD?

** Answer

Esto es una respuesta.

* Q.5

¿Cuál es el peso que tienen en España los impuestos directos, los
indirectos y las cotizaciones sociales?

** Answer

Esto es una respuesta.


* Q.6

¿Qué valor toma la presión fiscal en España? ¿Es muy diferente de
los países de nuestro entorno?

** Answer

Esto es una respuesta.

* Q.7

¿Cuál es el tamaño del déficit público en España? ¿Cómo se
distribuye este déficit en las diferentes Administraciones Públicas
que componen el Estado? ¿Es muy diferente el déficit de España del
de otros países de su entorno?

** Answer

Esto es una respuesta.
