# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Eficiencia y equidad: ejercicios


1. Considere una economía con dos personas: Ana y Berto, que consumen
   dos bienes: pan y agua. Debido a la pertinaz sequía, las
   autoridades deciden reasignar las dotaciones de agua de forma que
   cada persona disponga exactamente de la mitad del agua
   disponible. Se estipula, además, la prohibición de intercambiar pan
   por agua con el objetivo de que nadie pueda "explotar" a
   nadie. ¿Puede ser una redistribución de ese tipo una mejora en
   sentido de Pareto? ¿Es posible que la asignación resultante sea
   Pareto eficiente?

   #+begin_answer

   #+end_answer

2. En una economía de mercado que opera eficientemente se producen
   \num{1000000} de unidades del bien $X$ y \num{500000} unidades del
   bien $X$. Los precios a los que se venden estos bienes son $P_X =
   \price{10}$ y $P_Y = \price{2}$. ¿Cuántas unidades adicionales del
   bien $X$ podrían producirse en esta economía si se deja de producir
   una unidad del bien $Y$?

   #+begin_answer

   #+end_answer

3. Una economía está compuesta por dos consumidores: Alicia y Bruno; y
   dos bienes de consumo: café y donuts. Tanto Alicia como Bruno están
   dispuestos a intercambiar dos tazas de café por un donut. Por otro
   lado, si se produjera una taza de café menos se liberarían
   suficientes factores para producir tres donuts. ¿Se cumplen las
   condiciones de eficiencia en esta economía? Si la respuesta es
   negativa, ¿habría que producir más tazas de café o más donuts?

   #+begin_answer

   #+end_answer

4. En un mercado con curva inversa de demanda $P = 14 - 0.04 Q$ opera
   un monopolista cuyos costes marginales son $\CM = 2 + 0.02 Q$. Las
   autoridades económicas están considerando regular las actividades
   del monopolio.

   a) Calcule la ineficiencia del monopolio.

      #+begin_answer

      #+end_answer

   b) Si se obliga al monopolista a fijar el precio competitivo, ¿cuál
      sería el aumento del bienestar de los consumidores?

      #+begin_answer

      #+end_answer

5. Un programa público elevaría ligeramente el bienestar de los
   ciudadanos más pobres pero disminuye considerablemente el bienestar
   de los demás individuos. ¿Debería llevarse a cabo este programa si
   se adopta el criterio utilitarista? ¿Y si se utiliza el criterio
   /rawlsiano/?

   #+begin_answer

   #+end_answer

5. En un país sólo viven dos ciudadanos: Blanca y Teo. Blanca es
   abogada y gana \money{50} por hora. Cuando la tasa impositiva sobre
   la renta, $t$, es del 0%, Blanca trabaja 20 horas a la semana; si
   $t = \SI{25}{\percent}$, trabajaría 16 horas; y si $t =
   \SI{40}{\percent}$ sólo trabajaría 8 horas. Teo trabaja en un
   pequeño taller de reparaciones y gana \money{6} por hora. Teo
   siempre trabaja 20 horas por semana sea cual sea la tasa
   impositiva. El gobierno está pensando en gravar la renta de Blanca
   y transferir la recaudación a Teo.

   a) Blanca y Teo tienen la misma función de utilidad: $U(Y) =
      Y^{1/2}$ donde $Y$ es la renta después de impuestos y
      transferencias. ¿Cuál de las tres tasas impositivas sería óptima
      desde un punto de vista utilitarista? ¿Y si se utiliza una
      función de bienestar social /rawlsiana/?

      #+begin_answer

      #+end_answer

   b) ¿Cambiarían las conclusiones del apartado anterior si la función
      de utilidad fuera $U(Y) = Y^{1/5}$?.

      #+begin_answer

      #+end_answer

   c) Suponga ahora que Blanca y Teo tienen funciones de utilidad
      diferentes. La utilidad de Blanca es $U_B(Y) = 0.25 Y^{1/2}$ y
      la de Teo es $U_T(Y) = Y^{1/2}$. Esto se debe a que Blanca sufre
      una discapacidad por lo que necesita más renta para alcanzar el
      mismo nivel de utilidad. ¿Cómo ordenarían ahora las diferentes
      alternativas los criterios utilitarista y /rawlsiano/?

      #+begin_answer

      #+end_answer
