# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit02}}}

* Q.1

Utilizando el [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Documents/AAPP_A/Resumen.pdf][/Resumen del Informe COFOG 2019-2023/]], disponible en [[https://www.igae.pap.hacienda.gob.es/sitios/igae/es-ES/Contabilidad/ContabilidadNacional/Publicaciones/Paginas/iacogof.aspx][la
web del IGAE]], responda a las siguientes preguntas con los datos del
año 2023:

a) ¿Qué porcentaje sobre el PIB representa el total del gasto público?

b) ¿Cuáles son los principales grupos de gasto público en España?

c) ¿Cómo se reparte el gasto entre las diferentes administraciones
   públicas?

d) ¿Qué grupos de gastos conforman el gasto social de las
   administraciones públicas? ¿Qué porcentaje representan con respecto
   al gasto público total? ¿Y con respecto al PIB?


** Answer

Esto es una respuesta.

* Q.2

El archivo ~Indicators.xlsx~ contiene indicadores de las actividades
del sector público en España y en otros 6 países de la OCDE para el
periodo 2007--2024. Todos los indicadores se expresan como porcentaje
con respecto al PIB:

a) Gasto público (/Government expenditures/).
b) Ingreso público (/Government revenues/).
c) Saldo fiscal (/Government fiscal balance/).
d) Déficit primario (/Government primary balance/).
e) Deuda pública (/Government gross debt/).

Represente gráficamente la evolución temporal de esas
variables. Comente brevemente la posición de España con respecto a los
países de su entorno.

** Answer

Esto es una respuesta.


* Q.3

El archivo ~Revenues.xlsx~ contiene información sobre los ingresos
totales del sector público de España y otros 6 países de la OCDE para
el periodo 2007--2024. También se presentan datos sobre los impuestos y
las cotizaciones a la Seguridad Social. Todos los datos se expresan
como porcentajes del PIB.

a) Determine la *presión fiscal* (porcentaje sobre el PIB que
   representan los impuestos y las cotizaciones sociales) de cada
   uno de los países para el año 2024. Compare las cifras de España
   con las del resto de países. Calcule la presión fiscal en España
   para cada uno de los años del periodo 2007--2024 y comente cómo ha
   evolucionado.

b) Calcule qué porcentaje representan los impuestos /sobre el total de
   los ingresos del sector público/ de cada uno de los países en el
   año 2024. ¿Cómo ha evolucionado este porcentaje en España durante
   el periodo 2007--2024?

c) ¿Qué porcentaje representan las cotizaciones sociales /sobre
   el total de los ingresos del sector público/ de cada uno de los
   países en el año 2024? ¿Cómo ha evolucionado este porcentaje en
   España durante el periodo 2007--2024?


** Answer

Esto es una respuesta.



* Q.4

El archivo ~Taxes.xlsx~ reúne información sobre la estructura del
sistema impositivo de España y otros 6 países de la OCDE durante el
periodo 2007--2024. Los datos se expresan como porcentajes del PIB.

a) Utilizando los datos del año 2024, exprese los diferentes impuestos
   como porcentaje del total de impuestos de cada país y compare la
   estructura del sistema impositivo español con la de los otros
   países.

b) ¿Cómo ha evolucionado cada tipo de impuesto en España a lo largo de
   todo el periodo?

** Answer

Esto es una respuesta.
