# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./course-es.org

#+TITLE: Bienes públicos: ejercicios

1. ¿Son las autopistas un bien público? ¿Es una idea razonable la
   provisión privada de autopistas?

   #+begin_answer

   #+end_answer

2. El coste marginal de producir Q unidades de un bien público puro
   es: $\CM = 3 Q$. Sólo existen dos demandantes: $A$ cuya demanda
   viene dada por $Q_A = 10 - P$; y $B$ con demanda es $Q_B = 20 -
   P$. ¿Cuál sería la provisión eficiente del bien público?

   #+begin_answer

   #+end_answer

3. Tarzán y Jane viven en la jungla y han adiestrado a Chita para que
   patrulle los límites de su asentamiento y para que recolecte
   fruta. Chita puede recoger 3 kg de fruta por hora y actualmente
   dedica 6 horas a patrullar, 8 horas a recolectar y 10 horas a
   dormir.

   a) Identifique si los bienes de este ejemplo son públicos o privados.

      #+begin_answer

      #+end_answer

   b) Si Tarzán y Jane están dispuestos cada uno a sacrificar una hora
      de patrulla por 2 kg de fruta, ¿es la actual asignación de horas
      patrullando y recolectando un óptimo de Pareto? ¿Debería Chita
      patrullar más horas o menos?

      #+begin_answer

      #+end_answer

4. En una ciudad hay tres tipos de ciudadanos que se distinguen
   únicamente por sus preferencias con respecto a los parques. Los
   individuos del primer tipo tienen una disposición a pagar $D_{I} =
   \money{100}$ por la existencia de paqrques en la ciudad y esta
   disposición es independiente del número de parques. Por otro lado,
   la disposición a pagar de los individos de los otros dos tipos es:
   #+begin_export latex
   \begin{gather*}
     D_{II} = 200 + 30 N + 1.5 N^{2} \\
     D_{III} = 150 + 90 N + 4.5 N^{2}
   \end{gather*}
   #+end_export
   donde $N$ es el número de parques de la ciudad. Si hay 500
   individuos de cada tipo, cada parque cuesta \money{40000} y sólo se
   puede construir un número entero de paqrques, ¿cuántos se deben de
   proveer?

   #+begin_answer

   #+end_answer

5. \DANGER En una pequeña ciudad sólo viven dos personas: Alba y
   Blanca. El servicio de bomberos de la ciudad se financia
   exclusivamente con las aportaciones que voluntariamente realizan
   sus habitantes. Tanto Alba como Blanca tienen las mismas
   preferencias sobre su consumo de bienes privados, $X_i$, y sobre el
   número total de bomberos contratado por el ayuntamiento, $N$. Estas
   preferencias se pueden representar por la función de utilidad:
   \begin{equation*}
     U_i = 4\log X_i + 2\log N \qquad (i = A, B)
   \end{equation*}
   El número total de bomberos es la suma de los contratados por las
   aportaciones de Ana, $N_A$, y de Blanca, $N_B$: $N = N_A +
   N_B$. Tanto Ana como Blanca disponen de una renta de \money{150} y
   los precios por unidad de $X$ y de $N$ son iguales a \money{1}.

   a) ¿Cuántos bomberos se contratarán en estas condiciones?

      #+begin_answer

      #+end_answer

   b) ¿Cuál es el número socialmente óptimo de bomberos? Si su
      respuesta difiere de la del apartado anterior, explique por qué.

      #+begin_answer

      #+end_answer

   c) El gobierno decide contratar 40 bomberos más que financia
      mediante un impuesto de \money{20} a cada habitante. ¿Cuál es
      ahora número total de bomberos contratados? ¿Se ha alcanzado el
      óptimo social? ¿Por qué?

      #+begin_answer

      #+end_answer

   d) Suponga ahora que en vez de tener que financiar con impuestos
      los 40 bomberos contratados por el gobierno, un misterioso
      benefactor se hace cargo de los gastos adicionales. ¿Se obtienen
      en este caso los mismos resultados que en el apartado anterior?

      #+begin_answer

      #+end_answer

6. La curva de demanda de un bien privado viene dada por $P = 50 -
   Q$. El coste de producir una unidad adicional del bien es de
   \price{15} y no depende de la cantidad producida. Cuando el bien es
   provisto por empresas competitivas, estas tienen que afrontar unos
   costes de transacción de \price{10}. El gobierno está planteándose
   la posibilidad de proveer el bien gratuitamente, en cuyo caso no
   existirían costes de transacción. ¿Cuál de las dos opciones es más
   conveniente desde el punto de vista social?

   #+begin_answer

   #+end_answer
