# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit13}}}: ejercicios

* Q.1

El gobierno quiere introducir un nuevo impuesto sobre las ventas de
determinados productos y está considerando varias alternativas: a)
un impuesto sobre las ventas de leche semidesnatada; b) sobre los
productos lácteos; o c) sobre todos los productos
alimenticios. ¿Cuál de esas tres alternativas tendría un mayor
impacto sobre los precios de los productos gravados?

#+begin_answer

#+end_answer


* Q.2

En 2003 se estableció en Hong Kong un impuesto de \money{51} al
mes a los empleadores de asistentes domésticos extranjeros. Muchos
de esos trabajadores provenían de Filipinas y el presidente de ese
país se refirió a este impuesto como "injusto y no
equitativo". Teniendo en cuenta que el impuesto era pagado por los
empleadores, ¿bajo qué condiciones estaría justificada la
preocupación del presidente filipino?

#+begin_answer

#+end_answer


* Q.3

Considere un mercado competitivo con curva de demanda $Q^d = \num{54000} -
\num{4000} P$ y curva de oferta $Q^o = \num{1400} P$.

a) Analice la incidencia de un impuesto de \money{1.35} por unidad
   vendida.

   #+begin_answer

   #+end_answer

b) Analice la incidencia de un impuesto sobre las ventas del 15%
   sobre el precio.

   #+begin_answer

   #+end_answer

c) Compare los resultados obtenidos en los dos apartados
   anteriores.

   #+begin_answer

   #+end_answer


* Q.4

Considere un monopolista con curva de demanda $Q =
\num{10000}/P^2$ y costes marginales $\CM = \price{0.5}$. Analice
la incidencia de un impuesto específico de \price{1} por unidad
vendida.

#+begin_answer

#+end_answer


* Q.5

Un monopolista vende su producto en un mercado con demanda: $P =
50 - 0.05 Q$. La producción se caracteriza por costes marginales
constantes: $\CM = \price{10}$.

a) Determine la incidencia de un impuesto específico de \price{2}.

   #+begin_answer

   #+end_answer

b) Determine la incidencia de un impuesto del 20% sobre el precio
   de venta.

   #+begin_answer

   #+end_answer

c) ¿Es diferente la recaudación del impuesto si el impuesto es
   específico o es /ad valorem/?

   #+begin_answer

   #+end_answer


* Q.6

Las curvas de demanda y oferta de un mercado de trabajo competitivo
son:
#+begin_export latex
\begin{gather*}
  L^{d} = \num{60000} - \num{3000} w \\
  L^{s} = \num{20000} + \num{1000} w
\end{gather*}
#+end_export
donde $L$ se mide en horas y $w$ es el salario por hora.

a) ¿Cuál sería la incidencia de un impuesto de \wage{4} pagado por
   los empleadores? ¿Cómo cambiaría su respuesta si el impuesto
   fuese pagado a partes iguales por empleadores y empleados?

   #+begin_answer

   #+end_answer

b) Suponga ahora que una nueva ley establece un salario mínimo de
   \wage{8}. Repita el análisis del apartado anterior.

   #+begin_answer

   #+end_answer



* Q.7

Una ciudad está considerando introducir un impuesto del 10% de los
ingresos de los hoteles situados en el término municipal. A pesar
de no ser muy diferentes a los de localidades vecinas, los hoteles
de la ciudad están mucho más próximos a un aeropuerto y a muchos
centros de convenciones. Por estas razones los viajeros están
dispuestos a pagar un precio más alto por alojarse en ellos.

Por otro lado los terrenos de la ciudad que pueden destinarse a
usos comerciales están completamente utilizados por los hoteles y
los restantes negocios de la ciudad. Si un hotel dejase de operar
en la ciudad, el terreno sería utilizado rápidamente por alguna
otra empresa.

El alcalde está preocupado por quién acabará soportando la
incidencia del impuesto a corto plazo (un mes) y a largo plazo
(cinco años).

a) ¿Cómo se repartiría la incidencia del impuesto a corto plazo?

   #+begin_answer

   #+end_answer

b) ¿Y a largo plazo?

   #+begin_answer

   #+end_answer

c) ¿Cómo cambiarían sus respuestas si los hoteles de las
   localidades cercanas fueran sustitutos perfectos de los situados
   dentro de la ciudad?

   #+begin_answer

   #+end_answer


* COMMENT Q.2

Un producto se vende en un mercado competitivo cuyas curvas de
demanda y oferta son:
#+begin_export latex
\begin{gather*}
  P = 90 - 0.03 Q \\
  P = 30 + 0.02 Q
\end{gather*}
#+end_export
Determine el exceso de gravamen de un impuesto de \money{2.5} por
unidad vendida.


** Answer

Por hacer.


* Q.8

La demanda de mercado de un producto viene dada por $P = 20 - 0.001
Q$. La curva de oferta de mercado es perfectamente elástica: $P =
\price{10}$. Suponiendo que los efectos renta son despreciables:

a) Calcule el exceso de gravamen si se establece un impuesto de
   \money{2} por unidad producida.

b) Calcule el exceso de gravamen si el impuesto fuera de \money{3}
   por unidad producida.

c) Compare los resultados obtenidos en los apartados anterior. ¿Cómo
   cambia la ineficiciencia generada por el impuesto cuando cambia la
   tasa impositiva?

d) ¿Cómo cree que variará el exceso de gravamen en el largo plazo?
   ¿Será mayor o menor que a corto plazo?


** Answer

Por hacer.


* Q.9

En el mercado de un bien la curva de demanda es: $P = 10 - 0.01 Q$. El
bien es producido por un monopolista y los costes marginales son
constantes: $\CM = \price{2}$.

a) ¿Cuál sería el exceso de gravamen de un impuesto de \money{2}
   por unidad producida?

b) ¿Cómo cambiaría su respuesta al apartado anterior si el productor
   actuara como una empresa competitiva? Compare la ineficiencia
   provocada por el impuesto en un mercado competitivo y en un
   monopolio.


** Answer

Por hacer.


* Q.10

Después de introducir un impuesto sobre el precio de un bien no se
observan cambios en el consumo del bien. ¿Quiere esto decir que el
impuesto es eficiente en este caso?


** Answer

Por hacer.
