# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit01}}}: ejercicios

* Q.1
Discuta la veracidad o falsedad de las siguientes afirmaciones:

a) El sector público sólo produce bienes y servicios que no ofrecen
   las empresas privadas, como el alumbrado público o la seguridad
   ciudadana.

b) El gasto público no financiero mide el valor de los bienes y
   servicios producidos por las administraciones públicas.

c) La presión fiscal es el cociente entre los ingresos totales del
   sector público y el PIB.

d) El déficit público mide el valor total de los pasivos financieros
   de las Administraciones Públicas.

e) Las administraciones regionales realizan la mayor parte de los
   gastos de protección social.


** Answer

a) Falso. Contraejemplos: sanidad, educación.
b) Falso. También transferencias.
c) Falso. Es el porcentaje del PIB que representan los impuestos más
   cotizaciones
d) Falso. La definición dada corresponde a la deuda pública.
e) Falso. La función de protección social (pensiones) la lleva a cabo
   casi en exclusiva la Seguridad Social.


* Q.2

El mercado de un determinado bien es abastecido por una única empresa
cuya estructura de costes es: $C(Q) = 100 + 100 Q + Q^2$.  La función
inversa de demanda del mercado viene dada por: $P(Q) = \num{1300} -
Q$.

1. Determine el nivel de producción y el precio del monopolista.

2. Si el monopolista actuase como una empresa competitiva, ¿cuáles
   serían el precio y la cantidad de equilibrio?

3. Calcule la pérdida irrecuperable de eficiencia asociada a la
   situación de monopolio. ¿Cómo cambiaría el bienestar de los
   consumidores si se obligara al monopolio a fijar el precio
   competitivo? ¿Y el de los propietarios del monopolio?


** Answer

1. Condición de primer orden:
   #+begin_export latex
   \[
      \num{1300} - 2Q^M = 100 + 2 Q^M.
   \]
   #+end_export
   Por tanto $Q^M = 300$ unidades. Sustituyendo en la función
   inversa de demanda, $P^M = P(300) = \price{1000}$.

2. Igualando precio y coste marginal:
   #+begin_export latex
   \[
     \num{1300} -  Q^C = 100 + 2 Q^C.
   \]
   #+end_export
   Por tanto $Q^C = 400$ unidades y $P^C = 900$ €/u.

3. Geométricamente, la pérdida irrecuperable de
   eficiencia es un triángulo cuya altura (vista desde el eje de
   ordenadas) es:
   #+begin_export latex
   \[
     Q^C - Q^M = \units{100}.
   \]
   #+end_export
   y su base es:
   #+begin_export latex
   \[
     P(Q^M) - \CMg(Q^M) = \price{300}.
   \]
   #+end_export
   La pérdida irrecuperable de eficiencia es igual a $100 \cdot 300 /
   2 = \money{15000}$.

   #+xxx: fig file:fig-01_1047-01-*.pdf

   El cambio en el bienestar de los consumidores vendría dado por la
   variación del excedente de los consumidores:
   #+begin_export latex
   \[
     \big[P(Q^M) - P(Q^C)\big] \frac{Q^C + Q^M}{2} =
      (1000 - 900) (400 + 300) / 2 = \money{35000}.
   \]
   #+end_export
   En el caso del monopolista:
   #+begin_export latex
   \begin{multline*}
     \big[P(Q^C) - \CMg(Q^M)\big] \frac{Q^C - Q^M}{2} + \big[P(Q^M) -
     P(Q^C)\big] Q^M = \\
   (900 - 700) (400 - 300) / 2 - (1000 - 900) 300 = \money{-20000}.
   \end{multline*}
   #+end_export


* Q.3

Un monopolista puede identificar a dos grupos de consumidores y evitar
la reventa entre miembros de los diferentes grupos. La curva de
demanda de los consumidores con alta disposición a pagar es: $Q_A =
100 - P_A$, mientras que la curva de demanda de los consumidores con
baja disposición a pagar es: $Q_B = 20 - P_B$.  El monopolista fabrica
su producto con costes marginales constantes: $\CMg = \price{2}$.

1. Calcule los beneficios del monopolista cuando practica discriminación
   de precios de tercer grado. ¿Cuántas unidades vende y qué precios
   carga a cada grupo de consumidores?

2. Determine el equilibrio si se prohíbe al monopolista discriminar
   precios. ¿Mejora el bienestar social al prohibirse la
   discriminación en este caso? Compare el bienestar que obtienen los
   diferentes agentes con el que obtienen cuando es posible
   discriminar.


** Answer

1.  Ingreso marginal mercado A:
   #+begin_export latex
   \[
     \IMg_A = 100 - 2 Q_A.
   \]
   #+end_export
   Ingreso marginal mercado A:
   #+begin_export latex
   \[
     \IMg_B = 20 - 2 Q_B.
   \]
   #+end_export
   El coste marginal es constante y podemos resolver cada mercado por
   separado. En el caso del mercado A:
   #+begin_export latex
   \[
     Q_A = \units{49}; \quad P_A = \price{51}; \quad \EC_A = \money{1200.5}.
   \]
   #+end_export
   En el mercado B:
   #+begin_export latex
   \[
     Q_B = \units{9}; \quad P_B = \price{11}; \quad \EC_B = \money{40.5}.
   \]
   #+end_export
   Los beneficiós del monopolista son:
   #+begin_export latex
   \[
     \pi = P_A Q_A + P_B Q_B - C(Q_A + Q_B) =
     51 \cdot 49 + 11 \cdot 9 - 2 \cdot 58 =
     \money{2482}.
   \]
   #+end_export

2. La curva de demanda de mercado es la suma de las curvas de demanda
   de cada grupo. Si el precio es superior a 20, la curva de mercado
   coincide con la del grupo A. Si el precio es menor que 20:
   #+begin_export latex
   \[
     Q = 120 - 2 P \qquad\text{(si $P \leq 20$)}.
   \]
   #+end_export
   Tratemos de encontrar un equilibrio en este tramo. La curva inversa
   de demanda es:
   #+begin_export latex
   \[
     P = 60 - Q/2.
   \]
   #+end_export
   Condición de primer orden:
   #+begin_export latex
   \[
     60 - Q = 2.
   \]
   #+end_export
   Por lo que $Q = \units{58}$ y $P = \price{31}$. Pero esta solución
   contradice la condición $P \leq 20$: el monopolista fijará un
   precio superior a $20$ y sólo comprarán el producto los
   consumidores del mercado A. Equilibrio:
   #+begin_export latex
   \[
     Q = \units{49}; \quad P = \price{51}; \quad \EC = \money{1200.5}.
   \]
   #+end_export
   Los beneficios del monopolista son:
   #+begin_export latex
   \[
     \pi = P Q  - C(Q) = 51 \cdot 49 - 2 \cdot 49 = \money{2401}.
   \]
   #+end_export

   En este caso la discriminación es beneficiosa para la sociedad
   puesto que permitiría que se vendiera algo a los consumidores de
   baja disposición a pagar. Ningún agente mejora si se prohíbe la
   discriminación. Sólo los consumidores de disposición a pagar alta
   no empeoran.


* Q.4

En el mercado de un producto sólo participan dos consumidores
precio-aceptantes. La curva de demanda del consumidor con alta
disposición a pagar es: $Q_A = 9 - P_A$, y la curva de demanda de del
consumidor con baja disposición a pagar es: $Q_B = 7 - P_B$.  La única
empresa que vende en este mercado tiene unos costes marginales
constantes: $\CMg = \price{1}$.

a. Determine el equilibrio competitivo en este mercado.

b. Determine el equilibrio si la empresa actúa como un monopolista que
   fija un precio uniforme.

c. Determine el equilibrio cuando la empresa puede identificar
   perfectamente a cada consumidor y practica discriminación de
   precios de primer grado.

d. ¿Cuál de las tres situaciones analizadas sería preferible? ¿Por
   qué?


** Answer

a. La solución competitiva implica que el monopolista fija el mismo
   precio a los dos consumidores y el precio es igual al coste marginal:
   #+begin_export latex
   \[
     P_A = P_B = \CMg  = \price{1}.
   \]
   #+end_export
   A este precio el consumidor A compra $Q_A = \units{8}$ y el
   consumidor B compra $Q_B = \units{6}$.

   Bienestar:
   #+begin_export latex
   \[
     \EC_A = \money{32}; \quad \EC_B = \money{18}; \quad \pi = \money{0}.
   \]
   #+end_export
   Excedente total: $\ET = \money{50}$.

b. En primer lugar, determinamos la demanda de mercado. Si el precio
   es superior a \price{7}, la demanda de mercado coincide con la del
   consumidor A. Si el precio es inferior a \price{7}, sumamos las
   demandas de los dos consumidores:
   #+begin_export latex
   \[
     Q = 16 - 2 P.
   \]
   #+end_export
   Ingreso marginal:
   #+begin_export latex
   \[
     \IMg = 8 - Q.
   \]
   #+end_export
   Condición de primer orden:
   #+begin_export latex
   \[
     8 - Q^* = 1.
   \]
   #+end_export
   El monopolista produce $Q^* = \units{7}$ a un precio de $P^* =
   \price{4.5}$. Cada consumidor compra: $Q_A = \units{4.5}$ y $Q_B =
   \units{2.5}$.

   Bienestar:
   #+begin_export latex
   \[
     \EC_A = \money{10.125}; \quad
     \EC_B = \money{3.125}; \quad
     \pi = \money{24.5}.
   \]
   #+end_export
   Excedente total: $\ET = \money{37.75}$.

c. El monopolista ofrece a cada consumidor la cantidad que consumiría
   en la solución competitiva a cambio de la máxima disoposición a
   pagar por esas unidades. Por tanto, al consumidor A le ofrece $Q_A
   = \units{8}$ a cambio de \money{40}; y al consumidor B le ofrece
   $Q_B = \units{6}$ por \money{24}.

   Bienestar:
   #+begin_export latex
   \[
     \EC_A = \money{0}; \quad
     \EC_B = \money{0}; \quad
     \pi = \money{50}.
   \]
   #+end_export
   Excedente total: $\ET = \money{50}$.

d. Desde el punto de vista de la eficiencia, la peor situación es la
   del monopolista que carga un precio uniforme. Las otras dos
   situaciones (competencia perfecta y discriminación de primer grado)
   son equivalentes si solo tenemos en consideración la
   eficiencia. Sin embargo, la distribución de los excedentes es muy
   diferente en ambos casos.



# Local Variables:
# ispell-local-dictionary: "spanish"
# End:
