# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit04}}}: ejercicios


* Q.7

Imagine una economía donde sólo habitan dos consumidores, Aurora y Bernardo.

a) Si la función de bienestar social es:
   #+begin_export latex
   \[ W_1 = U_A + U_B \]
   #+end_export
   donde $U_A$ y $U_B$ son las utilidades de Aurora y Bernardo,
   respectivamente. Dibuje las curvas de indiferencia social. ¿Cómo
   describiría la importancia relativa que se asigna a cada
   utilidad?

b) ¿Cómo cambiaría su respuesta al apartado anterior si la función
   de bienestar social fuera $W_2 = U_A + 2 U_B$?

c) ¿Y si fuera $W_3 = \min\{U_A, U_B\}$?

d) Suponga que la función de posibilidades de utilidad es:
   #+xxx: fig fig-04_1047-01-*.pdf
   Muestre gráficamente como difieren las soluciones óptimas para
   las funciones de bienestar social de los apartados anteriores.

** Answer

Por hacer


* Q.8

Un programa público elevaría ligeramente el bienestar de los
ciudadanos más pobres pero disminuye considerablemente el bienestar
de los demás individuos. ¿Debería llevarse a cabo este programa si
se adopta el criterio utilitarista? ¿Y si se utiliza el criterio
/rawlsiano/?

** Answer

Por hacer


* Q.9

En un país sólo viven dos ciudadanos: Blanca y Teo. Blanca es
abogada y gana \money{50} por hora. Cuando la tasa impositiva sobre
la renta es $t = \SI{0}{\percent}$, Blanca trabaja 20 horas a la
semana; si $t = \SI{25}{\percent}$, trabajaría 16 horas; y si $t =
\SI{40}{\percent}$ sólo trabajaría 8 horas. Teo trabaja en un
pequeño taller de reparaciones y gana \money{6} por hora. Teo
siempre trabaja 20 horas por semana sea cual sea la tasa
impositiva. El gobierno está pensando en gravar la renta de Blanca
y transferir la recaudación a Teo.

a) Blanca y Teo tienen la misma función de utilidad: $U(Y) =
   Y^{1/2}$ donde $Y$ es la renta después de impuestos y
   transferencias. ¿Cuál de las tres tasas impositivas sería óptima
   desde un punto de vista utilitarista? ¿Y si se utiliza una
   función de bienestar social /rawlsiana/?

b) ¿Cambiarían las conclusiones del apartado anterior si la función
   de utilidad fuera $U(Y) = Y^{1/5}$?.

c) Suponga ahora que Blanca y Teo tienen funciones de utilidad
   diferentes. La utilidad de Blanca es $U_B(Y) = 0.25 Y^{1/2}$ y
   la de Teo es $U_T(Y) = Y^{1/2}$. Esto se debe a que Blanca sufre
   una discapacidad por lo que necesita más renta para alcanzar el
   mismo nivel de utilidad. ¿Cómo ordenarían ahora las diferentes
   alternativas los criterios utilitarista y /rawlsiano/?

** Answer

Por hacer


* Q.11

¿Es posible encontrar una situación en la que que el óptimo social de
acuerdo a una función de bienestar /rawlsiana/ coincida con el que se
obtendría con una función de bienestar utilitarista?  Represente
gráficamente.


* Q.12

Considere una economía con dos individuos $A$ y $B$. La tabla
siguiente muestra algunas combinaciones de utilidad que se
encuentran sobre la frontera de posibilidades de utilidad:

#+begin_export latex
\begin{center}
  \begin{tabular}{>{$}l<{$}*{2}{>{$}r<{$}}}
    \toprule
    \text{Opción} & U_A & U_B \\
    \midrule
    M & 100 &  0 \\
    N &  90 & 20 \\
    O &  60 & 30 \\
    P &  30 & 30 \\
    Q &  40 & 60 \\
    R &  10 & 70 \\
  \bottomrule
\end{tabular}
\end{center}
#+end_export

Indique cuál será la opción elegida de acuerdo con:

a) el criterio utilitarista.

b) el criterio igualitarista.

c) el criterio /rawlsiano/.


* Q.13

6. Analice la veracidad o falsedad de las siguientes afirmaciones:

   a) La aplicación del criterio /rawlsiano/ conduce necesariamente a
      una distribución igualitaria de la renta.

   b) Dada una curva de posibilidades de utilidad para dos individuos,
      la aplicación del criterio utilitarista llevará siempre a una
      distribución menos igualitaria que la del criterio /rawlsiano/.


* COMMENT Q.14

\DANGER Una economía está compuesta por dos individuos: $A$ y
$B$. $A$ dispone de un factor de producción que puede usar para
producir un bien de consumo $X$. $B$ no posee ninguna unidad del
factor de producción y, por tanto, no puede producir nada. Para
paliar esta situación el gobierno puede transferir a $B$ una
fracción $t$ de la producción de $A$. La producción de $A$ depende
de $t$ mediante la siguiente función:
#+begin_export latex
\[
  X(t) = 167 (1 - t) (t + 0.6)
\]
#+end_export
Suponiendo que la utilidad de ambos individuos es igual a la
cantidad que consumen del bien $X$, determinar qué fracción debería
$t$ debería establecerse de acuerdo a un criterio:

a) utilitarista.

b) /rawlsiano/.

c) igualitarista.
